import type { BackgroundTaskRecord, TaskStatus } from "./task-types.js";

export interface TextRenderable { invalidate(): void; render(width: number): string[]; }

export const ANSI = {
  reset: "\x1b[0m", bold: "\x1b[1m", dim: "\x1b[38;2;120;120;128m", text: "\x1b[38;2;220;220;221m",
  green: "\x1b[38;2;126;201;145m", amber: "\x1b[38;2;229;181;72m", red: "\x1b[38;2;232;111;111m", sky: "\x1b[38;2;174;215;255m",
};
const IDENTITY_PALETTE = ["\x1b[38;2;229;181;72m","\x1b[38;2;126;201;145m","\x1b[38;2;174;215;255m","\x1b[38;2;213;163;233m","\x1b[38;2;232;156;126m","\x1b[38;2;126;212;201m","\x1b[38;2;232;200;126m","\x1b[38;2;200;160;220m"];
const esc = /\x1b\[[0-9;]*m/g;
const norm = (s: string) => s.replace(/\t/g, "  ");
function wide(cp: number) { return cp >= 0x1100 && (cp <= 0x115f || (cp >= 0x2e80 && cp <= 0xa4cf) || (cp >= 0xac00 && cp <= 0xd7a3) || (cp >= 0x1f000 && cp <= 0x1faff)); }
export function visWidth(s: string): number { let w = 0; for (const ch of norm(s).replace(esc, "")) { const cp = ch.codePointAt(0) ?? 0; if (cp === 0x200d || (cp >= 0xfe00 && cp <= 0xfe0f)) continue; w += wide(cp) ? 2 : 1; } return w; }
export function truncAnsi(s: string, max: number): string { s = norm(s); if (visWidth(s) <= max) return s; if (max <= 1) return "…" + ANSI.reset; let out = "", cells = 0; for (let i = 0; i < s.length;) { if (s.charCodeAt(i) === 27) { const e = s.indexOf("m", i); if (e < 0) break; out += s.slice(i, e + 1); i = e + 1; continue; } const cp = s.codePointAt(i); if (cp == null) break; const ch = String.fromCodePoint(cp); const w = visWidth(ch); if (cells + w > max - 1) break; out += ch; cells += w; i += ch.length; } return out + "…" + ANSI.reset; }
export function truncPath(p: string, max: number): string { if (visWidth(p) <= max) return p; if (max < 8) return truncAnsi(p, max); const keep = max - 1; const a = Math.ceil(keep / 2), b = Math.floor(keep / 2); return p.slice(0, a) + "…" + p.slice(Math.max(0, p.length - b)); }
export function identitySlot(id: string) { let h = 0; for (let i = 0; i < id.length; i++) h = ((h * 31) + id.charCodeAt(i)) >>> 0; return h % 8; }
export const identityColor = (id: string) => IDENTITY_PALETTE[identitySlot(id)];
export const shortId = (id?: string) => id ? `bg…${id.replace(/^bg[_-]?/, "").slice(-6)}` : "bash";
function safeWidth(w: unknown) { return typeof w === "number" && Number.isFinite(w) ? Math.max(32, Math.floor(w)) : 80; }
export function chromeRenderable(build: (width: number) => string[]): TextRenderable { return { invalidate() {}, render(width) { const w = Math.min(120, safeWidth(width)); return build(w); } }; }
function chrome(width: number) { const gray = ANSI.dim, reset = ANSI.reset; const topTitled = (title: string, badge?: string) => { const l = `╭─ ${title} `; const rTry = badge ? ` ${badge} ─╮` : "╮"; const r = width - visWidth(l) - visWidth(rTry) >= 2 ? rTry : "╮"; return gray + l + "─".repeat(Math.max(2, width - visWidth(l) - visWidth(r))) + r + reset; }; const bot = () => gray + "╰" + "─".repeat(width - 2) + "╯" + reset; const row = (c: string, bar?: string) => { const final = truncAnsi(c, width - 4); const pad = Math.max(0, width - 2 - visWidth(" " + final + " ")); return (bar ?? gray + "│" + reset) + " " + final + " " + " ".repeat(pad) + gray + "│" + reset; }; const rowRight = (l: string, r: string) => { const maxL = Math.max(1, width - 5 - visWidth(r)); const left = truncAnsi(l, maxL); const pad = Math.max(1, width - 3 - visWidth(left) - visWidth(r)); return gray + "│" + reset + " " + left + " ".repeat(pad) + r + " " + gray + "│" + reset; }; return { topTitled, bot, row, rowRight }; }
function dur(ms?: number) { if (!ms || ms < 0) return "0s"; const s = Math.floor(ms / 1000); if (s < 60) return `${s}s`; const m = Math.floor(s / 60); return `${m}m${String(s % 60).padStart(2, "0")}s`; }
function elapsed(t: BackgroundTaskRecord, now = Date.now()) { return dur((Date.parse(t.endedAt ?? new Date(now).toISOString()) || now) - (Date.parse(t.startedAt ?? t.createdAt) || now)); }
function size(n?: number) { if (!n) return undefined; return n < 1024 ? `${n} B` : n < 1048576 ? `${Math.round(n / 1024)} KB` : `${(n / 1048576).toFixed(1)} MB`; }
function state(t: Partial<BackgroundTaskRecord>) { const cap = t.stopReason === "output_cap"; const s = cap ? "output_cap" : t.status; const table: Record<string, [string,string,string]> = { starting:["→","starting",ANSI.sky], running:["◐","running",ANSI.sky], exited:["✓","done",ANSI.green], failed:["✗","failed",ANSI.red], timed_out:["⚠","timed out",ANSI.amber], killed:["⊘","stopped",ANSI.dim], blocked:["?","blocked",ANSI.amber], output_cap:["⚠","output cap",ANSI.amber], orphaned:["⚠","orphaned",ANSI.amber], unknown:["·","unknown",ANSI.dim] }; return table[s ?? "unknown"] ?? table.unknown; }
function bar(t: Partial<BackgroundTaskRecord>) { const [,,c] = state(t); const danger = ["failed","timed_out","blocked","orphaned"].includes(t.status ?? "") || t.stopReason === "output_cap"; const color = danger ? c : (t.status === "killed" || t.status === "unknown" ? ANSI.dim : identityColor(t.taskId ?? "bash")); return color + "▌" + ANSI.reset; }
const kv = (k: string, v: string) => `${ANSI.dim}${k.padEnd(9)}${ANSI.reset}${v}`;
export function renderBashCall(args: unknown): TextRenderable | undefined { const a = args as Record<string, unknown>; if (!a?.run_in_background) return undefined; return chromeRenderable(w => { const c = chrome(w); const badge = ANSI.sky + "→ starting" + ANSI.reset; const lines = [c.topTitled(`${ANSI.bold}bash${ANSI.reset}${ANSI.dim} · background${ANSI.reset}`, badge), c.row(kv("command", String(a.command ?? "")))]; if (typeof a.timeout === "number") lines.push(c.row(kv("runtime", `max ${dur(a.timeout)}`))); lines.push(c.bot()); return lines; }); }
export function renderTaskCard(task: BackgroundTaskRecord, detail = false): TextRenderable { return chromeRenderable(w => { const c = chrome(w); const [g,l,col] = state(task); const badge = `${col}${g} ${l}${ANSI.reset}${task.startedAt ? ANSI.dim + " · " + elapsed(task) + ANSI.reset : ""}`; const b = bar(task); const title = `${b} ${identityColor(task.taskId)}${shortId(task.taskId)}${ANSI.reset}${ANSI.dim} · bash${ANSI.reset}`; const out = detail ? truncPath(task.outputPath, Math.max(10, w - 15)) : `.pi/…/output.log${size(task.outputBytes) ? " · " + size(task.outputBytes) : ""}${task.stopReason === "output_cap" ? " (cap)" : ""}`; const lines = [c.topTitled(title, badge), c.row(kv("command", task.command), b)]; if (detail) lines.push(c.row(kv("status", task.status), b)); if (task.exitCode != null) lines.push(c.row(kv("exit", String(task.exitCode)), b)); else if (task.signal) lines.push(c.row(kv("signal", String(task.signal)), b)); else lines.push(c.row(kv("runtime", `${elapsed(task)}${task.maxRuntimeMs ? ` · max ${dur(task.maxRuntimeMs)}${task.status === "timed_out" ? " (reached)" : ""}` : ""}`), b)); lines.push(c.row(kv("output", out), b)); if (detail) { if (size(task.outputBytes)) lines.push(c.row(kv("size", size(task.outputBytes)!), b)); if (task.pid) lines.push(c.row(kv("pid", `${task.pid}${task.pgid ? ` · pgid ${task.pgid}` : ""}`), b)); lines.push(c.row(kv("started", (task.startedAt ?? task.createdAt).replace("T", " ").slice(0, 19)), b)); if (task.ownerSessionId) lines.push(c.row(kv("owner", `session ${task.ownerSessionId.slice(0,4)}…`), b)); }
    if (!detail && (task.status === "failed" || task.status === "blocked" || task.status === "orphaned")) { lines.push(c.row("", b)); lines.push(c.row(task.status === "blocked" ? `/tasks stop ${shortId(task.taskId)}  ·  or answer in a real terminal` : task.status === "orphaned" ? "controls disabled · verify before stopping" : "read output.log for the failure", b)); } lines.push(c.bot()); return lines; }); }
export function renderTaskList(tasks: BackgroundTaskRecord[]): TextRenderable { return chromeRenderable(w => { const c = chrome(w); const counts = (s: TaskStatus) => tasks.filter(t => t.status === s).length; const badge = [`${counts("running")} running`, `${counts("blocked")} blocked`, `${counts("failed")} failed`, `${tasks.length} total`].filter(x => !x.startsWith("0 ")).join(" · "); const order = (t: BackgroundTaskRecord) => t.status === "blocked" ? 0 : t.status === "failed" ? 1 : t.status === "running" ? 2 : 3; const lines = [c.topTitled("tasks", badge)]; for (const t of [...tasks].sort((a,b)=>order(a)-order(b))) { const [g,l,col] = state(t); const right = `${ANSI.dim}${elapsed(t)}${ANSI.reset}  ${col}${t.exitCode != null ? `exit ${t.exitCode}` : l}${ANSI.reset}`; lines.push(c.rowRight(`${col}${g}${ANSI.reset} ${identityColor(t.taskId)}${shortId(t.taskId)}${ANSI.reset}  ${taskCommand(t)}`, right)); } if (!tasks.length) lines.push(c.row("No background tasks.")); lines.push(c.bot()); return lines; }); }
function taskCommand(t: BackgroundTaskRecord) { return ANSI.text + t.command.replace(/\s+/g, " ").trim() + ANSI.reset; }
export function renderTail(task: BackgroundTaskRecord, content: string, linesCount: number): TextRenderable { return chromeRenderable(w => { const c = chrome(w); const title = `${identityColor(task.taskId)}${shortId(task.taskId)}${ANSI.reset}${ANSI.dim} · output.log · last ${linesCount} lines${ANSI.reset}`; const out = [c.topTitled(title, size(task.outputBytes))]; for (const line of content.split(/\r?\n/)) out.push("  " + ANSI.dim + truncAnsi(line, w - 2) + ANSI.reset); out.push(c.bot()); return out; }); }
export function renderFooter(counts: { running: number; blocked: number; failed: number; }): TextRenderable { return chromeRenderable(w => { const full = `${ANSI.dim}BG${ANSI.reset}  ${ANSI.sky}${counts.running} running${ANSI.reset}${counts.blocked ? ` · ${ANSI.amber}${counts.blocked} blocked${ANSI.reset}` : ""}${counts.failed ? ` · ${ANSI.red}${counts.failed} failed${ANSI.reset}` : ""}`; const compact = `${ANSI.dim}BG${ANSI.reset} ${counts.running ? `${ANSI.sky}${counts.running}◐${ANSI.reset} ` : ""}${counts.blocked ? `${ANSI.amber}${counts.blocked}?${ANSI.reset} ` : ""}${counts.failed ? `${ANSI.red}${counts.failed}✗${ANSI.reset}` : ""}`.trimEnd(); const tiny = counts.failed ? `${ANSI.dim}BG${ANSI.reset} ${ANSI.red}${counts.failed}✗${ANSI.reset}` : counts.blocked ? `${ANSI.dim}BG${ANSI.reset} ${ANSI.amber}${counts.blocked}?${ANSI.reset}` : `${ANSI.dim}BG${ANSI.reset} ${ANSI.sky}${counts.running}◐${ANSI.reset}`; return [w >= 34 ? full : w >= 12 ? compact : tiny]; }); }
