import { createHash, randomBytes } from 'node:crypto';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import os from 'node:os';

export type UsageWindow = { label: 'primary' | 'secondary' | string; remainingPercent?: number; resetAt?: number; resetInSeconds?: number; stale?: boolean };
export type CodexAccountStatus = 'ok' | 'limited' | 'broken' | 'unknown';
export type CodexAccountSlot = { slot: string; label?: string; email?: string; accountIdHash?: string; activePi: boolean; activeCodex: boolean; status: CodexAccountStatus; usage?: { primary?: UsageWindow; secondary?: UsageWindow; updatedAt?: number; source?: 'cache' | 'probe' | 'unknown' }; problem?: { code: string; message: string } };
export type CodexUsage = { accounts: CodexAccountSlot[]; generatedAt: number; staleAfterMs: number; unavailable?: boolean; error?: string };
export type UsageEntry = { slot: string; windows?: Record<string, UsageWindow>; primary?: UsageWindow; secondary?: UsageWindow; updatedAt?: number; source?: 'cache' | 'probe' | 'unknown'; [key: string]: unknown };
export type Account = { slot: string; authPath: string; piAuthPath?: string; idHash: string; usage?: UsageEntry };
type InternalAccount = Account & { authHash: string };
type LaunchMetadata = { slot: string; generation: string; authHash: string; stateRoot: string; metadata_path?: string; expected_generation?: string };
export type PrepareLaunchResult = { schema_version: 1; selected_slot: string; slot: string; label?: string; reason: string; status: 'ok' | 'limited' | 'unknown'; isolated_dir: string; pi_agent_dir: string; codex_home: string; env: Record<string, string>; metadata: Record<string, string>; primary_remaining_percent?: number; secondary_remaining_percent?: number };

const sha = (s: string | Buffer) => createHash('sha256').update(s).digest('hex');
async function exists(p: string) { try { await fs.access(p); return true; } catch { return false; } }
async function readJson<T>(p: string, fallback: T): Promise<T> { try { return JSON.parse(await fs.readFile(p, 'utf8')) as T; } catch { return fallback; } }
async function writeJson(p: string, v: unknown) { await fs.mkdir(path.dirname(p), { recursive: true, mode: 0o700 }); await fs.writeFile(p, JSON.stringify(v, null, 2) + '\n', { mode: 0o600 }); }
async function salt(root: string) { const p = path.join(root, 'account-id-hash-salt'); if (!(await exists(p))) { await fs.mkdir(root, { recursive: true, mode: 0o700 }); await fs.writeFile(p, randomBytes(32).toString('hex') + '\n', { mode: 0o600 }); } return (await fs.readFile(p, 'utf8')).trim(); }
export function resolveStateRoot(env: NodeJS.ProcessEnv = process.env): string { return path.resolve(env.CODEX_AUTH_BALANCER_HOME || path.join(os.homedir(), '.bravo', 'codex-auth-balancer')); }
function normalizeWindow(label: string, value: any): UsageWindow | undefined { if (!value || typeof value !== 'object') return undefined; return { label: typeof value.label === 'string' ? value.label : label, remainingPercent: typeof value.remainingPercent === 'number' ? value.remainingPercent : typeof value.remaining_percent === 'number' ? value.remaining_percent : undefined, resetAt: typeof value.resetAt === 'number' ? value.resetAt : typeof value.reset_at === 'number' ? value.reset_at : undefined, resetInSeconds: typeof value.resetInSeconds === 'number' ? value.resetInSeconds : typeof value.reset_in_seconds === 'number' ? value.reset_in_seconds : undefined, stale: value.stale === true }; }
async function readUsageCache(stateRoot: string): Promise<Record<string, UsageEntry>> { return readJson(path.join(stateRoot, 'cache', 'usage.json'), {} as Record<string, UsageEntry>); }
async function usageCacheGeneratedAt(stateRoot: string): Promise<number | undefined> { const p = path.join(stateRoot, 'cache', 'usage.json'); const parsed = await readJson<any>(p, undefined); if (typeof parsed?.generatedAt === 'number') return parsed.generatedAt; if (typeof parsed?.generated_at === 'number') return parsed.generated_at; try { return (await fs.stat(p)).mtimeMs; } catch { return undefined; } }
export async function getUsage(options: { stateRoot?: string; staleAfterMs?: number } | string = {}): Promise<CodexUsage> { const stateRoot = typeof options === 'string' ? options : options.stateRoot || resolveStateRoot(); const staleAfterMs = typeof options === 'string' ? 5 * 60_000 : options.staleAfterMs ?? 5 * 60_000; try { const accounts = await loadInternalAccounts(stateRoot); const generatedAt = await usageCacheGeneratedAt(stateRoot) ?? Date.now(); const stale = Date.now() - generatedAt > staleAfterMs; return { generatedAt, staleAfterMs, error: stale ? 'stale' : undefined, accounts: accounts.map(a => ({ slot: a.slot, label: a.slot, accountIdHash: a.idHash, activePi: !!a.piAuthPath, activeCodex: true, status: 'unknown', usage: { primary: normalizeWindow('primary', a.usage?.primary ?? a.usage?.windows?.primary), secondary: normalizeWindow('secondary', a.usage?.secondary ?? a.usage?.windows?.secondary), updatedAt: typeof a.usage?.updatedAt === 'number' ? a.usage.updatedAt : Date.parse(String(a.usage?.refreshedAt || '')) || undefined, source: (a.usage?.source as any) || 'cache' } })) }; } catch (e) { return { accounts: [], generatedAt: Date.now(), staleAfterMs, unavailable: true, error: e instanceof Error ? e.message : String(e) }; } }
async function loadInternalAccounts(stateRoot = resolveStateRoot()): Promise<InternalAccount[]> { const dir = path.join(stateRoot, 'accounts'); const usage = await readUsageCache(stateRoot); const s = await salt(stateRoot); let slots: string[] = []; try { slots = await fs.readdir(dir); } catch { return []; } const out: InternalAccount[] = []; for (const slot of slots.sort()) { const authPath = path.join(dir, slot, 'auth.json'); if (!(await exists(authPath))) continue; const content = await fs.readFile(authPath); out.push({ slot, authPath, piAuthPath: (await exists(path.join(dir, slot, 'pi-openai-codex.json'))) ? path.join(dir, slot, 'pi-openai-codex.json') : undefined, authHash: sha(content), idHash: sha(s + ':' + slot), usage: usage[slot] }); } return out; }
export async function loadAccounts(stateRoot = resolveStateRoot()): Promise<Account[]> { return (await loadInternalAccounts(stateRoot)).map(({ authHash: _authHash, ...account }) => account); }
export async function refreshUsage(options: { stateRoot?: string; all?: boolean; slot?: string } | string = {}, opts: { all?: boolean; slot?: string } = {}) { const stateRoot = typeof options === 'string' ? options : options.stateRoot || resolveStateRoot(); const o = typeof options === 'string' ? opts : options; const cur = await readUsageCache(stateRoot); const accounts = await loadInternalAccounts(stateRoot); const wanted = new Set(o.slot ? [o.slot] : accounts.map(a => a.slot)); const normalized: Record<string, UsageEntry> = { ...cur }; for (const a of accounts) if (wanted.has(a.slot)) normalized[a.slot] = { ...(cur[a.slot] || {}), slot: a.slot, refreshedAt: new Date().toISOString(), liveProbe: false }; await writeJson(path.join(stateRoot, 'cache', 'usage.json'), normalized); return getUsage({ stateRoot }); }
export async function chooseSlot(stateRoot = resolveStateRoot(), slot?: string): Promise<InternalAccount> { const accounts = await loadInternalAccounts(stateRoot); const found = slot ? accounts.find(a => a.slot === slot) : accounts[0]; if (!found) throw new Error(slot ? `slot not found: ${slot}` : 'no accounts found'); return found; }
function assertSafeIsolatedDir(isolatedDir: string, stateRoot?: string) { const dir = path.resolve(isolatedDir); if (!path.isAbsolute(isolatedDir)) throw new Error('isolatedDir must be absolute'); if (dir === path.parse(dir).root || dir === os.homedir()) throw new Error('refusing unsafe isolatedDir'); if (stateRoot) { const root = path.resolve(stateRoot); if (dir === root || dir.startsWith(root + path.sep)) throw new Error('isolatedDir must not be inside stateRoot'); const marker = `${path.sep}auth${path.sep}codex-balancer`; if (!dir.endsWith(marker) && !dir.startsWith(os.tmpdir() + path.sep)) throw new Error('isolatedDir must be a run auth/codex-balancer dir or temp test dir'); } return dir; }
export async function prepareLaunch(isolatedDir: string, opts: { stateRoot?: string; slot?: string } = {}): Promise<PrepareLaunchResult> { const stateRoot = opts.stateRoot || resolveStateRoot(); isolatedDir = assertSafeIsolatedDir(isolatedDir, stateRoot); const acct = await chooseSlot(stateRoot, opts.slot); const piDir = path.join(isolatedDir, 'pi-agent'); const codexDir = path.join(isolatedDir, 'codex'); await fs.mkdir(piDir, { recursive: true, mode: 0o700 }); await fs.mkdir(codexDir, { recursive: true, mode: 0o700 }); await fs.copyFile(acct.authPath, path.join(codexDir, 'auth.json')); await fs.copyFile(acct.piAuthPath || acct.authPath, path.join(piDir, 'auth.json')); const metaPath = path.join(isolatedDir, 'balancer-metadata.json'); const meta: LaunchMetadata = { slot: acct.slot, generation: acct.authHash, expected_generation: acct.authHash, authHash: acct.authHash, stateRoot, metadata_path: metaPath }; await writeJson(metaPath, meta); const primary = normalizeWindow('primary', acct.usage?.primary ?? acct.usage?.windows?.primary); const secondary = normalizeWindow('secondary', acct.usage?.secondary ?? acct.usage?.windows?.secondary); return { schema_version: 1, selected_slot: acct.slot, slot: acct.slot, label: acct.slot, reason: 'selected', status: 'unknown', isolated_dir: isolatedDir, pi_agent_dir: piDir, codex_home: codexDir, env: { PI_CODING_AGENT_DIR: piDir, CODEX_HOME: codexDir }, metadata: { metadata_path: metaPath, launch_id: sha(metaPath).slice(0, 16) }, primary_remaining_percent: primary?.remainingPercent, secondary_remaining_percent: secondary?.remainingPercent }; }
export async function syncBack(isolatedDir: string, opts: { stateRoot?: string; slot?: string } = {}) { const meta = await readJson<LaunchMetadata | null>(path.join(isolatedDir, 'balancer-metadata.json'), null); if (!meta) throw new Error('missing balancer metadata'); const stateRoot = opts.stateRoot || meta.stateRoot || resolveStateRoot(); isolatedDir = assertSafeIsolatedDir(isolatedDir, stateRoot); if (path.resolve(isolatedDir) !== path.resolve(path.dirname(meta.metadata_path || path.join(isolatedDir, 'balancer-metadata.json')))) throw new Error('isolatedDir does not match metadata'); const slot = opts.slot || meta.slot; if (slot !== meta.slot) throw new Error('slot does not match metadata'); const authPath = path.join(stateRoot, 'accounts', slot, 'auth.json'); const currentHash = sha(await fs.readFile(authPath)); if (currentHash !== meta.generation) return { ok: false, conflict: true, retainedDir: isolatedDir }; const src = path.join(isolatedDir, 'codex', 'auth.json'); await fs.copyFile(src, authPath); return { ok: true, conflict: false, retainedDir: null }; }
export async function cleanupLaunch(isolatedDir: string) { const meta = await readJson<LaunchMetadata | null>(path.join(isolatedDir, 'balancer-metadata.json'), null); if (!meta) throw new Error('missing balancer metadata'); isolatedDir = assertSafeIsolatedDir(isolatedDir, meta.stateRoot); if (path.resolve(isolatedDir) !== path.resolve(path.dirname(meta.metadata_path || path.join(isolatedDir, 'balancer-metadata.json')))) throw new Error('isolatedDir does not match metadata'); await fs.rm(isolatedDir, { recursive: true, force: true }); return { ok: true }; }
export async function importAuthswap(from = path.join(os.homedir(), '.authswap', 'providers', 'openai'), opts: { stateRoot?: string; dryRun?: boolean; overwrite?: boolean; slot?: string } = {}) { const stateRoot = opts.stateRoot || resolveStateRoot(); if (!(await exists(path.join(from, 'accounts')))) throw new Error(`authswap source not found: ${path.join(from, 'accounts')}`); const entries = opts.slot ? [opts.slot] : await fs.readdir(path.join(from, 'accounts')); const imported: string[] = []; for (const slot of entries) { const srcDir = path.join(from, 'accounts', slot); const auth = path.join(srcDir, 'auth.json'); if (!(await exists(auth))) continue; const dstDir = path.join(stateRoot, 'accounts', slot); if (!opts.overwrite && await exists(path.join(dstDir, 'auth.json'))) throw new Error(`slot exists: ${slot}`); imported.push(slot); if (!opts.dryRun) { await fs.mkdir(dstDir, { recursive: true, mode: 0o700 }); await fs.copyFile(auth, path.join(dstDir, 'auth.json')); const pi = path.join(srcDir, 'pi-openai-codex.json'); if (await exists(pi)) await fs.copyFile(pi, path.join(dstDir, 'pi-openai-codex.json')); } } const usage = await readJson<Record<string, UsageEntry>>(path.join(from, 'cache', 'usage.json'), {}); if (!opts.dryRun && Object.keys(usage).length) await writeJson(path.join(stateRoot, 'cache', 'usage.json'), usage); return { imported, dryRun: !!opts.dryRun }; }
export function redactForJson<T>(v: T): T { return JSON.parse(JSON.stringify(v, (k, val) => /token|secret|refresh|key|auth_hash|expected_generation|generation|authHash/i.test(k) ? '[REDACTED]' : val)); }
