#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync, renameSync, copyFileSync, rmSync } from 'node:fs';
import { dirname, resolve, join, relative, basename } from 'node:path';
import { homedir, tmpdir, hostname } from 'node:os';
import { execFileSync, spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const VERSION = '0.1.0';
type Obj = Record<string, any>;
type Ctx = { root: string; loom: string; config: Obj };

class LoomError extends Error { constructor(public code: string, message: string, public details?: unknown, public exitCode = 1){ super(message); } }
const now = () => new Date().toISOString();
const q = (s: string) => `'${String(s).replaceAll("'", "''")}'`;
const json = (v: unknown) => JSON.stringify(v);
const home = () => process.env.LOOM_HOME || join(process.env.HOME || homedir(), '.loom');

function main() { try { run(process.argv.slice(2)); } catch (e) { fail(e); } }
function fail(e: unknown): never { const err = e instanceof LoomError ? e : new LoomError('GENERAL_ERROR', e instanceof Error ? e.message : String(e)); if (globalJson) console.log(json({ok:false,error:{code:err.code,message:err.message,details:err.details}})); else console.error(`loom: ${err.code}: ${err.message}`); process.exit(err.exitCode); }
let globalJson = false;

function run(argv0: string[]) {
  const {globals, argv} = parseGlobals(argv0); globalJson = globals.json;
  if (globals.version) return out(VERSION);
  if (argv.length === 0 || globals.help) return help();
  const [cmd, ...rest] = argv;
  switch(cmd){
    case 'init': return cmdInit(rest, globals);
    case 'create': return withCtx(globals, rest, c=>cmdCreate(c, rest));
    case 'show': return withCtx(globals, rest, c=>cmdShow(c, rest));
    case 'tree': return withCtx(globals, rest, c=>cmdTree(c, rest));
    case 'decompose': return withCtx(globals, rest, c=>cmdDecompose(c, rest));
    case 'branch': return withCtx(globals, rest, c=>cmdBranch(c, rest));
    case 'link': return withCtx(globals, rest, c=>cmdLink(c, rest));
    case 'decide': return withCtx(globals, rest, c=>cmdDecide(c, rest));
    case 'resolve': return withCtx(globals, rest, c=>cmdResolve(c, rest));
    case 'note': return withCtx(globals, rest, c=>cmdNote(c, rest));
    case 'index': return withCtx(globals, rest, c=>cmdIndex(c, rest));
    case 'search': return withCtx(globals, rest, c=>cmdSearch(c, rest));
    case 'context': return withCtx(globals, rest, c=>cmdContext(c, rest));
    case 'artifact': return withCtx(globals, rest, c=>cmdArtifact(c, rest));
    case 'reference': return withCtx(globals, rest, c=>cmdReference(c, rest));
    case 'registry': return cmdRegistry(rest);
    case 'agent': return maybeCtx(globals, rest, c=>cmdAgent(c, rest), ()=>cmdAgentNoCtx(rest));
    case 'inbox': return withCtx(globals, rest, c=>cmdInbox(c, rest));
    case 'notify': return withCtx(globals, rest, c=>cmdNotify(c, rest));
    case 'spawn': return withCtx(globals, rest, c=>cmdSpawn(c, rest));
    case 'dispatch': return withCtx(globals, rest, c=>cmdDispatch(c, rest));
    case 'current': return withCtx(globals, rest, c=>outData({loom:c.config.id, alias:c.config.name, root:c.root, loomPath:c.loom}));
    case 'doctor': return withCtx(globals, rest, c=>outData({ok:true, loom:c.config.id, checks:['basic']}));
    default: throw new LoomError('INVALID_ARGUMENT', `unknown command ${cmd}`, undefined, 2);
  }
}

function parseGlobals(argv: string[]) { const globals: Obj = {json:false}; const outv:string[]=[]; for(let i=0;i<argv.length;i++){ const a=argv[i]; if(a==='--json') globals.json=true; else if(a==='--help'||a==='-h') globals.help=true; else if(a==='--version') globals.version=true; else if(a==='-L'||a==='--loom') globals.loom=argv[++i]; else if(a==='--cwd') globals.cwd=argv[++i]; else outv.push(a);} return {globals, argv: outv}; }
function flag(args:string[], name:string, def?:string){ const i=args.indexOf(name); return i>=0 ? args[i+1] : def; }
function has(args:string[], name:string){ return args.includes(name); }
function stripFlags(args:string[], names:string[]){ const r:string[]=[]; for(let i=0;i<args.length;i++){ if(names.includes(args[i])) i++; else if(args[i].startsWith('--') && names.includes(args[i])) i++; else r.push(args[i]); } return r; }
function out(s:string){ console.log(s); }
function outData(data:unknown){ console.log(globalJson ? json({ok:true,data}) : human(data)); }
function human(v:any): string { if(typeof v==='string') return v; if(Array.isArray(v)) return v.map(human).join('\n'); return JSON.stringify(v,null,2); }

function help(){ out(`loom ${VERSION}\n\nUsage: loom [-L loom] <command> [args]\n\nCommands: init, create, show, tree, decompose, branch, link, decide, resolve, note, index rebuild, search, context, artifact, reference, registry, agent, inbox, notify, spawn, dispatch\n\nAgents: run 'loom agent guide' for a compact Loom operating guide.`); }

function cmdInit(args:string[], globals:Obj){ const cwd=resolve(globals.cwd||process.cwd()); const title=flag(args,'--title')||flag(args,'-t')||'Untitled Loom'; const name=flag(args,'--name')||slug(title); const loom=join(cwd,'.loom'); if(existsSync(loom)) throw new LoomError('REGISTRY_CONFLICT','Loom already exists here'); mkdirSync(join(loom,'nodes'),{recursive:true}); mkdirSync(join(loom,'artifacts'),{recursive:true}); mkdirSync(join(loom,'runtime','context'),{recursive:true}); const id='lm_'+Math.random().toString(36).slice(2,10); const cfg:any={schemaVersion:1,id,name,title,root:'.',workspaces:[]}; const ws=flag(args,'--workspace'); if(ws){ const [wid,path]=ws.includes('=')?ws.split('='):['repo',ws]; cfg.workspaces.push({id:wid,path,kind:'git'}); } writeAtomic(join(loom,'loom.json'), JSON.stringify(cfg,null,2)+'\n'); writeAtomic(join(loom,'events.jsonl'),''); ensureRegistry(); regExec(`insert or replace into registry_looms(id,alias,title,root_path,loom_path,last_seen_at) values(${q(id)},${q(name)},${q(title)},${q(cwd)},${q(loom)},${q(now())});`); ensureRuntime(loom); ensureIndex(loom); outData({loom:cfg, path:loom}); }

function withCtx(globals:Obj, args:string[], fn:(c:Ctx)=>void){ fn(resolveCtx(globals,args)); }
function maybeCtx(globals:Obj,args:string[], fn:(c:Ctx)=>void, no:()=>void){ try{fn(resolveCtx(globals,args));}catch(e){ if(e instanceof LoomError && e.code==='LOOM_NOT_FOUND') no(); else throw e; } }
function resolveCtx(globals:Obj,args:string[]):Ctx{ let ref=globals.loom; for(const a of args){ const m=a.match(/^([^:]+):(N-\d+)$/); if(m){ ref=m[1]; break; }} if(!ref && process.env.LOOM_CONTEXT && existsSync(process.env.LOOM_CONTEXT)){ const c=JSON.parse(readFileSync(process.env.LOOM_CONTEXT,'utf8')); ref=process.env.LOOM_DEFAULT || c.default; } if(!ref && process.env.LOOM_DEFAULT) ref=process.env.LOOM_DEFAULT; let loomPath:string|undefined; if(ref) loomPath=resolveLoomRef(ref); else loomPath=findUp(globals.cwd||process.cwd()); if(!loomPath) throw new LoomError('LOOM_NOT_FOUND','could not resolve Loom; use -L <id-or-alias>'); const cfg=JSON.parse(readFileSync(join(loomPath,'loom.json'),'utf8')); return {root: dirname(loomPath), loom: loomPath, config:cfg}; }
function findUp(start:string){ let d=resolve(start); while(true){ const p=join(d,'.loom'); if(existsSync(join(p,'loom.json'))) return p; const n=dirname(d); if(n===d) return undefined; d=n; }}
function resolveLoomRef(ref:string){ ensureRegistry(); const rows=regJson(`select * from registry_looms where id=${q(ref)} or alias=${q(ref)};`); if(rows.length>1) throw new LoomError('AMBIGUOUS_LOOM',`ambiguous Loom alias ${ref}`); if(rows.length===1) return rows[0].loom_path; const p=resolve(ref); if(existsSync(join(p,'.loom','loom.json'))) return join(p,'.loom'); if(existsSync(join(p,'loom.json'))) return p; throw new LoomError('LOOM_NOT_FOUND',`unknown Loom ${ref}`); }

function lock<T>(c:Ctx, fn:()=>T):T{ const lockDir=join(c.loom,'runtime','loom.lock'); mkdirSync(join(c.loom,'runtime'),{recursive:true}); const start=Date.now(); while(true){ try{ mkdirSync(lockDir); writeFileSync(join(lockDir,'meta.json'),json({pid:process.pid,host:hostname(),time:now()})); break; } catch { if(Date.now()-start>10000) throw new LoomError('LOCK_TIMEOUT','could not acquire Loom lock',undefined,5); Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,50); } } try{return fn();} finally{ rmSync(lockDir,{recursive:true,force:true}); } }
function writeAtomic(path:string, content:string){ mkdirSync(dirname(path),{recursive:true}); const tmp=`${path}.tmp-${process.pid}-${Date.now()}`; writeFileSync(tmp,content); renameSync(tmp,path); }
function slug(s:string){ return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'node'; }
function nextNodeId(c:Ctx){ const nums=listNodes(c).map(n=>Number(n.id.slice(2))).filter(Number.isFinite); const n=Math.max(0,...nums)+1; return `N-${String(n).padStart(4,'0')}`; }
function nextMsgId(c:Ctx){ ensureRuntime(c.loom); const rows=rtJson(c.loom,`select id from inbox_items;`); const nums=rows.map((r:any)=>Number(String(r.id).slice(2))).filter(Number.isFinite); return `M-${String(Math.max(0,...nums)+1).padStart(4,'0')}`; }

function parseNodeRef(a:string){ const m=a.match(/^(?:([^:]+):)?(N-\d+)$/); if(!m) throw new LoomError('INVALID_REF',`invalid node ref ${a}`); return m[2]; }
function nodePath(c:Ctx,id:string){ const found=readdirSync(join(c.loom,'nodes')).find(f=>f.startsWith(id+'-')&&f.endsWith('.md')); if(!found) throw new LoomError('NODE_NOT_FOUND',`node not found ${id}`,undefined,3); return join(c.loom,'nodes',found); }
function readNode(c:Ctx,id:string){ const path=nodePath(c,id); const raw=readFileSync(path,'utf8'); const m=raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/); if(!m) throw new LoomError('INVALID_FRONTMATTER',`invalid frontmatter ${path}`,{path},6); return {path, fm: parseYaml(m[1]), body:m[2]}; }
function writeNode(c:Ctx,fm:Obj,body:string){ fm.updated_at=now(); const path = existsMaybe(c,fm.id) || join(c.loom,'nodes',`${fm.id}-${slug(fm.title)}.md`); writeAtomic(path,`---\n${toYaml(fm)}---\n\n${body}`); return path; }
function existsMaybe(c:Ctx,id:string){ try{return nodePath(c,id);}catch{return undefined;} }
function listNodes(c:Ctx){ const dir=join(c.loom,'nodes'); if(!existsSync(dir)) return [] as any[]; return readdirSync(dir).filter(f=>f.endsWith('.md')).map(f=>{try{const raw=readFileSync(join(dir,f),'utf8'); const m=raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/); if(!m)return null; return {path:join(dir,f), fm:parseYaml(m[1]), body:m[2], id:parseYaml(m[1]).id};}catch{return null;}}).filter(Boolean) as any[]; }

function parseYaml(src:string):Obj{ const o:Obj={}; const lines=src.split(/\r?\n/); for(let i=0;i<lines.length;i++){ const line=lines[i]; if(!line.trim()) continue; const m=line.match(/^([A-Za-z0-9_]+):(?:\s*(.*))?$/); if(!m) continue; const key=m[1], val=m[2]??''; if(val===''){ const arr:any[]=[]; while(i+1<lines.length && lines[i+1].startsWith('  - ')){ i++; const item:Obj={}; let rest=lines[i].slice(4); const im=rest.match(/^([^:]+):\s*(.*)$/); if(im) item[im[1]]=parseScalar(im[2]); while(i+1<lines.length && lines[i+1].startsWith('    ')){ i++; const sm=lines[i].trim().match(/^([^:]+):\s*(.*)$/); if(sm) item[sm[1]]=parseScalar(sm[2]); } arr.push(item); } o[key]=arr; } else o[key]=parseScalar(val); } return o; }
function parseScalar(v:string):any{ v=v.trim(); if(v==='null')return null; if(v==='true')return true; if(v==='false')return false; if(v.startsWith('[')&&v.endsWith(']')) return v.slice(1,-1).split(',').map(s=>s.trim()).filter(Boolean); return v.replace(/^"|"$/g,''); }
function toYaml(o:Obj){ let s=''; for(const [k,v] of Object.entries(o)){ if(v===undefined) continue; if(Array.isArray(v)){ if(v.length===0){s+=`${k}: []\n`; continue;} s+=`${k}:\n`; for(const it of v){ if(typeof it==='object'){ const es=Object.entries(it); s+=`  - ${es[0][0]}: ${es[0][1]}\n`; for(const [kk,vv] of es.slice(1)) s+=`    ${kk}: ${vv}\n`; } else s+=`  - ${it}\n`; } } else if(typeof v==='string' && v.includes(': ')) s+=`${k}: "${v.replaceAll('"','\\"')}"\n`; else s+=`${k}: ${v}\n`; } return s; }
function bodyFor(title:string, summary=''){ return `# Summary\n\n${summary||title}\n\n# Context\n\n\n# Analysis\n\n\n# Result\n\nPending.\n`; }
function appendEvent(c:Ctx,e:Obj){ e.event_id=e.event_id||`E-${Date.now()}-${Math.random().toString(36).slice(2,6)}`; e.time=e.time||now(); writeFileSync(join(c.loom,'events.jsonl'), json(e)+'\n', {flag:'a'}); return e.event_id; }

function cmdCreate(c:Ctx,args:string[]){ lock(c,()=>{ const title=stripFlags(args,['--kind','--parent','--summary','--tag'])[0]; if(!title) throw new LoomError('INVALID_ARGUMENT','title required',undefined,2); const id=nextNodeId(c); const tags:string[]=[]; for(let i=0;i<args.length;i++) if(args[i]==='--tag') tags.push(args[i+1]); const fm:any={id,title,kind:flag(args,'--kind','task'),state:'open',parent:flag(args,'--parent')||null,summary:flag(args,'--summary')||title,tags,created_at:now(),updated_at:now()}; writeNode(c,fm,bodyFor(title,fm.summary)); const ev=appendEvent(c,{type:'node.created',node_id:id,title,kind:fm.kind}); rebuildIndex(c); outData({node:summary(c,fm), event_id:ev}); }); }
function cmdShow(c:Ctx,args:string[]){ const id=parseNodeRef(args[0]||''); const n=readNode(c,id); outData({node:summary(c,n.fm), frontmatter:n.fm, body:n.body}); }
function summary(c:Ctx,fm:Obj){ return {id:fm.id,title:fm.title,kind:fm.kind,state:fm.state,parent:fm.parent??null,summary:fm.summary,path:existsMaybe(c,fm.id)||''}; }
function cmdTree(c:Ctx,args:string[]){ const root=args[0]?parseNodeRef(args[0]):null; const nodes=listNodes(c).map(n=>n.fm); const rec=(pid:any,depth=0):string[]=>nodes.filter(n=>(n.parent??null)===(pid??null)).flatMap(n=>[`${'  '.repeat(depth)}${n.id} ${n.title} [${n.kind}/${n.state}]`,...rec(n.id,depth+1)]); out(globalJson?json({ok:true,data:{lines:rec(root)}}):rec(root).join('\n')); }
function createChild(c:Ctx,parent:string,title:string,kind:string,edge?:Obj){ const id=nextNodeId(c); const fm:any={id,title,kind,state:'open',parent,summary:title,tags:[],edges:edge?[edge]:[],created_at:now(),updated_at:now()}; writeNode(c,fm,bodyFor(title)); return id; }
function cmdDecompose(c:Ctx,args:string[]){ lock(c,()=>{ const src=parseNodeRef(args[0]); const ids=args.slice(1).map(t=>createChild(c,src,t,'task')); const ev=appendEvent(c,{type:'node.decomposed',source:src,children:ids}); rebuildIndex(c); outData({source:src, children:ids, event_id:ev}); }); }
function cmdBranch(c:Ctx,args:string[]){ lock(c,()=>{ const src=parseNodeRef(args[0]); const ids=args.slice(1).map(t=>createChild(c,src,t,'variant',{type:'variant_of',to:src})); const ev=appendEvent(c,{type:'node.branched',source:src,variants:ids}); rebuildIndex(c); outData({source:src, variants:ids, event_id:ev}); }); }
function cmdLink(c:Ctx,args:string[]){ lock(c,()=>{ const from=parseNodeRef(args[0]); const to=flag(args,'--to'); const type=flag(args,'--type','references'); if(!to) throw new LoomError('INVALID_ARGUMENT','--to required',undefined,2); const n=readNode(c,from); n.fm.edges=[...(n.fm.edges||[]),{type,to}]; writeNode(c,n.fm,n.body); const ev=appendEvent(c,{type:'edge.added',from,to,edge_type:type}); rebuildIndex(c); outData({from,to,type,event_id:ev}); }); }
function cmdDecide(c:Ctx,args:string[]){ lock(c,()=>{ const src=parseNodeRef(args[0]); const chosen=flag(args,'--choose'); if(!chosen) throw new LoomError('INVALID_ARGUMENT','--choose required',undefined,2); const title=`Decision: ${readNode(c,src).fm.title}`; const id=nextNodeId(c); const fm:any={id,title,kind:'decision',state:'resolved',parent:src,summary:flag(args,'--summary')||`Choose ${chosen}`,edges:[{type:'chooses',to:chosen}],resolution:'chosen',created_at:now(),updated_at:now()}; writeNode(c,fm,bodyFor(title,fm.summary).replace('Pending.',fm.summary)); const ev=appendEvent(c,{type:'node.created',node_id:id,title,kind:'decision'}); rebuildIndex(c); outData({node:summary(c,fm), chosen, event_id:ev}); }); }
function cmdResolve(c:Ctx,args:string[]){ lock(c,()=>{ const id=parseNodeRef(args[0]); const n=readNode(c,id); n.fm.state='resolved'; n.fm.resolution=flag(args,'--resolution','answered'); n.fm.summary=flag(args,'--summary',n.fm.summary||'Resolved'); const body=n.body+`\n\n# Resolution ${now()}\n\n${n.fm.summary}\n`; writeNode(c,n.fm,body); const ev=appendEvent(c,{type:'node.resolved',node_id:id,resolution:n.fm.resolution}); rebuildIndex(c); routeUpdate(c,id,n.fm.summary); outData({node:summary(c,n.fm), event_id:ev}); }); }
function cmdNote(c:Ctx,args:string[]){ lock(c,()=>{ const id=parseNodeRef(args[0]); const msg=args.slice(1).join(' '); const n=readNode(c,id); writeNode(c,n.fm,n.body+`\n\n# Note ${now()}\n\n${msg}\n`); const ev=appendEvent(c,{type:'node.updated',node_id:id}); rebuildIndex(c); outData({node:summary(c,n.fm), event_id:ev}); }); }

function cmdIndex(c:Ctx,args:string[]){ if(args[0]!=='rebuild') throw new LoomError('INVALID_ARGUMENT','expected index rebuild',undefined,2); lock(c,()=>{ rebuildIndex(c); outData({rebuilt:true}); }); }
function ensureIndex(loom:string){ sqlite(join(loom,'index.sqlite'),`pragma user_version=1; create table if not exists nodes(id text primary key, slug text, title text, kind text, state text, parent_id text, summary text, body text, path text, created_at text, updated_at text); create table if not exists edges(from_loom_id text, from_node_id text, to_loom_id text, to_node_id text, type text, label text, created_at text); create table if not exists chunks(id text primary key,node_id text,heading_path text,text text,start_line integer,end_line integer); create table if not exists node_files(node_id text,role text,workspace text,path text,label text,kind text); create table if not exists node_closure(ancestor_id text,descendant_id text,depth integer); create virtual table if not exists chunks_fts using fts5(node_id, title, text);`); }
function rebuildIndex(c:Ctx){ ensureIndex(c.loom); const db=join(c.loom,'index.sqlite'); sqlite(db,'delete from nodes; delete from edges; delete from chunks; delete from node_files; delete from node_closure; delete from chunks_fts;'); const ns=listNodes(c); for(const n of ns){ const fm=n.fm, body=n.body; sqlite(db,`insert into nodes values(${q(fm.id)},${q(slug(fm.title))},${q(fm.title)},${q(fm.kind)},${q(fm.state)},${q(fm.parent||'')},${q(fm.summary||'')},${q(body)},${q(relative(c.loom,n.path))},${q(fm.created_at||'')},${q(fm.updated_at||'')});`); for(const e of fm.edges||[]) sqlite(db,`insert into edges values(${q(c.config.id)},${q(fm.id)},${q(String(e.to).includes(':')?String(e.to).split(':')[0]:c.config.id)},${q(String(e.to).split(':').pop()||'')},${q(e.type)},${q(e.label||'')},${q(fm.updated_at||'')});`); for(const a of fm.artifacts||[]) sqlite(db,`insert into node_files values(${q(fm.id)},'artifact',null,${q(a.path)},${q(a.label||'')},${q(a.kind||'')});`); for(const r of fm.references||[]) sqlite(db,`insert into node_files values(${q(fm.id)},'reference',${q(r.workspace||'')},${q(r.path)},${q(r.label||'')},${q(r.kind||'')});`); sqlite(db,`insert into chunks values(${q(fm.id+':body')},${q(fm.id)},'',${q(body)},1,null); insert into chunks_fts(node_id,title,text) values(${q(fm.id)},${q(fm.title)},${q(body)});`); } for(const n of ns){ let d=0, cur=n.fm.parent; while(cur){ d++; sqlite(db,`insert into node_closure values(${q(cur)},${q(n.fm.id)},${d});`); const p=ns.find(x=>x.fm.id===cur); cur=p?.fm.parent; } } }
function cmdSearch(c:Ctx,args:string[]){ ensureIndex(c.loom); const query=args.filter(a=>!a.startsWith('--') && a!==flag(args,'--under') && a!==flag(args,'--kind') && a!==flag(args,'--state')).join(' '); const under=flag(args,'--under'); let sql=`select nodes.*, bm25(chunks_fts) as score, snippet(chunks_fts,2,'[',']','...',12) as snippet from chunks_fts join nodes on nodes.id=chunks_fts.node_id where chunks_fts match ${q(query||'*')}`; if(under) sql+=` and nodes.id in (select descendant_id from node_closure where ancestor_id=${q(parseNodeRef(under))})`; sql+=' limit 20;'; const rows=dbJson(join(c.loom,'index.sqlite'),sql); outData({query, hits:rows.map((r:any)=>({node:{id:r.id,title:r.title,kind:r.kind,state:r.state,parent:r.parent_id||null,path:r.path},score:r.score,snippet:r.snippet}))}); }
function cmdContext(c:Ctx,args:string[]){ const id=parseNodeRef(args[0]); const n=readNode(c,id); const nodes=listNodes(c).map(x=>x.fm); const ancestors=[]; let cur=n.fm.parent; while(cur){ const p=nodes.find(x=>x.id===cur); if(!p) break; ancestors.unshift({id:p.id,title:p.title,summary:p.summary}); cur=p.parent; } const children=nodes.filter(x=>x.parent===id).map(x=>({id:x.id,title:x.title,kind:x.kind,state:x.state})); const data={loom:{id:c.config.id,alias:c.config.name,root:c.root,workspaces:c.config.workspaces||[]},node:summary(c,n.fm),ancestors,children,links:n.fm.edges||[],artifacts:n.fm.artifacts||[],references:n.fm.references||[],body:n.body}; outData(data); }

function cmdArtifact(c:Ctx,args:string[]){ const sub=args[0]; if(sub==='list'){ const n=readNode(c,parseNodeRef(args[1])); return outData({artifacts:n.fm.artifacts||[]}); } if(sub!=='add') throw new LoomError('INVALID_ARGUMENT','artifact add|list',undefined,2); lock(c,()=>{ const id=parseNodeRef(args[1]); const src=args[2]; const n=readNode(c,id); const destRel=join('.loom','artifacts',id,basename(src)); const dest=join(c.root,destRel); if(has(args,'--copy')){ mkdirSync(dirname(dest),{recursive:true}); copyFileSync(resolve(src),dest); } n.fm.artifacts=[...(n.fm.artifacts||[]),{path:destRel,label:flag(args,'--label')||basename(src),kind:flag(args,'--kind')||'artifact'}]; writeNode(c,n.fm,n.body); rebuildIndex(c); outData({artifacts:n.fm.artifacts}); }); }
function cmdReference(c:Ctx,args:string[]){ const sub=args[0]; if(sub==='list'){ const n=readNode(c,parseNodeRef(args[1])); return outData({references:n.fm.references||[]}); } if(sub!=='add') throw new LoomError('INVALID_ARGUMENT','reference add|list',undefined,2); lock(c,()=>{ const id=parseNodeRef(args[1]); const pathArg=positionalAfter(args.slice(2), ['--workspace','--label','--kind'])[0]; if(!pathArg) throw new LoomError('INVALID_ARGUMENT','reference path required',undefined,2); const n=readNode(c,id); n.fm.references=[...(n.fm.references||[]),{workspace:flag(args,'--workspace'),path:pathArg,label:flag(args,'--label')||pathArg,kind:flag(args,'--kind')||'source'}]; writeNode(c,n.fm,n.body); rebuildIndex(c); outData({references:n.fm.references}); }); }

function positionalAfter(args:string[], flagsWithValues:string[]){ const out:string[]=[]; for(let i=0;i<args.length;i++){ if(flagsWithValues.includes(args[i])) { i++; continue; } if(args[i].startsWith('-')) continue; out.push(args[i]); } return out; }

function ensureRuntime(loom:string){ mkdirSync(join(loom,'runtime'),{recursive:true}); sqlite(join(loom,'runtime','runtime.sqlite'),`pragma user_version=1; create table if not exists inbox_items(id text primary key, recipient_agent_id text not null,node_id text,type text not null,priority text not null,state text not null,payload_json text,delivery_state text not null,delivery_attempts integer not null default 0,delivery_error text,created_at text not null,updated_at text); create table if not exists participants(agent_id text primary key, role text, joined_at text, last_seen_at text); create table if not exists subscriptions(agent_id text not null, scope_json text not null, created_at text not null);`); }
function cmdAgentNoCtx(args:string[]){ if(args[0]==='guide') return agentGuide(); throw new LoomError('LOOM_NOT_FOUND','agent command requires Loom except agent guide'); }
function cmdAgent(c:Ctx,args:string[]){ ensureRuntime(c.loom); if(args[0]==='guide') return agentGuide(); if(args[0]==='join'){ const a=args[1]; rt(c.loom,`insert or replace into participants values(${q(a)},${q(flag(args,'--role','agent')!)},${q(now())},${q(now())});`); return outData({agent_id:a, joined:true}); } if(args[0]==='default'){ const a=args[1]; ensureRegistry(); regExec(`insert or replace into registry_agent_defaults values(${q(a)},${q(c.config.id)});`); return outData({agent_id:a, default:c.config.id}); } if(args[0]==='subscribe'){ const a=args[1]; rt(c.loom,`insert into subscriptions values(${q(a)},${q(json({under:flag(args,'--under')||null, loom:c.config.id}))},${q(now())});`); return outData({agent_id:a, subscribed:true}); } throw new LoomError('INVALID_ARGUMENT','agent guide|join|default|subscribe',undefined,2); }
function agentGuide(){ const here=dirname(fileURLToPath(import.meta.url)); const candidates=[resolve(here,'..','..','prompts','agent-guide.md'), resolve(here,'..','prompts','agent-guide.md'), resolve(process.cwd(),'docs/specs/loom-v1/agent-guide.md')]; const p=candidates.find(existsSync); out(readFileSync(p || candidates[0],'utf8')); }
function cmdInbox(c:Ctx,args:string[]){ ensureRuntime(c.loom); const sub=args[0]; if(sub==='send') return lock(c,()=>{ const agent=args[1]; const id=nextMsgId(c); const payload={message:flag(args,'--message')||'',subject:flag(args,'--subject'),sender_agent_id:process.env.LOOM_AGENT_ID,relation:'peer'}; const node=flag(args,'--node'); rt(c.loom,`insert into inbox_items values(${q(id)},${q(agent)},${q(node||'')},${q(flag(args,'--type','assignment')!)},${q(flag(args,'--priority','normal')!)},'open',${q(json(payload))},'none',0,null,${q(now())},${q(now())});`); appendEvent(c,{type:'inbox.sent',item_id:id,recipient_agent_id:agent,node_id:node}); deliver(c,id); outData({item:inboxGet(c,id)}); }); if(sub==='next'){ const agent=args[1]||process.env.LOOM_AGENT_ID; if(!agent) throw new LoomError('INVALID_ARGUMENT','agent id required',undefined,2); const rows=rtJson(c.loom,`select * from inbox_items where recipient_agent_id=${q(agent)} and state='open' order by created_at limit 1;`); return outData({item:rows[0]?inflateInbox(rows[0]):null}); } if(sub==='show'){ return outData({item:inboxGet(c,args[1])}); } if(sub==='accept'||sub==='done'||sub==='cancel'){ const id=args[1]; const st=sub==='cancel'?'cancelled':sub==='accept'?'accepted':'done'; rt(c.loom,`update inbox_items set state=${q(st)}, updated_at=${q(now())} where id=${q(id)};`); appendEvent(c,{type:'inbox.updated',item_id:id,state:st}); return outData({item:inboxGet(c,id)}); } throw new LoomError('INVALID_ARGUMENT','inbox send|next|show|accept|done',undefined,2); }
function inboxGet(c:Ctx,id:string){ const rows=rtJson(c.loom,`select * from inbox_items where id=${q(id)};`); if(!rows[0]) throw new LoomError('INBOX_ITEM_NOT_FOUND',`missing ${id}`,undefined,3); return inflateInbox(rows[0]); }
function inflateInbox(r:any){ return {...r,payload:r.payload_json?JSON.parse(r.payload_json):{}}; }
function cmdNotify(c:Ctx,args:string[]){ const agent=args[0]; const id=flag(args,'--inbox'); if(!id) throw new LoomError('INVALID_ARGUMENT','--inbox required',undefined,2); deliver(c,id,agent); outData({notified:agent,inbox:id}); }
function renderMsg(c:Ctx,item:any){ const n=item.node_id?safeRead(c,item.node_id):undefined; const p=item.payload||{}; return `New Loom item ${item.id}\n\nLoom: ${c.config.name||c.config.id} / ${c.config.id}\n${n?`Node: ${n.fm.id} ${n.fm.title}\n`:''}Type: ${item.type}\n\n${p.message||p.summary||''}\n\nInspect:\n  loom -L ${c.config.id} inbox show ${item.id}\n${item.node_id?`  loom -L ${c.config.id} context ${item.node_id}\n`:''}`; }
function safeRead(c:Ctx,id:string){try{return readNode(c,id)}catch{return undefined}}
function deliver(c:Ctx,id:string,agent?:string){ const item=inboxGet(c,id); const target=agent||item.recipient_agent_id; const msg=renderMsg(c,item); const res=spawnSync('tango',['message',target,msg],{encoding:'utf8'}); const ok=res.status===0; rt(c.loom,`update inbox_items set delivery_state=${q(ok?'delivered':'failed')}, delivery_attempts=delivery_attempts+1, delivery_error=${q(ok?'':(res.stderr||res.stdout||'tango message failed'))}, updated_at=${q(now())} where id=${q(id)};`); }
function routeUpdate(c:Ctx,nodeId:string,summary:string){ const subs=rtJson(c.loom,`select * from subscriptions;`); for(const s of subs){ const id=nextMsgId(c); rt(c.loom,`insert into inbox_items values(${q(id)},${q(s.agent_id)},${q(nodeId)},'subscription_event','normal','open',${q(json({summary,relation:'subscription'}))},'none',0,null,${q(now())},${q(now())});`); deliver(c,id); } }
function cmdSpawn(c:Ctx,args:string[]){ const agent=args[0]; const role=flag(args,'--role','agent'); const ctxPath=writeAgentCtx(c,agent); const prompt=`You are Loom-aware. Run 'loom agent guide' if needed. Default Loom: ${c.config.id}. Context: ${ctxPath}`; const res=spawnSync('tango',['start',agent,'--role',role!,prompt],{stdio:'inherit',env:{...process.env,LOOM_AGENT_ID:agent,LOOM_DEFAULT:c.config.id,LOOM_CONTEXT:ctxPath}}); outData({agent_id:agent, status:res.status}); }
function cmdDispatch(c:Ctx,args:string[]){ const node=parseNodeRef(args[0]); const role=flag(args,'--role','worker'); const agent=`loom-${node.toLowerCase()}-${Date.now()}`; const ctxPath=writeAgentCtx(c,agent); const prompt=`Use Loom. Work on ${node}. First run: loom -L ${c.config.id} context ${node}`; const res=spawnSync('tango',['start',agent,'--role',role!,'--mode','oneshot',prompt],{stdio:'inherit',env:{...process.env,LOOM_AGENT_ID:agent,LOOM_DEFAULT:c.config.id,LOOM_CONTEXT:ctxPath}}); outData({agent_id:agent,node,status:res.status}); }
function writeAgentCtx(c:Ctx,agent:string){ const p=join(c.loom,'runtime','context',`${agent}.json`); writeAtomic(p,json({agentId:agent,default:c.config.id,looms:[{id:c.config.id,alias:c.config.name,rootPath:c.root,loomPath:c.loom}]})); return p; }

function ensureRegistry(){ mkdirSync(home(),{recursive:true}); sqlite(join(home(),'registry.sqlite'),`pragma user_version=1; create table if not exists registry_looms(id text primary key, alias text unique, title text, root_path text not null, loom_path text not null, last_seen_at text); create table if not exists registry_agent_defaults(agent_id text primary key, loom_id text not null);`); }
function cmdRegistry(args:string[]){ ensureRegistry(); if(args[0]==='list') return outData({looms:regJson('select * from registry_looms order by alias;')}); if(args[0]==='resolve') return outData({loom:regJson(`select * from registry_looms where id=${q(args[1])} or alias=${q(args[1])};`)[0]||null}); throw new LoomError('INVALID_ARGUMENT','registry list|resolve',undefined,2); }
function sqlite(db:string, sql:string){ mkdirSync(dirname(db),{recursive:true}); execFileSync('sqlite3',[db,sql],{stdio:['ignore','pipe','pipe']}); }
function dbJson(db:string, sql:string){ const s=execFileSync('sqlite3',['-json',db,sql],{encoding:'utf8'}); return s.trim()?JSON.parse(s):[]; }
function regExec(sql:string){ sqlite(join(home(),'registry.sqlite'),sql); }
function regJson(sql:string){ return dbJson(join(home(),'registry.sqlite'),sql); }
function rt(loom:string,sql:string){ ensureRuntime(loom); sqlite(join(loom,'runtime','runtime.sqlite'),sql); }
function rtJson(loom:string,sql:string){ ensureRuntime(loom); return dbJson(join(loom,'runtime','runtime.sqlite'),sql); }

main();
