import test from "node:test";
import assert from "node:assert/strict";
import {chmodSync,lstatSync,mkdirSync,mkdtempSync,readFileSync,rmSync,statSync,writeFileSync} from "node:fs";
import {tmpdir} from "node:os";
import {dirname,join,resolve} from "node:path";
import {fileURLToPath} from "node:url";
import {execFileSync} from "node:child_process";
import {fauxAssistantMessage,fauxToolCall,registerFauxProvider,type Context} from "@earendil-works/pi-ai";
import {AuthStorage,DefaultResourceLoader,SettingsManager,SessionManager,createAgentSession} from "@earendil-works/pi-coding-agent";

const extension=resolve(dirname(fileURLToPath(import.meta.url)),"../src/index.js");
const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(fn:()=>boolean,ms=8_000){const end=Date.now()+ms;while(!fn()&&Date.now()<end)await wait(20);assert.ok(fn(),`condition timed out after ${ms}ms`);}
async function bounded<T>(promise:Promise<T>,ms=8_000):Promise<T>{let timer:NodeJS.Timeout|undefined;try{return await Promise.race([promise,new Promise<T>((_,reject)=>{timer=setTimeout(()=>reject(new Error(`host proof timed out after ${ms}ms`)),ms);})]);}finally{if(timer)clearTimeout(timer);}}
function contextText(context:Context){return JSON.stringify(context);}

async function makeSession(root:string,model:ReturnType<ReturnType<typeof registerFauxProvider>["getModel"]>,sessionRoot=root){const agentDir=join(root,"agent"),settings=SettingsManager.create(root,agentDir),loader=new DefaultResourceLoader({cwd:root,agentDir,settingsManager:settings,additionalExtensionPaths:[extension],noSkills:true,noPromptTemplates:true,noThemes:true,noContextFiles:true});await loader.reload();assert.equal(loader.getExtensions().errors.length,0);assert.equal(loader.getExtensions().extensions.length,1);const authStorage=AuthStorage.inMemory({[model!.provider]:{type:"api_key",key:"faux-test"}});const result=await createAgentSession({cwd:root,agentDir,model:model!,authStorage,resourceLoader:loader,settingsManager:settings,sessionManager:SessionManager.inMemory(sessionRoot),tools:["bash","monitor","task_list","task_stop"]});await result.session.bindExtensions({});return result.session;}

test("real Pi AgentSession and DefaultResourceLoader load exactly four task-plane tools",async()=>{const root=mkdtempSync(join(tmpdir(),"task-plane-host-")),old=process.env.PI_TASK_PLANE_HOME,oldHome=process.env.HOME;process.env.PI_TASK_PLANE_HOME=join(root,"state");process.env.HOME=root;const faux=registerFauxProvider();let session:Awaited<ReturnType<typeof makeSession>>|undefined;try{session=await makeSession(root,faux.getModel());assert.deepEqual(session.getActiveToolNames(),["bash","monitor","task_list","task_stop"]);}finally{session?.dispose();faux.unregister();if(old===undefined)delete process.env.PI_TASK_PLANE_HOME;else process.env.PI_TASK_PLANE_HOME=old;if(oldHome===undefined)delete process.env.HOME;else process.env.HOME=oldHome;rmSync(root,{recursive:true,force:true});}});

test("legacy retirement uses the real loader without reading blocking records",async()=>{if(process.platform==="win32")return;const root=mkdtempSync(join(tmpdir(),"task-plane-host-retirement-")),state=join(root,"state"),old=process.env.PI_TASK_PLANE_HOME,oldHome=process.env.HOME,warnings:string[]=[],warn=console.warn,faux=registerFauxProvider();let first:Awaited<ReturnType<typeof makeSession>>|undefined,second:Awaited<ReturnType<typeof makeSession>>|undefined;process.env.PI_TASK_PLANE_HOME=state;process.env.HOME=root;console.warn=(...args:unknown[])=>warnings.push(args.map(String).join(" "));const legacy=[join(root,".pi","monitor"),join(root,".pi","background-bash")];try{for(const dir of legacy){mkdirSync(dir,{recursive:true});const unreadable=join(dir,"unreadable-record");writeFileSync(unreadable,"legacy-bytes");chmodSync(unreadable,0);execFileSync("mkfifo",[join(dir,"blocking-record")],{timeout:2_000});}const snapshot=()=>legacy.map(dir=>[lstatSync(dir).mode,lstatSync(join(dir,"unreadable-record")).mode,lstatSync(join(dir,"unreadable-record")).size,lstatSync(join(dir,"blocking-record")).mode,lstatSync(join(dir,"blocking-record")).mtimeMs]);const before=snapshot();first=await bounded(makeSession(root,faux.getModel()),4_000);first.dispose();first=undefined;const retired=warnings.filter(line=>line.includes("retired state root"));assert.equal(retired.length,2);assert.ok(legacy.every(dir=>retired.some(line=>line.includes(dir))));for(const name of ["monitor","background-bash"]){const marker=join(state,`.retired-${name}-noticed`);assert.equal(statSync(marker).mode&0o777,0o600);}const markerTimes=["monitor","background-bash"].map(name=>statSync(join(state,`.retired-${name}-noticed`)).mtimeMs);warnings.length=0;second=await bounded(makeSession(root,faux.getModel(),join(root,"second-session")),4_000);second.dispose();second=undefined;assert.deepEqual(warnings,[]);assert.deepEqual(["monitor","background-bash"].map(name=>statSync(join(state,`.retired-${name}-noticed`)).mtimeMs),markerTimes);assert.deepEqual(snapshot(),before);}finally{second?.dispose();first?.dispose();console.warn=warn;for(const dir of legacy)try{chmodSync(join(dir,"unreadable-record"),0o600);}catch{}faux.unregister();if(old===undefined)delete process.env.PI_TASK_PLANE_HOME;else process.env.PI_TASK_PLANE_HOME=old;if(oldHome===undefined)delete process.env.HOME;else process.env.HOME=oldHome;rmSync(root,{recursive:true,force:true});}});

test("real AgentSession admits only retired fields for structured teaching",async()=>{const root=mkdtempSync(join(tmpdir(),"task-plane-host-schema-")),old=process.env.PI_TASK_PLANE_HOME,oldHome=process.env.HOME;process.env.PI_TASK_PLANE_HOME=join(root,"state");process.env.HOME=root;const faux=registerFauxProvider({tokensPerSecond:0});let session:Awaited<ReturnType<typeof makeSession>>|undefined;try{session=await makeSession(root,faux.getModel());const schema=session.getToolDefinition("monitor")!.parameters as any,retired=["wake_on_completion","emit","projection","wake","kind","condition","path","file_mode","pattern","encoding","shell","labels","metadata","description"];assert.deepEqual(Object.keys(schema.properties).sort(),["command","command_timeout_s","cwd","idempotency_key","interval_s","lifespan_s","name","throttle_s","until_output_matches"].sort());assert.equal(schema.additionalProperties,false);assert.ok(retired.every(name=>!(name in schema.properties)));assert.deepEqual(Object.keys(schema.patternProperties),[`^(?:${retired.join("|")})$`]);let retiredContext:Context|undefined,typoContext:Context|undefined;faux.setResponses([fauxAssistantMessage(fauxToolCall("monitor",{command:"true",emit:"legacy"}),{stopReason:"toolUse"}),(context)=>{retiredContext=context;return fauxAssistantMessage("Retired field handled.");}]);await bounded(session.prompt("Probe the retired field."));const retiredText=contextText(retiredContext!);assert.match(retiredText,/emit was removed in v3/);assert.match(retiredText,/error_type[^}]*validation/);faux.setResponses([fauxAssistantMessage(fauxToolCall("monitor",{command:"true",emitt:"typo"}),{stopReason:"toolUse"}),(context)=>{typoContext=context;return fauxAssistantMessage("Typo handled.");}]);await bounded(session.prompt("Probe the typo."));const text=contextText(typoContext!);assert.match(text,/emitt/);assert.doesNotMatch(text,/emitt was removed in v3/);assert.match(text,/validation|invalid|additional|unexpected/i);}finally{session?.dispose();faux.unregister();if(old===undefined)delete process.env.PI_TASK_PLANE_HOME;else process.env.PI_TASK_PLANE_HOME=old;if(oldHome===undefined)delete process.env.HOME;else process.env.HOME=oldHome;rmSync(root,{recursive:true,force:true});}});

test("disposing a real session synchronously disables polling, durably suspends, and does not poison a new runtime",async()=>{const root=mkdtempSync(join(tmpdir(),"task-plane-host-dispose-")),state=join(root,"state"),polls=join(root,"polls"),freshPolls=join(root,"fresh-polls"),old=process.env.PI_TASK_PLANE_HOME,oldHome=process.env.HOME;process.env.PI_TASK_PLANE_HOME=state;process.env.HOME=root;const faux=registerFauxProvider({tokensPerSecond:0});let session:Awaited<ReturnType<typeof makeSession>>|undefined,fresh:Awaited<ReturnType<typeof makeSession>>|undefined;const count=(path:string)=>{try{return readFileSync(path,"utf8").length;}catch{return 0;}};try{session=await makeSession(root,faux.getModel());faux.setResponses([fauxAssistantMessage(fauxToolCall("monitor",{command:`printf x >> '${polls}'`,interval_s:5,until_output_matches:"never",lifespan_s:30,throttle_s:0}),{stopReason:"toolUse"}),fauxAssistantMessage("Monitor started.")]);await bounded(session.prompt("Start an interval monitor."));await until(()=>count(polls)===1);const taskId=(await import("node:fs")).readdirSync(join(state,"tasks"))[0],recordPath=join(state,"tasks",taskId,"metadata.json");session.dispose();session=undefined;const afterDispose=count(polls);await wait(5_300);assert.equal(count(polls),afterDispose);const suspended=JSON.parse(readFileSync(recordPath,"utf8"));assert.equal(suspended.status,"running");assert.equal(suspended.attempt_phase,"suspended");assert.equal(suspended.owner_runtime_id,undefined);
 fresh=await makeSession(root,faux.getModel(),join(root,"fresh-session"));faux.setResponses([fauxAssistantMessage(fauxToolCall("monitor",{command:`printf y >> '${freshPolls}'`,interval_s:5,until_output_matches:"never",lifespan_s:30,throttle_s:0}),{stopReason:"toolUse"}),fauxAssistantMessage("Fresh monitor started.")]);await bounded(fresh.prompt("Start a fresh interval monitor."));await until(()=>count(freshPolls)===1);assert.notEqual(fresh.sessionId,suspended.owner_session_id);fresh.dispose();fresh=undefined;
 }finally{fresh?.dispose();session?.dispose();faux.unregister();if(old===undefined)delete process.env.PI_TASK_PLANE_HOME;else process.env.PI_TASK_PLANE_HOME=old;if(oldHome===undefined)delete process.env.HOME;else process.env.HOME=oldHome;rmSync(root,{recursive:true,force:true});}});

test("real AgentSession task_stop races a registered bash close with one terminal follow-up",async()=>{const root=mkdtempSync(join(tmpdir(),"task-plane-host-stop-")),state=join(root,"state"),old=process.env.PI_TASK_PLANE_HOME,oldHome=process.env.HOME;process.env.PI_TASK_PLANE_HOME=state;process.env.HOME=root;const faux=registerFauxProvider({tokensPerSecond:0});let session:Awaited<ReturnType<typeof makeSession>>|undefined;const contexts:Context[]=[];try{session=await makeSession(root,faux.getModel());faux.setResponses([
 fauxAssistantMessage(fauxToolCall("bash",{command:"sleep .4",run_in_background:true,timeout:30}),{stopReason:"toolUse"}),
 fauxAssistantMessage("Started."),
]);await bounded(session.prompt("Start it."));const taskId=(await import("node:fs")).readdirSync(join(state,"tasks"))[0];const recordPath=join(state,"tasks",taskId,"metadata.json");assert.equal(JSON.parse(readFileSync(recordPath,"utf8")).status,"running");faux.setResponses([
 fauxAssistantMessage(fauxToolCall("task_stop",{task_id:taskId,kill_after_s:.02}),{stopReason:"toolUse"}),
 (context)=>{contexts.push(context);return fauxAssistantMessage("Stop complete.");},
 (context)=>{contexts.push(context);return fauxAssistantMessage("Terminal received.");},
]);await bounded(session.prompt("Stop it now."));await wait(100);const record=JSON.parse(readFileSync(recordPath,"utf8"));assert.ok(["completed","stopped"].includes(record.status));const notifications=contexts.reduce((n,context)=>n+(contextText(context).split("<task_notification not_user_input=\\\"true\\\">").length-1),0);assert.equal(notifications,1);
 }finally{session?.dispose();faux.unregister();if(old===undefined)delete process.env.PI_TASK_PLANE_HOME;else process.env.PI_TASK_PLANE_HOME=old;if(oldHome===undefined)delete process.env.HOME;else process.env.HOME=oldHome;rmSync(root,{recursive:true,force:true});}});

test("real faux-provider prompt executes owned background bash and receives its host follow-up",async()=>{const root=mkdtempSync(join(tmpdir(),"task-plane-host-active-")),state=join(root,"state"),old=process.env.PI_TASK_PLANE_HOME,oldHome=process.env.HOME;process.env.PI_TASK_PLANE_HOME=state;process.env.HOME=root;const faux=registerFauxProvider({tokensPerSecond:0});let session:Awaited<ReturnType<typeof makeSession>>|undefined,foreign:Awaited<ReturnType<typeof makeSession>>|undefined;let firstContext:Context|undefined,followUpContext:Context|undefined,foreignContext:Context|undefined;const queueEvents:Array<{steering:readonly string[];followUp:readonly string[]}>=[];try{
 session=await makeSession(root,faux.getModel());assert.deepEqual(session.getActiveToolNames(),["bash","monitor","task_list","task_stop"]);
 faux.setResponses([
  (context)=>{firstContext=context;return fauxAssistantMessage(fauxToolCall("bash",{command:"sleep 0.2; printf bash-ok",run_in_background:true,timeout:30}),{stopReason:"toolUse"});},
  async()=>{await wait(450);return fauxAssistantMessage("Background work is still being observed.");},
  (context)=>{followUpContext=context;return fauxAssistantMessage("Completion received.");},
 ]);
 session.subscribe(event=>{if(event.type==="queue_update")queueEvents.push({steering:event.steering,followUp:event.followUp});});
 await bounded(session.prompt("Run the requested command in managed background mode."));
 const records=JSON.parse(readFileSync(join(state,"active-index.json"),"utf8")) as string[];assert.deepEqual(records,[]);const taskDirs=(await import("node:fs")).readdirSync(join(state,"tasks"));assert.equal(taskDirs.length,1);const record=JSON.parse(readFileSync(join(state,"tasks",taskDirs[0],"metadata.json"),"utf8"));
 assert.equal(record.owner_session_id,session.sessionId);assert.equal(record.owner_session_file,session.sessionFile);assert.equal(record.status,"completed");assert.equal(readFileSync(record.output_path,"utf8"),"bash-ok\n");assert.match(firstContext?.systemPrompt??"",/Silence is not success/);assert.match(contextText(followUpContext!),/<task_notification not_user_input=\\"true\\">/);const notificationCount=contextText(followUpContext!).split("<task_notification not_user_input=\\\"true\\\">").length-1;assert.equal(notificationCount,1);
 // Pi 0.74 queues extension custom follow-ups directly on Agent, so they are
 // observable in the next provider context but not in the string-only
 // AgentSession.getFollowUpMessages()/queue_update projection.
 assert.deepEqual(session.getFollowUpMessages(),[]);assert.equal(queueEvents.some(e=>e.followUp.some(v=>v.includes("task_notification"))),false);

 foreign=await makeSession(root,faux.getModel(),join(root,"foreign-session"));faux.setResponses([
  fauxAssistantMessage(fauxToolCall("task_stop",{task_id:record.task_id}),{stopReason:"toolUse"}),
  (context)=>{foreignContext=context;return fauxAssistantMessage("Route refusal received.");},
 ]);await bounded(foreign.prompt("Stop that task."));assert.notEqual(foreign.sessionId,record.owner_session_id);assert.match(contextText(foreignContext!),/belongs to another session/);
 }finally{foreign?.dispose();session?.dispose();faux.unregister();if(old===undefined)delete process.env.PI_TASK_PLANE_HOME;else process.env.PI_TASK_PLANE_HOME=old;if(oldHome===undefined)delete process.env.HOME;else process.env.HOME=oldHome;rmSync(root,{recursive:true,force:true});}});
