import test from "node:test";
import assert from "node:assert/strict";
import { chmodSync, mkdirSync, mkdtempSync, readFileSync, rmSync, utimesSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname,join,resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawn } from "node:child_process";
import { nodeRegistryFs, RegistryConflictError, RegistryCorruptionError, RegistryRuntimeError, TaskRegistry, type RegistryFsPort } from "../src/registry.js";
import type { AdmissionDraft,TaskRecord } from "../src/types.js";
const here=dirname(fileURLToPath(import.meta.url));
function root(){return mkdtempSync(join(tmpdir(),"task-registry-"));}
function draft(session="session-a",extra:Partial<AdmissionDraft>={}):AdmissionDraft{return{type:"bash",command:"true",cwd:process.cwd(),owner_session_id:session,max_output_bytes:1024,...extra};}
function admit(r:TaskRegistry,s="session-a",extra:Partial<AdmissionDraft>={}){return r.admit(s,draft(s,extra)).record;}
function worker(home:string,session:string,key=""){return new Promise<any>(resolve=>{const fixture=resolvePath("fixtures/registry-worker.mjs");const p=spawn(process.execPath,[fixture,home,session,key],{stdio:["ignore","pipe","pipe"]});let out="",err="";p.stdout.on("data",b=>out+=b);p.stderr.on("data",b=>err+=b);p.on("close",code=>resolve({code,err,...JSON.parse(out)}));});}
function resolvePath(rel:string){return resolve(here,"../../test",rel);}
function faultFs(fail:(op:"mkdir"|"open"|"write"|"rename"|"unlink",path:string,data?:string)=>boolean):RegistryFsPort{const paths=new Map<number,string>(),data=new Map<string,string>();return{...nodeRegistryFs,mkdir(path,options){if(fail("mkdir",path))throw new Error("injected");nodeRegistryFs.mkdir(path,options);},open(path,flags,mode){if(fail("open",path))throw new Error("injected");const fd=nodeRegistryFs.open(path,flags,mode);paths.set(fd,path);return fd;},write(fd,text){const path=paths.get(fd)!;data.set(path,(data.get(path)??"")+text);if(fail("write",path,data.get(path)))throw new Error("injected");nodeRegistryFs.write(fd,text);},close(fd){paths.delete(fd);nodeRegistryFs.close(fd);},rename(from,to){if(fail("rename",to,data.get(from)))throw new Error("injected");nodeRegistryFs.rename(from,to);data.delete(from);},unlink(path){if(fail("unlink",path))throw new Error("injected");nodeRegistryFs.unlink(path);}};}

test("real subprocess admissions serialize the same-session 25th/26th boundary",async()=>{const home=root(),r=new TaskRegistry(home);for(let i=0;i<24;i++)admit(r);const got=await Promise.all([worker(home,"session-a"),worker(home,"session-a")]);assert.equal(got.filter(x=>x.ok).length,1);assert.equal(got.filter(x=>!x.ok&&/cap/.test(x.message)).length,1);assert.equal(r.listSession("session-a").length,25);});
test("real subprocess same-session idempotency converges while sessions remain independent",async()=>{const home=root();const same=await Promise.all(Array.from({length:8},()=>worker(home,"session-a","same-key")));assert.equal(new Set(same.map(x=>x.id)).size,1);assert.equal(same.filter(x=>x.idempotent===false).length,1);const other=await worker(home,"session-b","same-key");assert.equal(other.ok,true);assert.notEqual(other.id,same[0].id);});

test("strict metadata parsing rejects path injection, id mismatch, and invalid leases",()=>{const home=root(),r=new TaskRegistry(home),record=admit(r);for(const mutate of [(x:any)=>x.output_path="/tmp/injected",(x:any)=>x.task_id="task_aaaaaaaaaaaa_aaaaaaaaaaaa",(x:any)=>x.lease_token="partial"]){const raw=JSON.parse(readFileSync(record.metadata_path,"utf8"));mutate(raw);writeFileSync(record.metadata_path,JSON.stringify(raw));assert.throws(()=>r.get(record.task_id),RegistryCorruptionError);writeFileSync(record.metadata_path,JSON.stringify(record));}});
test("malformed metadata fails closed while corrupt active index self-repairs",()=>{const home=root(),r=new TaskRegistry(home),record=admit(r);writeFileSync(record.metadata_path,"{");assert.throws(()=>r.list(),RegistryCorruptionError);writeFileSync(record.metadata_path,JSON.stringify(record));writeFileSync(r.indexPath,"not json");assert.equal(admit(r).status,"running");assert.equal(JSON.parse(readFileSync(r.indexPath,"utf8")).length,2);});
test("metadata commit survives index refresh failure and rebuild repairs cache",()=>{const home=root(),r=new TaskRegistry(home),record=admit(r);rmSync(r.indexPath);mkdirSync(r.indexPath);const next=r.updateOutput(record.task_id,record.owner_session_id,record.record_version,7);assert.equal(r.get(record.task_id)?.record_version,next.record_version);assert.equal(r.get(record.task_id)?.output_bytes,7);rmSync(r.indexPath,{recursive:true});assert.deepEqual(r.rebuildIndex(),[record.task_id]);});

test("stale version cannot resurrect and first terminalizer wins",()=>{const r=new TaskRegistry(root()),record=admit(r);const done=r.finalizeUnleased(record.task_id,record.owner_session_id,record.record_version,"completed");assert.throws(()=>r.markOrphaned(record.task_id,record.owner_session_id,record.record_version,"stale"),RegistryConflictError);assert.throws(()=>r.finalizeUnleased(done.task_id,done.owner_session_id,done.record_version,"failed"),RegistryConflictError);assert.equal(r.get(record.task_id)?.status,"completed");});
test("every operation rejects a foreign session",()=>{const r=new TaskRegistry(root()),record=admit(r);for(const op of [()=>r.updateOutput(record.task_id,"foreign",record.record_version,1),()=>r.claimLease(record.task_id,"foreign",record.record_version,"runtime",1000),()=>r.requestStop(record.task_id,"foreign",record.record_version,"user"),()=>r.finalizeUnleased(record.task_id,"foreign",record.record_version,"failed")])assert.throws(op,RegistryConflictError);});
test("lease claims distinguish acquisition, contention, unclaimable, and fence failures",()=>{const r=new TaskRegistry(root()),record=admit(r),t0=new Date("2026-01-01T00:00:00.000Z");const result=r.claimLease(record.task_id,record.owner_session_id,record.record_version,"runtime-a",1000,t0);assert.equal(result.outcome,"acquired");if(result.outcome!=="acquired")return;const leased=result.record;const contended=r.claimLease(record.task_id,record.owner_session_id,leased.record_version,"runtime-b",1000,t0);assert.equal(contended.outcome,"contended");assert.throws(()=>r.updateAttemptClaimed(record.task_id,record.owner_session_id,leased.record_version,"wrong",{output_bytes:1},t0),RegistryConflictError);assert.throws(()=>r.updateAttemptClaimed(record.task_id,record.owner_session_id,leased.record_version,leased.lease_token!,{output_bytes:1},new Date(t0.getTime()+1000)),RegistryConflictError);const reclaimed=r.claimLease(record.task_id,record.owner_session_id,leased.record_version,"runtime-b",1000,new Date(t0.getTime()+1001));assert.equal(reclaimed.outcome,"unclaimable");assert.equal(reclaimed.record.status,"orphaned");assert.equal(reclaimed.record.pid,undefined);assert.throws(()=>r.claimLease(reclaimed.record.task_id,"foreign",reclaimed.record.record_version,"runtime",1000,t0),RegistryConflictError);});
test("every claimed mutation treats exact lease expiry as a hard fence",()=>{const t0=new Date("2026-01-01T00:00:00.000Z"),times=[999,1000,1001];for(const offset of times)for(const operation of ["renew","release","schedule","suspend","finalize","event","attempt"] as const){let clock=t0.getTime()+offset;const r=new TaskRegistry(root(),{clock:()=>clock}),a=r.admit("s",draft("s",{type:"monitor",mode:"interval",interval_s:5})).record,claim=r.claimLease(a.task_id,"s",a.record_version,"rt",1000,t0);assert.equal(claim.outcome,"acquired");if(claim.outcome!=="acquired")continue;const c=claim.record,now=new Date(t0.getTime()+offset),invoke=()=>{switch(operation){case"renew":return r.renewLease(c.task_id,"s",c.record_version,c.lease_token!,1000,now);case"release":return r.releaseLease(c.task_id,"s",c.record_version,c.lease_token!,now);case"schedule":return r.commitScheduleClaimed(c.task_id,"s",c.record_version,c.lease_token!,new Date(now.getTime()+5000).toISOString(),"hash",now);case"suspend":return r.suspendClaimed(c.task_id,"s",c.record_version,c.lease_token!,now);case"finalize":return r.finalizeClaimed(c.task_id,"s",c.record_version,c.lease_token!,"completed",{},now);case"event":return r.appendEventTimestamp(c.task_id,"s",c.record_version,c.lease_token!,now);case"attempt":return r.updateAttemptClaimed(c.task_id,"s",c.record_version,c.lease_token!,{output_bytes:1},now);}};if(offset<1000)assert.doesNotThrow(invoke,`${operation} at expiry-1`);else{assert.throws(invoke,RegistryConflictError,`${operation} at expiry+${offset-1000}`);assert.deepEqual(r.get(c.task_id),c);}}});
test("claimed persistence crossing expiry cannot commit",()=>{const t0=new Date("2026-01-01T00:00:00.000Z");let clock=t0.getTime()+999;const fs=faultFs((op,path,data)=>{if(op==="write"&&path.includes("metadata.json")&&data?.includes('"status": "completed"'))clock=t0.getTime()+1000;return false;});const r=new TaskRegistry(root(),{clock:()=>clock,fs}),a=admit(r),claim=r.claimLease(a.task_id,a.owner_session_id,a.record_version,"rt",1000,t0);assert.equal(claim.outcome,"acquired");if(claim.outcome!=="acquired")return;assert.throws(()=>r.finalizeClaimed(a.task_id,a.owner_session_id,claim.record.record_version,claim.record.lease_token!,"completed",{},new Date(t0.getTime()+999)),RegistryConflictError);assert.equal(r.get(a.task_id)?.status,"running");assert.equal(r.orphanExpiredAttempts(a.owner_session_id,new Date(clock))[0]?.status,"orphaned");});
test("expired token cannot race a second registry orphan reconciliation",()=>{const home=root(),aRegistry=new TaskRegistry(home),bRegistry=new TaskRegistry(home),t0=new Date("2026-01-01T00:00:00.000Z"),a=admit(aRegistry),claim=aRegistry.claimLease(a.task_id,a.owner_session_id,a.record_version,"runtime-a",1000,t0);assert.equal(claim.outcome,"acquired");if(claim.outcome!=="acquired")return;const orphaned=bRegistry.orphanExpiredAttempts(a.owner_session_id,new Date(t0.getTime()+1000));assert.equal(orphaned[0]?.status,"orphaned");assert.throws(()=>aRegistry.updateAttemptClaimed(a.task_id,a.owner_session_id,claim.record.record_version,claim.record.lease_token!,{output_bytes:1},new Date(t0.getTime()+999)),RegistryConflictError);assert.equal(aRegistry.get(a.task_id)?.status,"orphaned");});

test("event flood window persists, expires inclusively, and version-fences writers",()=>{const home=root(),t0=new Date("2026-01-01T00:00:00.000Z"),r=new TaskRegistry(home,{clock:()=>t0.getTime()+60_299}),a=r.admit("s",draft("s",{type:"monitor",mode:"stream"})).record,claim=r.claimLease(a.task_id,"s",a.record_version,"rt",120_000,t0);assert.equal(claim.outcome,"acquired");if(claim.outcome!=="acquired")return;let current=claim.record;for(let i=0;i<300;i++)current=r.appendEventTimestamp(current.task_id,"s",current.record_version,current.lease_token!,new Date(t0.getTime()+i)).record;assert.equal(new TaskRegistry(home).get(a.task_id)?.event_timestamps?.length,300);assert.throws(()=>r.appendEventTimestamp(current.task_id,"s",current.record_version-1,current.lease_token!,new Date(t0.getTime()+300)),RegistryConflictError);const rolled=r.appendEventTimestamp(current.task_id,"s",current.record_version,current.lease_token!,new Date(t0.getTime()+60_299));assert.equal(rolled.count,2);});

test("orphaned records are absorbing for all execution mutations",()=>{const r=new TaskRegistry(root()),a=admit(r),o=r.markOrphaned(a.task_id,a.owner_session_id,a.record_version,"lost");const ops=[()=>r.setBlocked(o.task_id,o.owner_session_id,o.record_version,false),()=>r.attachProcess(o.task_id,o.owner_session_id,o.record_version,"rt",1),()=>r.updateOutput(o.task_id,o.owner_session_id,o.record_version,1),()=>r.commitSchedule(o.task_id,o.owner_session_id,o.record_version,new Date().toISOString(),"x"),()=>r.requestStop(o.task_id,o.owner_session_id,o.record_version,"user"),()=>r.suspend(o.task_id,o.owner_session_id,o.record_version),()=>r.resume(o.task_id,o.owner_session_id,o.record_version,"rt"),()=>r.finalizeUnleased(o.task_id,o.owner_session_id,o.record_version,"completed")];for(const op of ops)assert.throws(op,RegistryConflictError);assert.equal(r.claimLease(o.task_id,o.owner_session_id,o.record_version,"rt",1000).outcome,"unclaimable");assert.deepEqual(r.get(o.task_id),o);});
test("terminal patches reject JS extra fields and preserve protected state",()=>{const r=new TaskRegistry(root()),a=admit(r);for(const key of ["record_version","task_id","paths","command","ownership","status"]){assert.throws(()=>r.finalizeUnleased(a.task_id,a.owner_session_id,a.record_version,"completed",{[key]:"evil"} as any),/patch field/);assert.deepEqual(r.get(a.task_id),a);}});
test("admission drafts reject lifecycle and unknown JS fields",()=>{const r=new TaskRegistry(root());for(const key of ["status","record_version","task_id","output_path","owner_runtime_id","lease_token","dispatch_state"]){assert.throws(()=>r.admit("s",{...draft("s"),[key]:"evil"} as any),/draft field/);assert.equal(r.list().length,0);}});
test("registry root and canonical paths remain absolute after cwd changes",()=>{const old=process.cwd(),base=root();try{process.chdir(base);const r=new TaskRegistry("relative");process.chdir(tmpdir());const a=admit(r);assert.ok(a.metadata_path.startsWith(base));assert.equal(r.get(a.task_id)?.metadata_path,a.metadata_path);}finally{process.chdir(old);}});
test("attempt patches reject JS extra fields and preserve protected state",()=>{const r=new TaskRegistry(root()),a=admit(r),claim=r.claimLease(a.task_id,a.owner_session_id,a.record_version,"rt",1000);assert.equal(claim.outcome,"acquired");if(claim.outcome!=="acquired")return;const before=claim.record;assert.throws(()=>r.updateAttemptClaimed(a.task_id,a.owner_session_id,before.record_version,before.lease_token!,{output_bytes:4,status:"completed",command:"evil",owner_session_id:"evil"} as any),/patch field/);assert.deepEqual(r.get(a.task_id),before);});
test("exact metadata validation rejects unknown and representative malformed fields",()=>{const home=root(),r=new TaskRegistry(home),a=admit(r);for(const mutate of [(x:any)=>x.extra=true,(x:any)=>x.signal=3,(x:any)=>x.suspension_pending=true,(x:any)=>x.stop_requested_at=new Date().toISOString(),(x:any)=>x.owner_runtime_id="",(x:any)=>x.updated_at="2026-01-01",(x:any)=>x.output_bytes=NaN]){const raw=JSON.parse(readFileSync(a.metadata_path,"utf8"));mutate(raw);writeFileSync(a.metadata_path,JSON.stringify(raw));assert.throws(()=>r.get(a.task_id),RegistryCorruptionError);}});
test("atomic resume-and-claim permits exactly one runtime",()=>{const r=new TaskRegistry(root()),a=r.admit("s",draft("s",{type:"monitor",mode:"stream"})).record;const requested=r.requestSuspension(a.task_id,"s",a.record_version);const suspended=r.suspend(requested.task_id,"s",requested.record_version);const first=r.resumeAndClaim(a.task_id,"s",suspended.record_version,"runtime-a",1000);assert.equal(first.outcome,"acquired");assert.throws(()=>r.resumeAndClaim(a.task_id,"s",suspended.record_version,"runtime-b",1000),RegistryConflictError);if(first.outcome==="acquired")assert.equal(first.record.lease_attempt_id,first.record.attempt_id);});

test("claimDue validates timestamps and fences due work",()=>{const r=new TaskRegistry(root()),session="s",record=r.admit(session,draft(session,{type:"monitor",mode:"interval",interval_s:5})).record;const got=r.claimDue(session,"runtime",1,1000,new Date("2026-01-01T00:00:01.000Z"));assert.equal(got[0].task_id,record.task_id);assert.ok(got[0].lease_token);assert.throws(()=>r.claimDue(session,"runtime",1,0),/TTL/);});
test("one interval claim fault does not block unaffected due work and retries",()=>{let failed=false;const fs=faultFs((op,path,data)=>op==="rename"&&path.endsWith("metadata.json")&&Boolean(data?.includes('"lease_token"'))&&!failed&&(failed=true));const r=new TaskRegistry(root(),{fs}),session="s",a=r.admit(session,draft(session,{type:"monitor",mode:"interval",interval_s:5})).record,b=r.admit(session,draft(session,{type:"monitor",mode:"interval",interval_s:5})).record,now=new Date("2026-01-01T00:00:01.000Z"),first=r.claimDue(session,"runtime",2,1000,now);assert.equal(first.length,1);const unclaimed=[a,b].find(candidate=>candidate.task_id!==first[0].task_id)!;assert.equal(r.get(unclaimed.task_id)?.lease_token,undefined);const second=r.claimDue(session,"runtime",2,1000,now);assert.equal(second.length,1);assert.equal(second[0].task_id,unclaimed.task_id);});

test("an old live lock owner cannot be stolen",async()=>{const home=root(),r=new TaskRegistry(home,{lockTimeoutMs:40,lockRetryMs:2,lockStaleMs:1});const lock=join(home,".registry.lock");mkdirSync(lock);writeFileSync(join(lock,"owner.json"),JSON.stringify({pid:process.pid,hostname:(await import("node:os")).hostname(),token:"live",acquired_at:0}));assert.throws(()=>admit(r),RegistryRuntimeError);assert.equal(JSON.parse(readFileSync(join(lock,"owner.json"),"utf8")).token,"live");});
test("dead same-host and conservatively old malformed locks recover",async()=>{for(const malformed of [false,true]){const home=root(),r=new TaskRegistry(home,{lockTimeoutMs:300,lockRetryMs:2,lockStaleMs:5}),lock=join(home,".registry.lock");mkdirSync(lock);writeFileSync(join(lock,"owner.json"),malformed?"bad":JSON.stringify({pid:2147483647,hostname:(await import("node:os")).hostname(),token:"dead",acquired_at:Date.now()}));if(malformed){const old=new Date(Date.now()-1000);utimesSync(lock,old,old);}assert.equal(admit(r).status,"running");}});

test("low-level metadata rename faults never fabricate lifecycle state",()=>{let reject:(data:string)=>boolean=()=>false;const fs=faultFs((op,path,data)=>op==="rename"&&path.endsWith("metadata.json")&&reject(data??""));const r=new TaskRegistry(root(),{fs});reject=data=>data.includes('"record_version": 1');assert.throws(()=>admit(r),RegistryRuntimeError);assert.equal(r.list(true).length,0);reject=()=>false;const a=admit(r);reject=data=>data.includes('"lease_token"');assert.throws(()=>r.claimLease(a.task_id,a.owner_session_id,a.record_version,"rt",1000),RegistryRuntimeError);assert.equal(r.get(a.task_id)?.lease_token,undefined);reject=data=>data.includes('"status": "completed"');assert.throws(()=>r.finalizeUnleased(a.task_id,a.owner_session_id,a.record_version,"completed"),RegistryRuntimeError);assert.equal(r.get(a.task_id)?.status,"running");});
test("suspension metadata rename fault leaves request recoverable",()=>{let fail=true;const fs=faultFs((op,path,data)=>op==="rename"&&path.endsWith("metadata.json")&&Boolean(data?.includes('"attempt_phase": "suspended"'))&&fail);const r=new TaskRegistry(root(),{fs}),a=r.admit("s",draft("s",{type:"monitor",mode:"stream"})).record,requested=r.requestSuspension(a.task_id,"s",a.record_version);assert.throws(()=>r.suspend(a.task_id,"s",requested.record_version),RegistryRuntimeError);assert.equal(r.get(a.task_id)?.attempt_phase,"suspension_requested");fail=false;assert.equal(r.suspend(a.task_id,"s",requested.record_version).attempt_phase,"suspended");});

test("dispatch backfill selects ordinary terminal once but never suppressed or requested",()=>{const r=new TaskRegistry(root()),make=()=>admit(r),ordinaryActive=make(),ordinary=r.finalizeUnleased(ordinaryActive.task_id,"session-a",ordinaryActive.record_version,"completed"),suppressedActive=make(),suppressed=r.finalizeUnleased(suppressedActive.task_id,"session-a",suppressedActive.record_version,"stopped",{stop_reason:"user",notification_suppressed_reason:"shutdown"}),requestedActive=make(),requested=r.finalizeUnleased(requestedActive.task_id,"session-a",requestedActive.record_version,"failed");assert.equal(r.claimTerminal(requested.task_id,"session-a"),true);assert.deepEqual(r.dispatchBackfillCandidates("session-a").map(x=>x.task_id),[ordinary.task_id]);assert.equal(r.claimTerminal(ordinary.task_id,"session-a"),true);assert.deepEqual(r.dispatchBackfillCandidates("session-a"),[]);assert.equal(suppressed.notification_suppressed_reason,"shutdown");});

test("terminal claim returns false only on collision and propagates other I/O",()=>{const home=root(),r=new TaskRegistry(home),a=admit(r),done=r.finalizeUnleased(a.task_id,a.owner_session_id,a.record_version,"completed");assert.equal(r.claimTerminal(done.task_id,done.owner_session_id),true);assert.equal(r.claimTerminal(done.task_id,done.owner_session_id),false);const b=admit(r),done2=r.finalizeUnleased(b.task_id,b.owner_session_id,b.record_version,"failed");chmodSync(r.taskDir(done2.task_id),0o500);try{assert.throws(()=>r.claimTerminal(done2.task_id,done2.owner_session_id),RegistryRuntimeError);}finally{chmodSync(r.taskDir(done2.task_id),0o700);}});
