import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdtempSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createRenderClock, type RenderClock, type RenderClockScheduler, type RenderClockSubscriber } from "@bravo/render-clock";
import { Dispatcher } from "../src/dispatcher.js";
import { TaskEngine, TaskRouteError } from "../src/engine.js";
import { BASH_OUTPUT_CAP, EVENT_LINE_TRUNCATED_MARKER, MAX_EVENT_LINE_CHARS, MONITOR_OUTPUT_CAP, nodeOutputFs, OutputWriter, type OutputFsPort } from "../src/output.js";
import { processTreeAlive } from "../src/process-tree.js";
import { nodeRegistryFs, TaskRegistry, type RegistryFsPort } from "../src/registry.js";

const wait = (ms:number) => new Promise(resolve=>setTimeout(resolve,ms));
async function until(fn:()=>boolean,ms=3_000){const end=Date.now()+ms;while(!fn()&&Date.now()<end)await wait(20);assert.ok(fn(),"condition timed out");}
const testClock=(tickMs:number)=>createRenderClock({baseIntervalMs:tickMs});
function rig(){const registry=new TaskRegistry(mkdtempSync(join(tmpdir(),"task-runner-")));const sent:any[]=[];const dispatcher=new Dispatcher({sendMessage:(m:any)=>sent.push(m)} as any,registry,{sessionId:"s",currentSessionId:()=>"s",currentSessionFile:()=>undefined});return{registry,sent,dispatcher,engine:new TaskEngine(registry,{tickMs:20,renderClock:testClock(20)})};}
function metadataRenameFault(reject:(data:string)=>boolean):RegistryFsPort{const paths=new Map<number,string>(),data=new Map<string,string>();return{...nodeRegistryFs,open(path,flags,mode){const fd=nodeRegistryFs.open(path,flags,mode);paths.set(fd,path);return fd;},write(fd,text){const path=paths.get(fd)!;data.set(path,(data.get(path)??"")+text);nodeRegistryFs.write(fd,text);},close(fd){paths.delete(fd);nodeRegistryFs.close(fd);},rename(from,to){if(to.endsWith("metadata.json")&&reject(data.get(from)??""))throw new Error("injected shutdown metadata fault");nodeRegistryFs.rename(from,to);}};}
function phasedSharedClock(baseIntervalMs=1_000):{clock:RenderClock;advance(ms:number):void;fire():void;taskSubscriber():RenderClockSubscriber;stop():void}{let now=0,active:(()=>void)|undefined;const observed:RenderClockSubscriber[]=[],scheduler={now:()=>now} as unknown as RenderClockScheduler;Object.assign(scheduler,{["set"+"Interval"](callback:()=>void){active=callback;return{callback};},["clear"+"Interval"](handle:{callback?:()=>void}){if(active===handle.callback)active=undefined;}});const shared=createRenderClock({baseIntervalMs,scheduler}),clock:RenderClock={subscribe(subscriber){observed.push(subscriber);return shared.subscribe(subscriber);},tick:reason=>shared.tick(reason),now:()=>shared.now(),subscriberCount:()=>shared.subscriberCount(),isRunning:()=>shared.isRunning()},unsubscribeKeepAlive=shared.subscribe({id:"already-running-surface",intervalMs:baseIntervalMs,reconcile:()=>{}});return{clock,advance(ms){now+=ms;},fire(){assert.ok(active,"shared clock timer is not running");active();},taskSubscriber(){const subscriber=observed.find(candidate=>candidate.id.startsWith("task-plane-engine:"));assert.ok(subscriber,"task-plane subscriber was not observed");return subscriber;},stop(){unsubscribeKeepAlive();}};}

test("canonical output writer persists from first byte and preserves descriptor line integrity",()=>{const root=mkdtempSync(join(tmpdir(),"output-writer-")),path=join(root,"output.log");const w=new OutputWriter(path,"bash",1024);w.write("stdout",Buffer.from("out"));assert.equal(readFileSync(path,"utf8"),"out");w.write("stderr",Buffer.from("err\n"));w.write("stdout",Buffer.from("-done\npartial"));w.close();assert.equal(readFileSync(path,"utf8"),"out-done\nerr\npartial\n");assert.equal(statSync(path).mode&0o777,0o600);});

test("newline-free chunks cap immediately with bounded decoder memory",()=>{for(const kind of ["bash","monitor"] as const){const root=mkdtempSync(join(tmpdir(),"output-bound-")),path=join(root,"output.log"),w=new OutputWriter(path,kind,1024);for(let i=0;i<100;i++)w.write("stdout",Buffer.alloc(1024,97));assert.ok(w.bufferedBytes<=65*1024+(kind==="monitor"?1024:0));w.close();const text=readFileSync(path,"utf8");assert.match(text,/output cap reached|older output truncated/);}});

test("StringDecoder preserves split UTF-8 across every byte boundary",()=>{const value="A😀€Z\n";for(let split=1;split<Buffer.byteLength(value);split++){const root=mkdtempSync(join(tmpdir(),"utf8-")),path=join(root,"o"),w=new OutputWriter(path,"monitor",1024),raw=Buffer.from(value);const lines=[...w.write("stdout",raw.subarray(0,split)).lines,...w.write("stdout",raw.subarray(split)).lines];w.close();assert.deepEqual(lines,["A😀€Z"]);}});

test("oversized stream and interval lines emit a bounded marked event for newline and final partial",async()=>{for(const mode of ["stream","interval"] as const)for(const finalPartial of [false,true]){const x=rig(),size=MAX_EVENT_LINE_CHARS+4096,command=`node -e 'process.stdout.write("A".repeat(${size})${finalPartial?"":"+\"\\n\""})'`,r=x.engine.startMonitor({command,cwd:process.cwd(),...(mode==="interval"?{interval_s:5,until_output_matches:"A"}:{}),throttle_s:0,owner_session_id:"s"},x.dispatcher);await until(()=>Boolean(x.registry.get(r.task_id)?.ended_at),3_000);await until(()=>x.sent.some(v=>v.content.includes(EVENT_LINE_TRUNCATED_MARKER)),1_000);const message=x.sent.map(v=>v.content).join("\n"),event=`${"A".repeat(MAX_EVENT_LINE_CHARS)}${EVENT_LINE_TRUNCATED_MARKER}`;assert.ok(message.includes(event),`${mode} ${finalPartial?"partial":"newline"} omitted marked event`);assert.equal((message.match(/\[task-plane event line truncated\]/g)??[]).length,1);const raw=readFileSync(r.output_path,"utf8");assert.ok(raw.includes("A".repeat(size)),`${mode} raw output was event-truncated`);}});

test("bash cap retains first payload, appends sentinel, and stops",async()=>{const x=rig();const record=x.registry.admit("s",{type:"bash",command:"x",cwd:process.cwd(),owner_session_id:"s",max_output_bytes:16}).record;const writer=new OutputWriter(record.output_path,"bash",16);writer.write("stdout",Buffer.from("abcdefghijklmnopMORE"));writer.close();const text=readFileSync(record.output_path,"utf8");assert.equal(text.slice(0,16),"abcdefghijklmnop");assert.match(text,/output cap reached/);});

test("monitor cap rolls newest payload and continues",()=>{const x=rig();const r=x.registry.admit("s",{type:"monitor",mode:"stream",command:"x",cwd:process.cwd(),owner_session_id:"s",max_output_bytes:8}).record;const w=new OutputWriter(r.output_path,"monitor",8);w.write("stdout",Buffer.from("old\n"));w.write("stderr",Buffer.from("1234\n"));w.write("stdout",Buffer.from("NEWEST\n"));w.close();const text=readFileSync(r.output_path,"utf8");assert.match(text,/older output truncated/);assert.ok(text.endsWith("NEWEST\n"));assert.ok(Buffer.byteLength(text)<=8+Buffer.byteLength(text.match(/^\n?\[task-plane monitor\].*\n/)?.[0]??""));});

test("control frames and descriptor EOF terminate active partial boundaries",()=>{const root=mkdtempSync(join(tmpdir(),"output-boundary-")),path=join(root,"output.log"),w=new OutputWriter(path,"monitor",1024);w.write("stdout",Buffer.from("partial"));w.frame("poll marker");w.write("stderr",Buffer.from("other"));w.close();const text=readFileSync(path,"utf8");assert.match(text,/partial\n\n\[task-plane monitor\].*poll marker\nother\n$/s);assert.doesNotMatch(text,/partial.*other(?!\n)/);});

test("repeated monitor sentinels are physically bounded by cap plus one sentinel",()=>{const root=mkdtempSync(join(tmpdir(),"output-sentinels-")),path=join(root,"output.log"),cap=64,w=new OutputWriter(path,"monitor",cap);for(let i=0;i<100;i++)w.frame(`poll ${i}`);w.close();const text=readFileSync(path,"utf8"),mark=text.match(/^\n?\[task-plane monitor\].*\n/)?.[0]??"";assert.ok(Buffer.byteLength(text)<=cap+Buffer.byteLength(mark));assert.ok((text.match(/older output truncated/g)??[]).length<=1);});

test("natural stream completion flushes final partial before metadata-only terminal",async()=>{const x=rig();const r=x.engine.startMonitor({command:"printf out; printf err >&2",cwd:process.cwd(),throttle_s:10,owner_session_id:"s"},x.dispatcher);await until(()=>Boolean(x.registry.get(r.task_id)?.ended_at));await wait(20);assert.equal(x.registry.get(r.task_id)?.status,"completed");const message=x.sent.map(v=>v.content).join("\n"),running=message.indexOf("<status>running</status>"),terminal=message.indexOf("<status>completed</status>");assert.ok(running>=0&&terminal>running);assert.match(message,/<lines>out<\/lines>/);assert.equal((message.match(/<lines>/g)??[]).length,1);assert.match(readFileSync(r.output_path,"utf8"),/out\nerr\n|err\nout\n/);});

test("interval stop between polls finalizes without a stale pid",async()=>{const x=rig();const r=x.engine.startMonitor({command:"printf stable",cwd:process.cwd(),interval_s:.1,until_output_matches:"never",throttle_s:0,owner_session_id:"s"},x.dispatcher);await until(()=>Boolean(x.registry.get(r.task_id)?.next_run_at));await x.engine.stop(r.task_id);assert.equal(x.registry.get(r.task_id)?.status,"stopped");assert.equal(x.registry.get(r.task_id)?.pid,undefined);});

test("shared lifespan sweep expires an interval monitor during a running poll",async()=>{const x=rig();const r=x.engine.startMonitor({command:"sleep 10",cwd:process.cwd(),interval_s:5,until_output_matches:"never",lifespan_s:.15,throttle_s:0,owner_session_id:"s"},x.dispatcher);await until(()=>x.registry.get(r.task_id)?.status==="timed_out",3_000);assert.equal(x.registry.get(r.task_id)?.stop_reason,"timeout");assert.equal(x.registry.get(r.task_id)?.pid,undefined);});
test("lifespan owner terminates before a later side effect and notifies once",async()=>{const x=rig(),marker=join(x.registry.root,"too-late"),r=x.engine.startMonitor({command:`sleep .4; touch '${marker}'`,cwd:process.cwd(),lifespan_s:.1,throttle_s:0,owner_session_id:"s"},x.dispatcher);await until(()=>x.registry.get(r.task_id)?.status==="timed_out",1_000);await wait(400);assert.equal((await import("node:fs")).existsSync(marker),false);assert.equal(x.sent.length,1);assert.equal((x.sent[0].content.match(/<status>timed_out<\/status>/g)??[]).length,1);});
test("scheduler sweep orphans a missing runtime only after lease expiry",async()=>{const x=rig(),a=x.registry.admit("s",{type:"monitor",mode:"stream",command:"sleep 10",cwd:process.cwd(),owner_session_id:"s",max_output_bytes:1024}).record,claim=x.registry.claimLease(a.task_id,"s",a.record_version,"missing-runtime",120);assert.equal(claim.outcome,"acquired");x.engine.rehydrate("s",()=>x.dispatcher);await wait(60);assert.equal(x.registry.get(a.task_id)?.status,"running");await until(()=>x.registry.get(a.task_id)?.status==="orphaned",1_000);});
test("lifespan sweep requests timeout without terminalizing a foreign live lease",async()=>{const x=rig(),now=Date.now(),a=x.registry.admit("s",{type:"monitor",mode:"stream",command:"touch should-not-run",cwd:process.cwd(),owner_session_id:"s",max_output_bytes:1024,started_at:new Date(now).toISOString(),deadline_at:new Date(now+80).toISOString()}).record,claim=x.registry.claimLease(a.task_id,"s",a.record_version,"missing-runtime",10_000);assert.equal(claim.outcome,"acquired");x.engine.rehydrate("s",()=>x.dispatcher);await until(()=>Boolean(x.registry.get(a.task_id)?.stop_requested_at),1_000);const current=x.registry.get(a.task_id)!;assert.equal(current.status,"running");assert.equal(current.stop_requested_reason,"timeout");assert.equal(current.owner_runtime_id,"missing-runtime");assert.ok(current.lease_token);assert.equal(x.sent.length,0);});
test("monitor throttle is a minimum and 20 lines is only an envelope cap",async()=>{const x=rig(),r=x.engine.startMonitor({command:"i=0; while [ $i -lt 40 ]; do echo line-$i; i=$((i+1)); done; sleep .5",cwd:process.cwd(),throttle_s:.1,owner_session_id:"s"},x.dispatcher);await wait(50);assert.equal(x.sent.length,0);await until(()=>x.sent.length>=1,500);assert.equal((x.sent[0].content.match(/line-/g)??[]).length,20);await until(()=>x.sent.length>=2,500);assert.equal((x.sent[1].content.match(/line-/g)??[]).length,20);await until(()=>Boolean(x.registry.get(r.task_id)?.ended_at),1_000);});
test("command timeout is recorded in output, metadata, and notification",async()=>{const x=rig(),r=x.engine.startMonitor({command:"printf begun; sleep 1",cwd:process.cwd(),interval_s:5,until_output_matches:"never",command_timeout_s:.05,throttle_s:0,owner_session_id:"s"},x.dispatcher);await until(()=>Boolean(x.registry.get(r.task_id)?.ended_at),1_000);await wait(20);assert.equal(x.registry.get(r.task_id)?.failure_reason,"command_timeout");assert.match(readFileSync(r.output_path,"utf8"),/begun[\s\S]*command_timeout/);assert.match(x.sent.map(v=>v.content).join("\n"),/<failure_reason>command_timeout<\/failure_reason>/);});
test("latched interval command timeout beats lifespan during detached stdio drain",async()=>{if(process.platform==="win32")return;const x=rig(),ready=join(x.registry.root,"timeout-lifespan-ready"),command=`touch '${ready}'; setsid sh -c 'sleep .45' & sleep 10`,r=x.engine.startMonitor({command,cwd:process.cwd(),interval_s:5,until_output_matches:"never",command_timeout_s:.05,lifespan_s:.12,throttle_s:0,owner_session_id:"s"},x.dispatcher);await until(()=>existsSync(ready)&&Boolean(x.registry.get(r.task_id)?.pgid));const pgid=x.registry.get(r.task_id)!.pgid!;await until(()=>!processTreeAlive(pgid),500);assert.equal(x.registry.get(r.task_id)?.status,"running");await until(()=>x.registry.get(r.task_id)?.status==="failed",1_500);const current=x.registry.get(r.task_id)!;assert.equal(current.failure_reason,"command_timeout");assert.equal(current.stop_reason,undefined);});
test("post-close output fault cannot erase latched command-timeout classification",async()=>{if(process.platform==="win32")return;let faulted=false;const faulty:OutputFsPort={...nodeOutputFs,write(fd,data){if(!faulted&&data.includes(Buffer.from("command_timeout"))){faulted=true;throw new Error("injected post-timeout output fault");}nodeOutputFs.write(fd,data);}},registry=new TaskRegistry(mkdtempSync(join(tmpdir(),"timeout-output-fault-"))),sent:any[]=[],dispatcher=new Dispatcher({sendMessage:(m:any)=>sent.push(m)} as any,registry,{sessionId:"s",currentSessionId:()=>"s",currentSessionFile:()=>undefined}),engine=new TaskEngine(registry,{tickMs:20,renderClock:testClock(20),outputFs:faulty}),r=engine.startMonitor({command:"sleep 10",cwd:process.cwd(),interval_s:5,until_output_matches:"never",command_timeout_s:.05,throttle_s:0,owner_session_id:"s"},dispatcher);await until(()=>registry.get(r.task_id)?.status==="failed",1_500);await wait(30);const current=registry.get(r.task_id)!;assert.equal(faulted,true);assert.equal(current.failure_reason,"command_timeout");assert.equal(current.stop_reason,undefined);assert.equal(sent.length,1);assert.match(sent[0].content,/<failure_reason>command_timeout<\/failure_reason>/);});
test("changed interval output flushes before natural predicate completion",async()=>{const x=rig(),r=x.engine.startMonitor({command:"printf READY",cwd:process.cwd(),interval_s:.1,until_output_matches:"READY",throttle_s:10,owner_session_id:"s"},x.dispatcher);await until(()=>Boolean(x.registry.get(r.task_id)?.ended_at),1_000);await wait(20);const message=x.sent.map(v=>v.content).join("\n");assert.ok(message.indexOf("<status>running</status>")<message.indexOf("<status>completed</status>"));assert.match(message,/<lines>READY<\/lines>/);});
test("scheduler restarts after becoming idle",async()=>{const x=rig();for(const value of ["FIRST","SECOND"]){const r=x.engine.startMonitor({command:`printf ${value}`,cwd:process.cwd(),interval_s:.1,until_output_matches:value,throttle_s:0,owner_session_id:"s"},x.dispatcher);await until(()=>x.registry.get(r.task_id)?.status==="completed",1_000);await wait(50);}assert.equal(x.registry.list(true).filter(r=>r.status==="completed").length,2);});
test("phase-shifted shared clock accepts the first base tick and fences its callback after shutdown",async()=>{const shared=phasedSharedClock(),registry=new TaskRegistry(mkdtempSync(join(tmpdir(),"task-clock-phase-"))),dispatcher=new Dispatcher({sendMessage:()=>{}} as any,registry,{sessionId:"s",currentSessionId:()=>"s",currentSessionFile:()=>undefined});shared.advance(700);const owner=new TaskEngine(registry,{runtimeId:"clock-owner",tickMs:1_000,renderClock:shared.clock}),foreign=new TaskEngine(registry,{runtimeId:"clock-foreign",tickMs:1_000,renderClock:shared.clock}),record=owner.startBash({command:"sleep 10",cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},dispatcher);await until(()=>Boolean(registry.get(record.task_id)?.pid));const staleSubscriber=shared.taskSubscriber(),stopping=foreign.stop(record.task_id,"SIGTERM",.02);shared.advance(300);shared.fire();const stopped=await stopping;assert.equal(stopped?.status,"stopped");assert.equal(stopped?.stop_acknowledged_by_runtime_id,"clock-owner");assert.equal(shared.clock.subscriberCount(),1,"task-plane subscriber stops while the keep-alive remains");await owner.shutdown("s");const dormant=registry.admit("s",{type:"monitor",mode:"interval",command:"printf stale",cwd:process.cwd(),owner_session_id:"s",max_output_bytes:1024,interval_s:5}).record;shared.advance(1_000);await staleSubscriber.reconcile({now:shared.clock.now(),seq:99,reason:"timer"});await wait(20);assert.equal(registry.get(dormant.task_id)?.lease_token,undefined,"a pre-shutdown subscriber cannot claim after shutdown");assert.equal(registry.get(dormant.task_id)?.next_run_at,undefined);shared.stop();assert.equal(shared.clock.subscriberCount(),0);});
test("output append failure kills the real child and finalizes failed",async()=>{let writes=0;const faulty:OutputFsPort={...nodeOutputFs,write(fd,data){if(++writes>0)throw new Error("injected append fault");nodeOutputFs.write(fd,data);}};const registry=new TaskRegistry(mkdtempSync(join(tmpdir(),"output-fault-")));const sent:any[]=[];const dispatcher=new Dispatcher({sendMessage:(m:any)=>sent.push(m)} as any,registry,{sessionId:"s",currentSessionId:()=>"s",currentSessionFile:()=>undefined});const engine=new TaskEngine(registry,{outputFs:faulty});const r=engine.startBash({command:"printf 'broken\\n'; sleep 10",cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},dispatcher);await until(()=>Boolean(registry.get(r.task_id)?.ended_at));assert.equal(registry.get(r.task_id)?.status,"failed");assert.equal(registry.get(r.task_id)?.pid,undefined);});

test("kill mid-output preserves prefix, prevents late side effect, and dispatches once",async()=>{if(process.platform==="win32")return;const x=rig(),marker=join(x.registry.root,"kill-mid-output-late"),r=x.engine.startBash({command:`printf 'kill-prefix\\n'; sleep .5; touch '${marker}'; sleep 30`,cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},x.dispatcher);await until(()=>readFileSync(r.output_path,"utf8").includes("kill-prefix")&&Boolean(x.registry.get(r.task_id)?.pgid));const pgid=x.registry.get(r.task_id)!.pgid!;process.kill(-pgid,"SIGKILL");await until(()=>x.registry.get(r.task_id)?.status==="failed");await wait(600);await until(()=>x.registry.get(r.task_id)?.dispatch_state==="host_api_invoked");const current=x.registry.get(r.task_id)!;assert.match(readFileSync(r.output_path,"utf8"),/kill-prefix/);assert.equal(existsSync(marker),false);assert.equal(processTreeAlive(pgid),false);assert.equal(current.signal,"SIGKILL");assert.equal(current.pid,undefined);assert.equal(current.pgid,undefined);assert.equal(current.owner_runtime_id,undefined);assert.equal(current.lease_token,undefined);assert.equal((x.sent.map(v=>v.content).join("\n").match(/<status>failed<\/status>/g)??[]).length,1);});

test("SIGTERM-resistant process is escalated and close-confirmed",async()=>{const x=rig();const r=x.engine.startBash({command:"trap '' TERM; sleep 10",cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},x.dispatcher);await until(()=>Boolean(x.registry.get(r.task_id)?.pid));await x.engine.stop(r.task_id,"SIGTERM",.05);assert.equal(x.registry.get(r.task_id)?.status,"stopped");assert.equal(x.registry.get(r.task_id)?.pid,undefined);});

test("stop waits for a SIGTERM-resistant same-group descendant after the shell leader closes",async()=>{if(process.platform==="win32")return;const x=rig(),ready=join(x.registry.root,"descendant-ready"),marker=join(x.registry.root,"late-marker"),script=`const fs=require("fs");fs.writeFileSync(${JSON.stringify(ready)},"");process.on("SIGTERM",()=>{});setTimeout(()=>fs.writeFileSync(${JSON.stringify(marker)},"late"),700);setInterval(()=>{},1000)`,command=`node -e '${script}' >/dev/null 2>&1 & wait`,r=x.engine.startBash({command,cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},x.dispatcher);await until(()=>existsSync(ready)&&Boolean(x.registry.get(r.task_id)?.pid));const stopped=await x.engine.stop(r.task_id,"SIGTERM",.05);assert.equal(stopped?.status,"stopped");assert.equal(stopped?.pid,undefined);await wait(800);assert.equal(existsSync(marker),false);});

test("stream flood boundary permits 299 and 300 raw lines",async()=>{for(const count of [299,300]){const x=rig(),r=x.engine.startMonitor({command:`i=0; while [ $i -lt ${count} ]; do echo event; i=$((i+1)); done`,cwd:process.cwd(),throttle_s:10,owner_session_id:"s"},x.dispatcher);await until(()=>Boolean(x.registry.get(r.task_id)?.ended_at),3_000);assert.equal(x.registry.get(r.task_id)?.status,"completed");assert.equal(x.registry.get(r.task_id)?.event_timestamps?.length,count);}});
test("stdout flood above 300 lines stops a stream monitor",async()=>{const x=rig();const r=x.engine.startMonitor({command:"i=0; while [ $i -lt 301 ]; do echo event; i=$((i+1)); done; sleep 10",cwd:process.cwd(),throttle_s:10,owner_session_id:"s"},x.dispatcher);await until(()=>x.registry.get(r.task_id)?.status==="stopped",3_000);assert.equal(x.registry.get(r.task_id)?.stop_reason,"event_flood");});
test("sustained flood counts 301 gradual raw events across throttle flushes",async()=>{const x=rig(),r=x.engine.startMonitor({command:"i=0; while [ $i -lt 301 ]; do echo event-$i; i=$((i+1)); sleep .003; done; sleep 30",cwd:process.cwd(),throttle_s:.05,owner_session_id:"s"},x.dispatcher);await until(()=>Boolean(x.registry.get(r.task_id)?.pgid));const pgid=x.registry.get(r.task_id)!.pgid!;await until(()=>x.registry.get(r.task_id)?.status==="stopped",8_000);await until(()=>x.sent.filter(v=>/<status>running<\/status>/.test(v.content)).length>=2);const current=x.registry.get(r.task_id)!;assert.equal(current.event_timestamps?.length,301);assert.equal(current.stop_reason,"event_flood");assert.equal(current.pid,undefined);assert.equal(current.pgid,undefined);assert.equal(processTreeAlive(pgid),false);});
test("stream flood counts empty lines and a final partial",async()=>{const x=rig();const r=x.engine.startMonitor({command:"i=0; while [ $i -lt 300 ]; do printf '\\n'; i=$((i+1)); done; printf partial",cwd:process.cwd(),throttle_s:10,owner_session_id:"s"},x.dispatcher);await until(()=>x.registry.get(r.task_id)?.status==="stopped",3_000);assert.equal(x.registry.get(r.task_id)?.stop_reason,"event_flood");assert.equal(x.registry.get(r.task_id)?.event_timestamps?.length,301);});
test("interval flood boundary permits 299/300 and stops 301 before completion",async()=>{for(const count of [299,300,301]){const x=rig(),r=x.engine.startMonitor({command:`i=0; while [ $i -lt ${count} ]; do echo event; i=$((i+1)); done`,cwd:process.cwd(),interval_s:5,until_output_matches:"event",throttle_s:10,owner_session_id:"s"},x.dispatcher);await until(()=>Boolean(x.registry.get(r.task_id)?.ended_at),3_000);assert.equal(x.registry.get(r.task_id)?.status,count===301?"stopped":"completed");assert.equal(x.registry.get(r.task_id)?.stop_reason,count===301?"event_flood":undefined);}});
test("interval flood precedes a nonzero poll outcome and counts blank lines",async()=>{const x=rig();const r=x.engine.startMonitor({command:"i=0; while [ $i -lt 301 ]; do printf '\\n'; i=$((i+1)); done; exit 7",cwd:process.cwd(),interval_s:5,until_output_matches:"never",throttle_s:10,owner_session_id:"s"},x.dispatcher);await until(()=>Boolean(x.registry.get(r.task_id)?.ended_at),3_000);assert.equal(x.registry.get(r.task_id)?.status,"stopped");assert.equal(x.registry.get(r.task_id)?.stop_reason,"event_flood");});

test("interactive prompt becomes blocked during grace then stops",async()=>{const x=rig();const r=x.engine.startBash({command:"printf 'Password: ' >&2; sleep 10",cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},x.dispatcher);await until(()=>x.registry.get(r.task_id)?.status==="blocked",2_500);assert.match(x.registry.get(r.task_id)?.blocked_reason??"",/interactive prompt/);await until(()=>x.registry.get(r.task_id)?.status==="stopped",4_000);assert.equal(x.registry.get(r.task_id)?.stop_reason,"interactive_prompt");});

test("shutdown durably suppresses bash notification and suspends monitor after close",async()=>{const x=rig();const b=x.engine.startBash({command:"sleep 10",cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},x.dispatcher);const m=x.engine.startMonitor({command:"sleep 10",cwd:process.cwd(),throttle_s:0,owner_session_id:"s"},x.dispatcher);await until(()=>Boolean(x.registry.get(b.task_id)?.pid)&&Boolean(x.registry.get(m.task_id)?.pid));await x.engine.shutdown("s");assert.equal(x.registry.get(b.task_id)?.notification_suppressed_reason,"shutdown");assert.equal(x.registry.get(b.task_id)?.status,"stopped");assert.equal(x.registry.get(m.task_id)?.attempt_phase,"suspended");assert.equal(x.registry.get(m.task_id)?.pid,undefined);assert.deepEqual(x.registry.dispatchBackfillCandidates("s"),[]);assert.equal(x.sent.length,0);});
test("shutdown escalation and drain retain lease across the ten-second boundary",async()=>{if(process.platform==="win32")return;const x=rig(),ready=join(x.registry.root,"shutdown-lease-ready"),detachedPath=join(x.registry.root,"shutdown-lease-detached"),command=`trap '' TERM; touch '${ready}'; setsid sh -c 'echo $$ > "${detachedPath}"; sleep 30' & while :; do sleep 1; done`,r=x.engine.startMonitor({command,cwd:process.cwd(),throttle_s:0,owner_session_id:"s"},x.dispatcher);let detached=0,pgid=0;try{await until(()=>existsSync(ready)&&existsSync(detachedPath)&&Boolean(x.registry.get(r.task_id)?.pgid));detached=Number(readFileSync(detachedPath,"utf8").trim());pgid=x.registry.get(r.task_id)!.pgid!;const started=Date.now();await x.engine.shutdown("s");const elapsed=Date.now()-started,current=x.registry.get(r.task_id)!;assert.ok(elapsed>=10_000,`shutdown elapsed ${elapsed}ms did not cross the lease boundary`);assert.ok(elapsed<13_000,`shutdown elapsed ${elapsed}ms was not bounded`);assert.equal(processTreeAlive(pgid),false);assert.equal(current.status,"running");assert.equal(current.attempt_phase,"suspended");assert.equal(current.pid,undefined);assert.equal(current.pgid,undefined);assert.equal(current.owner_runtime_id,undefined);assert.equal(current.lease_token,undefined);assert.notEqual(current.status,"orphaned");assert.equal(x.sent.length,0);console.log(`shutdown lease boundary elapsed_ms=${elapsed} metadata=${JSON.stringify({status:current.status,attempt_phase:current.attempt_phase,pid:current.pid??null,pgid:current.pgid??null,owner_runtime_id:current.owner_runtime_id??null,lease_token:current.lease_token??null})}`);}finally{if(detached>0)try{process.kill(-detached,"SIGKILL");}catch{}if(pgid>0)try{process.kill(-pgid,"SIGKILL");}catch{}}});
test("shutdown preserves an established bash timeout and suppresses its notification",async()=>{if(process.platform==="win32")return;const x=rig(),seen=join(x.registry.root,"shutdown-timeout-term"),script=`const fs=require("fs");process.on("SIGTERM",()=>fs.writeFileSync(${JSON.stringify(seen)},"TERM"));setInterval(()=>{},1000)`,r=x.engine.startBash({command:`node -e '${script}' & wait`,cwd:process.cwd(),timeout_s:.1,owner_session_id:"s"},x.dispatcher);await until(()=>existsSync(seen),1_000);await x.engine.shutdown("s");const current=x.registry.get(r.task_id)!;assert.equal(current.status,"timed_out");assert.equal(current.stop_reason,"timeout");assert.equal(current.notification_suppressed_reason,"shutdown");assert.equal(current.pid,undefined);assert.equal(x.sent.length,0);});
test("shutdown finalizes latched interval command timeout instead of suspending",async()=>{if(process.platform==="win32")return;const x=rig(),ready=join(x.registry.root,"shutdown-command-timeout-ready"),r=x.engine.startMonitor({command:`touch '${ready}'; setsid sh -c 'sleep .45' & sleep 10`,cwd:process.cwd(),interval_s:5,until_output_matches:"never",command_timeout_s:.05,throttle_s:0,owner_session_id:"s"},x.dispatcher);await until(()=>existsSync(ready)&&Boolean(x.registry.get(r.task_id)?.pgid));const pgid=x.registry.get(r.task_id)!.pgid!;await until(()=>!processTreeAlive(pgid),500);assert.equal(x.registry.get(r.task_id)?.status,"running");await x.engine.shutdown("s");const current=x.registry.get(r.task_id)!;assert.equal(current.status,"failed");assert.equal(current.failure_reason,"command_timeout");assert.equal(current.notification_suppressed_reason,"shutdown");assert.notEqual(current.attempt_phase,"suspended");assert.equal(current.pid,undefined);assert.equal(x.sent.length,0);});
test("shutdown kills a live handle from its snapshot even when metadata is malformed",async()=>{if(process.platform==="win32")return;const x=rig(),marker=join(x.registry.root,"corrupt-late-marker"),corrupt=x.engine.startBash({command:`sleep .7; touch '${marker}'`,cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},x.dispatcher);await until(()=>Boolean(x.registry.get(corrupt.task_id)?.pid));const metadata=readFileSync(corrupt.metadata_path,"utf8");writeFileSync(corrupt.metadata_path,"{");await assert.rejects(()=>x.engine.shutdown("s"),/Invalid JSON|metadata|shutdown encountered/i);writeFileSync(corrupt.metadata_path,metadata);await until(()=>["failed","stopped"].includes(x.registry.get(corrupt.task_id)?.status??""),2_000);await wait(750);assert.equal(existsSync(marker),false);});
test("bash shutdown resolves only after a one-shot terminal metadata fault recovers",async()=>{let failed=false;const fs=metadataRenameFault(data=>data.includes('"status": "stopped"')&&!failed&&(failed=true)),registry=new TaskRegistry(mkdtempSync(join(tmpdir(),"shutdown-bash-once-")),{fs}),dispatcher=new Dispatcher({sendMessage:()=>{}} as any,registry,{sessionId:"s",currentSessionId:()=>"s",currentSessionFile:()=>undefined}),engine=new TaskEngine(registry,{tickMs:20,renderClock:testClock(20)}),r=engine.startBash({command:"sleep 10",cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},dispatcher);await until(()=>Boolean(registry.get(r.task_id)?.pid));await engine.shutdown("s");assert.equal(failed,true);assert.equal(registry.get(r.task_id)?.status,"stopped");assert.equal(registry.get(r.task_id)?.pid,undefined);});
test("bash shutdown rejects boundedly on persistent terminal metadata failure",async()=>{let reject=true;const fs=metadataRenameFault(data=>reject&&data.includes('"status": "stopped"')),registry=new TaskRegistry(mkdtempSync(join(tmpdir(),"shutdown-bash-persistent-")),{fs}),dispatcher=new Dispatcher({sendMessage:()=>{}} as any,registry,{sessionId:"s",currentSessionId:()=>"s",currentSessionFile:()=>undefined}),engine=new TaskEngine(registry,{tickMs:20,renderClock:testClock(20)}),r=engine.startBash({command:"sleep 10",cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},dispatcher);await until(()=>Boolean(registry.get(r.task_id)?.pid));const started=Date.now();await assert.rejects(()=>engine.shutdown("s"),/terminal metadata was not durably persisted/);assert.ok(Date.now()-started<3_500);assert.equal(registry.get(r.task_id)?.status,"running");reject=false;await until(()=>registry.get(r.task_id)?.status==="stopped",1_000);});
test("one shutdown persistence failure does not leave a later real child running",async()=>{let reject=true;const fs=metadataRenameFault(data=>reject&&data.includes('"status": "stopped"')&&data.includes("first-persistent")),registry=new TaskRegistry(mkdtempSync(join(tmpdir(),"shutdown-best-effort-")),{fs}),dispatcher=new Dispatcher({sendMessage:()=>{}} as any,registry,{sessionId:"s",currentSessionId:()=>"s",currentSessionFile:()=>undefined}),engine=new TaskEngine(registry,{tickMs:20,renderClock:testClock(20)}),marker=join(registry.root,"late-side-effect"),first=engine.startBash({command:"sleep 10 # first-persistent",cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},dispatcher),second=engine.startBash({command:`sleep .7; touch '${marker}'`,cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},dispatcher);await until(()=>Boolean(registry.get(first.task_id)?.pid)&&Boolean(registry.get(second.task_id)?.pid));await assert.rejects(()=>engine.shutdown("s"),/terminal metadata was not durably persisted/);const later=registry.get(second.task_id)!;assert.equal(later.status,"stopped");assert.equal(later.stop_reason,"user");assert.equal(later.pid,undefined);assert.equal(later.notification_suppressed_reason,"shutdown");assert.equal(existsSync(marker),false);await wait(750);assert.equal(existsSync(marker),false);reject=false;await until(()=>registry.get(first.task_id)?.status==="stopped",1_000);});
test("monitor shutdown resolves only after a one-shot suspended metadata fault recovers",async()=>{let failed=false;const fs=metadataRenameFault(data=>data.includes('"attempt_phase": "suspended"')&&!failed&&(failed=true)),registry=new TaskRegistry(mkdtempSync(join(tmpdir(),"shutdown-monitor-once-")),{fs}),dispatcher=new Dispatcher({sendMessage:()=>{}} as any,registry,{sessionId:"s",currentSessionId:()=>"s",currentSessionFile:()=>undefined}),engine=new TaskEngine(registry,{tickMs:20,renderClock:testClock(20)}),r=engine.startMonitor({command:"sleep 10",cwd:process.cwd(),throttle_s:0,owner_session_id:"s"},dispatcher);await until(()=>Boolean(registry.get(r.task_id)?.pid));await engine.shutdown("s");assert.equal(failed,true);assert.equal(registry.get(r.task_id)?.attempt_phase,"suspended");assert.equal(registry.get(r.task_id)?.pid,undefined);});
test("monitor shutdown rejects boundedly on persistent suspended metadata failure",async()=>{let reject=true;const fs=metadataRenameFault(data=>reject&&data.includes('"attempt_phase": "suspended"')),registry=new TaskRegistry(mkdtempSync(join(tmpdir(),"shutdown-monitor-persistent-")),{fs}),dispatcher=new Dispatcher({sendMessage:()=>{}} as any,registry,{sessionId:"s",currentSessionId:()=>"s",currentSessionFile:()=>undefined}),engine=new TaskEngine(registry,{tickMs:20,renderClock:testClock(20)}),r=engine.startMonitor({command:"sleep 10",cwd:process.cwd(),throttle_s:0,owner_session_id:"s"},dispatcher);await until(()=>Boolean(registry.get(r.task_id)?.pid));const started=Date.now();await assert.rejects(()=>engine.shutdown("s"),/suspended metadata was not durably persisted/);assert.ok(Date.now()-started<3_500);assert.notEqual(registry.get(r.task_id)?.attempt_phase,"suspended");reject=false;await until(()=>registry.get(r.task_id)?.attempt_phase==="suspended",1_000);assert.equal(registry.get(r.task_id)?.pid,undefined);});
test("shutdown cancels a transiently failed initial stream claim and durably suspends without spawning",async()=>{let failed=false;const paths=new Map<number,string>(),data=new Map<string,string>(),fs:RegistryFsPort={...nodeRegistryFs,open(path,flags,mode){const fd=nodeRegistryFs.open(path,flags,mode);paths.set(fd,path);return fd;},write(fd,text){const path=paths.get(fd)!;data.set(path,(data.get(path)??"")+text);nodeRegistryFs.write(fd,text);},close(fd){paths.delete(fd);nodeRegistryFs.close(fd);},rename(from,to){if(!failed&&to.endsWith("metadata.json")&&(data.get(from)??"").includes('"lease_token"')){failed=true;throw new Error("injected initial claim failure");}nodeRegistryFs.rename(from,to);}};const registry=new TaskRegistry(mkdtempSync(join(tmpdir(),"claim-shutdown-")),{fs}),sent:any[]=[],dispatcher=new Dispatcher({sendMessage:(m:any)=>sent.push(m)} as any,registry,{sessionId:"s",currentSessionId:()=>"s",currentSessionFile:()=>undefined}),engine=new TaskEngine(registry,{tickMs:20,renderClock:testClock(20)}),marker=join(registry.root,"spawned"),r=engine.startMonitor({command:`touch '${marker}'; printf event`,cwd:process.cwd(),throttle_s:0,owner_session_id:"s"},dispatcher);assert.equal(failed,true);await engine.shutdown("s");await wait(75);const current=registry.get(r.task_id)!;assert.equal(current.attempt_phase,"suspended");assert.equal(current.suspension_pending,true);assert.equal(current.pid,undefined);assert.equal(current.lease_token,undefined);assert.equal(existsSync(marker),false);assert.equal(sent.length,0);});
test("pending stream-claim suspension failure does not block live bash termination",async()=>{let rejectClaim=true,claimFailed=false;const fs=metadataRenameFault(data=>{if(rejectClaim&&data.includes('"lease_token"')){claimFailed=true;return true;}return rejectClaim&&data.includes('"attempt_phase": "suspended"')&&data.includes("pending-fault");}),registry=new TaskRegistry(mkdtempSync(join(tmpdir(),"shutdown-pending-best-effort-")),{fs}),dispatcher=new Dispatcher({sendMessage:()=>{}} as any,registry,{sessionId:"s",currentSessionId:()=>"s",currentSessionFile:()=>undefined}),engine=new TaskEngine(registry,{tickMs:20,renderClock:testClock(20)}),marker=join(registry.root,"bash-late"),pending=engine.startMonitor({command:"printf never # pending-fault",cwd:process.cwd(),throttle_s:0,owner_session_id:"s"},dispatcher),bash=engine.startBash({command:`sleep .7; touch '${marker}'`,cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},dispatcher);assert.equal(claimFailed,true);await until(()=>Boolean(registry.get(bash.task_id)?.pid));await assert.rejects(()=>engine.shutdown("s"),/durably suspended|suspended metadata/);assert.equal(registry.get(bash.task_id)?.status,"stopped");assert.equal(registry.get(bash.task_id)?.pid,undefined);await wait(750);assert.equal(existsSync(marker),false);assert.notEqual(registry.get(pending.task_id)?.attempt_phase,"suspended");rejectClaim=false;});

test("foreign-runtime stop is consumed by the live owner",async()=>{const x=rig(),foreign=new TaskEngine(x.registry,{runtimeId:"foreign",tickMs:20,renderClock:testClock(20)});const r=x.engine.startBash({command:"sleep 10",cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},x.dispatcher);await until(()=>Boolean(x.registry.get(r.task_id)?.pid));const stopped=await foreign.stop(r.task_id,"SIGTERM",1);assert.equal(stopped?.status,"stopped");assert.ok(stopped?.stop_acknowledged_at);assert.equal(stopped?.stop_acknowledged_by_runtime_id,x.engine.runtimeId);});
test("foreign stop uses control-tick acknowledgement grace, not kill_after",async()=>{const registry=new TaskRegistry(mkdtempSync(join(tmpdir(),"task-stop-grace-"))),sent:any[]=[],dispatcher=new Dispatcher({sendMessage:(m:any)=>sent.push(m)} as any,registry,{sessionId:"s",currentSessionId:()=>"s",currentSessionFile:()=>undefined}),owner=new TaskEngine(registry,{runtimeId:"owner",tickMs:100,renderClock:testClock(100)}),foreign=new TaskEngine(registry,{runtimeId:"foreign",tickMs:100,renderClock:testClock(100)}),r=owner.startBash({command:"sleep 10",cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},dispatcher);await until(()=>Boolean(registry.get(r.task_id)?.pid));const stopped=await foreign.stop(r.task_id,"SIGTERM",.02);assert.equal(stopped?.status,"stopped");assert.equal(stopped?.stop_requested_kill_after_s,.02);assert.equal(stopped?.stop_acknowledged_by_runtime_id,"owner");});

test("unresponsive foreign owner stop surfaces a route failure",async()=>{const x=rig();const a=x.registry.admit("s",{type:"monitor",mode:"interval",command:"true",cwd:process.cwd(),owner_session_id:"s",max_output_bytes:1024,interval_s:5}).record;const claim=x.registry.claimLease(a.task_id,"s",a.record_version,"missing-runtime",10_000);assert.equal(claim.outcome,"acquired");await assert.rejects(()=>x.engine.stop(a.task_id,"SIGTERM",.02),TaskRouteError);assert.equal(x.registry.get(a.task_id)?.status,"running");assert.equal(x.registry.get(a.task_id)?.stop_requested_kill_after_s,.02);assert.ok(x.registry.get(a.task_id)?.stop_request_deadline_at);});

test("running interval shutdown suspends after close and rehydrate atomically resumes",async()=>{const x=rig();const r=x.engine.startMonitor({command:"sleep .2; printf READY",cwd:process.cwd(),interval_s:5,until_output_matches:"READY",throttle_s:0,owner_session_id:"s"},x.dispatcher);await until(()=>Boolean(x.registry.get(r.task_id)?.pid));await x.engine.shutdown("s");assert.equal(x.registry.get(r.task_id)?.attempt_phase,"suspended");assert.equal(x.registry.get(r.task_id)?.status,"running");assert.equal(x.registry.get(r.task_id)?.lease_token,undefined);const resumed=new TaskEngine(x.registry,{runtimeId:"resumed",tickMs:20,renderClock:testClock(20)});resumed.rehydrate("s",()=>x.dispatcher);await until(()=>x.registry.get(r.task_id)?.status==="completed");assert.equal(x.registry.get(r.task_id)?.owner_runtime_id,undefined);});
test("stream rehydration preserves the remaining absolute lifespan",async()=>{const x=rig(),r=x.engine.startMonitor({command:"sleep 10",cwd:process.cwd(),lifespan_s:.35,throttle_s:0,owner_session_id:"s"},x.dispatcher);await until(()=>Boolean(x.registry.get(r.task_id)?.pid));await wait(80);await x.engine.shutdown("s");const deadline=Date.parse(x.registry.get(r.task_id)!.deadline_at!),resumed=new TaskEngine(x.registry,{runtimeId:"stream-resumed",tickMs:20,renderClock:testClock(20)});resumed.rehydrate("s",()=>x.dispatcher);await until(()=>x.registry.get(r.task_id)?.status==="timed_out",1_000);assert.ok(Date.parse(x.registry.get(r.task_id)!.ended_at!)>=deadline);assert.equal(x.registry.get(r.task_id)?.attempt,2);});
test("expired suspended stream and interval monitors rehydrate to one strict timed_out notification",async()=>{for(const mode of ["stream","interval"] as const){const x=rig(),old=new Date(Date.now()-2_000).toISOString(),a=x.registry.admit("s",{type:"monitor",mode,command:"touch should-not-run",cwd:process.cwd(),owner_session_id:"s",max_output_bytes:1024,started_at:old,deadline_at:new Date(Date.now()-1_000).toISOString(),...(mode==="interval"?{interval_s:5}: {})}).record,requested=x.registry.requestSuspension(a.task_id,"s",a.record_version),suspended=x.registry.suspend(a.task_id,"s",requested.record_version),engine=new TaskEngine(x.registry,{runtimeId:`expired-${mode}`,tickMs:20,renderClock:testClock(20)});assert.equal(suspended.attempt_phase,"suspended");engine.rehydrate("s",()=>x.dispatcher);await until(()=>x.registry.get(a.task_id)?.dispatch_state==="host_api_invoked",1_000);const current=x.registry.get(a.task_id)!;assert.equal(current.status,"timed_out");assert.equal(current.stop_reason,"timeout");assert.equal(current.attempt_phase,"outcome_pending");assert.equal(current.suspended_at,undefined);assert.equal(current.suspension_pending,undefined);assert.equal(current.suspension_requested_at,undefined);assert.equal(current.suspension_completed_at,undefined);assert.equal(x.sent.length,1);assert.equal((x.sent[0].content.match(/<status>timed_out<\/status>/g)??[]).length,1);}});
test("stream respawn failure terminalizes the resumed attempt",async()=>{const x=rig(),a=x.registry.admit("s",{type:"monitor",mode:"stream",command:"true",cwd:join(tmpdir(),"missing-task-plane-cwd"),owner_session_id:"s",max_output_bytes:1024}).record,requested=x.registry.requestSuspension(a.task_id,"s",a.record_version),suspended=x.registry.suspend(a.task_id,"s",requested.record_version),resumed=new TaskEngine(x.registry,{runtimeId:"respawn",tickMs:20,renderClock:testClock(20)});assert.equal(suspended.attempt_phase,"suspended");resumed.rehydrate("s",()=>x.dispatcher);await until(()=>x.registry.get(a.task_id)?.status==="failed",1_000);assert.equal(x.registry.get(a.task_id)?.attempt,2);});
test("rehydration atomically recovers suspended and never-claimed stream attempts",async()=>{
  {const x=rig(),a=x.registry.admit("s",{type:"monitor",mode:"stream",command:"sleep .1",cwd:process.cwd(),owner_session_id:"s",max_output_bytes:1024}).record,requested=x.registry.requestSuspension(a.task_id,"s",a.record_version),suspended=x.registry.suspend(a.task_id,"s",requested.record_version),one=new TaskEngine(x.registry,{runtimeId:"one",tickMs:20,renderClock:testClock(20)}),two=new TaskEngine(x.registry,{runtimeId:"two",tickMs:20,renderClock:testClock(20)});assert.equal(suspended.attempt,1);one.rehydrate("s",()=>x.dispatcher);two.rehydrate("s",()=>x.dispatcher);await until(()=>Boolean(x.registry.get(a.task_id)?.ended_at),1_000);assert.equal(x.registry.get(a.task_id)?.attempt,2);assert.equal(x.registry.get(a.task_id)?.status,"completed");}
  {const x=rig(),a=x.registry.admit("s",{type:"monitor",mode:"stream",command:"printf recovered",cwd:process.cwd(),owner_session_id:"s",max_output_bytes:1024}).record,restarted=new TaskEngine(x.registry,{runtimeId:"restarted",tickMs:20,renderClock:testClock(20)});assert.equal(a.attempt_phase,"starting");assert.equal(a.owner_runtime_id,undefined);assert.equal(a.lease_token,undefined);restarted.rehydrate("s",()=>x.dispatcher);await until(()=>x.registry.get(a.task_id)?.status==="completed",1_000);assert.match(readFileSync(a.output_path,"utf8"),/recovered/);assert.equal(x.registry.get(a.task_id)?.attempt,1);}
  {const x=rig(),marker=join(x.registry.root,"spawn-count"),a=x.registry.admit("s",{type:"monitor",mode:"stream",command:`printf x >> '${marker}'; sleep .05`,cwd:process.cwd(),owner_session_id:"s",max_output_bytes:1024}).record,one=new TaskEngine(x.registry,{runtimeId:"preclaim-one",tickMs:20,renderClock:testClock(20)}),two=new TaskEngine(x.registry,{runtimeId:"preclaim-two",tickMs:20,renderClock:testClock(20)});one.rehydrate("s",()=>x.dispatcher);two.rehydrate("s",()=>x.dispatcher);await until(()=>x.registry.get(a.task_id)?.status==="completed",1_000);assert.equal(readFileSync(marker,"utf8"),"x");assert.equal(x.registry.get(a.task_id)?.attempt,1);}
  {const x=rig(),marker=join(x.registry.root,"expired-spawn"),old=new Date(Date.now()-2_000).toISOString(),a=x.registry.admit("s",{type:"monitor",mode:"stream",command:`touch '${marker}'`,cwd:process.cwd(),owner_session_id:"s",max_output_bytes:1024,started_at:old,deadline_at:new Date(Date.now()-1_000).toISOString()}).record,restarted=new TaskEngine(x.registry,{runtimeId:"expired-preclaim",tickMs:20,renderClock:testClock(20)});restarted.rehydrate("s",()=>x.dispatcher);await until(()=>x.registry.get(a.task_id)?.status==="timed_out",1_000);assert.equal(existsSync(marker),false);assert.equal(x.registry.get(a.task_id)?.stop_reason,"timeout");assert.equal(x.registry.get(a.task_id)?.lease_token,undefined);}
});

test("redirected same-group descendant delays natural completion until group death",async()=>{if(process.platform==="win32")return;const x=rig(),marker=join(x.registry.root,"redirected-late-marker"),r=x.engine.startBash({command:`(sleep .4; touch '${marker}') >/dev/null 2>&1 & exit 0`,cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},x.dispatcher);await wait(150);assert.equal(existsSync(marker),false);assert.equal(x.registry.get(r.task_id)?.ended_at,undefined);await until(()=>existsSync(marker),1_000);await until(()=>x.registry.get(r.task_id)?.status==="completed",1_000);});
test("inherited-stdio same-group descendant delays natural completion until group death",async()=>{if(process.platform==="win32")return;const x=rig(),marker=join(x.registry.root,"inherited-late-marker"),r=x.engine.startBash({command:`(sleep .4; touch '${marker}') & exit 0`,cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},x.dispatcher);await wait(150);assert.equal(existsSync(marker),false);assert.equal(x.registry.get(r.task_id)?.ended_at,undefined);await until(()=>existsSync(marker),1_000);await until(()=>x.registry.get(r.task_id)?.status==="completed",1_000);assert.equal(x.registry.get(r.task_id)?.stdio_drain_timed_out,undefined);});
test("leader exit is bounded when a detached grandchild retains stdio",async()=>{if(process.platform==="win32")return;const x=rig();x.engine=new TaskEngine(x.registry,{tickMs:20,renderClock:testClock(20),stdioDrainTimeoutMs:50});const r=x.engine.startBash({command:"setsid sh -c 'sleep 2' & exit 0",cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},x.dispatcher);await until(()=>Boolean(x.registry.get(r.task_id)?.ended_at),1_000);assert.equal(x.registry.get(r.task_id)?.status,"completed");assert.equal(x.registry.get(r.task_id)?.stdio_drain_timed_out,true);});

test("nonzero exits preserve output and dispatch exit 7 once for bash and stream",async()=>{for(const kind of ["bash","stream"] as const){const x=rig(),r=kind==="bash"?x.engine.startBash({command:"printf 'before-exit-7\\n'; exit 7",cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},x.dispatcher):x.engine.startMonitor({command:"printf 'before-exit-7\\n'; exit 7",cwd:process.cwd(),throttle_s:10,owner_session_id:"s"},x.dispatcher);await until(()=>x.registry.get(r.task_id)?.status==="failed");await until(()=>x.registry.get(r.task_id)?.dispatch_state==="host_api_invoked");const current=x.registry.get(r.task_id)!;assert.match(readFileSync(r.output_path,"utf8"),/before-exit-7/);assert.equal(current.exit_code,7);assert.equal(current.pid,undefined);assert.equal(current.pgid,undefined);assert.equal(current.owner_runtime_id,undefined);assert.equal(current.lease_token,undefined);const notifications=x.sent.map(v=>v.content).join("\n");assert.equal((notifications.match(/<status>failed<\/status>/g)??[]).length,1);assert.equal((notifications.match(/<exit_code>7<\/exit_code>/g)??[]).length,1);}});

test("interval stdout budget overflow fails with sentinel",async()=>{const x=rig();const r=x.engine.startMonitor({command:"head -c 5242881 /dev/zero",cwd:process.cwd(),interval_s:5,until_output_matches:"never",throttle_s:0,owner_session_id:"s"},x.dispatcher);await until(()=>Boolean(x.registry.get(r.task_id)?.ended_at),5_000);assert.equal(x.registry.get(r.task_id)?.status,"failed");assert.match(readFileSync(r.output_path,"utf8"),/exceeded 5242880-byte budget/);});
test("real bash engine stops at 10MiB and retains exactly the first cap plus sentinel",async()=>{const x=rig(),command=`node -e 'process.stdout.write(Buffer.alloc(${BASH_OUTPUT_CAP+1024},65)); setTimeout(()=>{},10000)'`,r=x.engine.startBash({command,cwd:process.cwd(),timeout_s:30,owner_session_id:"s"},x.dispatcher);await until(()=>x.registry.get(r.task_id)?.status==="stopped",8_000);const output=readFileSync(r.output_path);assert.equal(x.registry.get(r.task_id)?.stop_reason,"output_cap");assert.equal(output.subarray(0,BASH_OUTPUT_CAP).equals(Buffer.alloc(BASH_OUTPUT_CAP,65)),true);assert.match(output.subarray(BASH_OUTPUT_CAP).toString(),/output cap reached at 10485760 payload bytes; process stopped/);});
test("real stream monitor rolls beyond 5MiB, keeps newest sentinel, and completes naturally",async()=>{const x=rig(),marker="NEWEST-MONITOR-SENTINEL",command=`node -e 'process.stdout.write(Buffer.alloc(${MONITOR_OUTPUT_CAP+1024},65)); process.stdout.write("${marker}\\n")'`,r=x.engine.startMonitor({command,cwd:process.cwd(),throttle_s:0,owner_session_id:"s"},x.dispatcher);await until(()=>x.registry.get(r.task_id)?.status==="completed",8_000);const output=readFileSync(r.output_path);assert.match(output.toString(),/older output truncated/);assert.match(output.toString(),new RegExp(marker));const mark=output.toString().match(/^\n?\[task-plane monitor\].*\n/)?.[0]??"";assert.ok(output.length<=MONITOR_OUTPUT_CAP+Buffer.byteLength(mark));});

test("engine runtime ownership is per instance",()=>{const registry=new TaskRegistry(mkdtempSync(join(tmpdir(),"runtime-owner-")));const a=new TaskEngine(registry),b=new TaskEngine(registry);assert.notEqual(a.runtimeId,b.runtimeId);});
