import { randomBytes } from "node:crypto";
import { closeSync, mkdirSync, openSync, readFileSync, readdirSync, renameSync, rmSync, statSync, symlinkSync, unlinkSync, writeSync, type Dirent, type Stats } from "node:fs";
import { hostname as osHostname } from "node:os";
import { join, resolve } from "node:path";
import type { AdmissionDraft, DispatchState, LeaseClaimResult, StopReason, TaskRecord, TerminalTaskStatus } from "./types.js";

const ACTIVE=new Set<TaskRecord["status"]>(["running","blocked"]);
const STATUSES=new Set(["running","blocked","completed","failed","stopped","timed_out","orphaned"]);
const TERMINAL=new Set(["completed","failed","stopped","timed_out"]);
const STOPS=new Set(["timeout","output_cap","event_flood","user","interactive_prompt"]);
const DISPATCH=new Set(["dispatch_requested","host_api_invoked","dispatch_sync_failed"]);
const MAX_TTL_MS=86_400_000;
type LockOwner={pid:number;hostname:string;token:string;acquired_at:number};
export interface RegistryFsPort {
 mkdir(path:string,options?:{recursive?:boolean;mode?:number}):void;
 open(path:string,flags:string,mode?:number):number;
 write(fd:number,data:string):void;
 close(fd:number):void;
 rename(from:string,to:string):void;
 symlink(target:string,path:string):void;
 unlink(path:string):void;
 read(path:string):string;
 readdir(path:string):Dirent[];
 stat(path:string):Stats;
 rm(path:string,options?:{recursive?:boolean;force?:boolean}):void;
}
export const nodeRegistryFs:RegistryFsPort={mkdir:(path,options)=>mkdirSync(path,options),open:(path,flags,mode)=>openSync(path,flags,mode),write:(fd,data)=>{const b=Buffer.from(data);let at=0;while(at<b.length)at+=writeSync(fd,b,at,b.length-at);},close:closeSync,rename:renameSync,symlink:(target,path)=>symlinkSync(target,path,"dir"),unlink:unlinkSync,read:path=>readFileSync(path,"utf8"),readdir:path=>readdirSync(path,{withFileTypes:true}),stat:statSync,rm:(path,options)=>rmSync(path,options)};
export interface RegistryOptions {lockTimeoutMs?:number;lockStaleMs?:number;lockRetryMs?:number;hostname?:string;clock?:()=>number;fs?:RegistryFsPort}
type TerminalPatch={exit_code?:number;signal?:string;stop_reason?:StopReason;ended_at?:string;stdio_drain_timed_out?:boolean;notification_suppressed_reason?:"shutdown";failure_reason?:"command_timeout"};
type AttemptPatch={output_bytes?:number;pid?:number;pgid?:number;blocked_reason?:string;next_run_at?:string;last_hash?:string};

export class RegistryError extends Error { constructor(message:string,options?:ErrorOptions){super(message,options);this.name="RegistryError";} }
export class RegistryConflictError extends RegistryError { constructor(message:string){super(message);this.name="RegistryConflictError";} }
export class RegistryCorruptionError extends RegistryError { constructor(message:string,options?:ErrorOptions){super(message,options);this.name="RegistryCorruptionError";} }
export class RegistryRuntimeError extends RegistryError { constructor(message:string,options?:ErrorOptions){super(message,options);this.name="RegistryRuntimeError";} }
class AdmissionRetry extends Error {}

/** A synchronous, single-host/local-filesystem registry. The directory lock is
 * process-fenced and is not a distributed-filesystem coordination primitive. */
export class TaskRegistry {
 readonly tasksDir:string;readonly indexPath:string;private activeIndexDirtyPath:string;private archiveTasksDir:string;private lockDir:string;private recoveryLockDir:string;private heldLockToken?:string;private archiveRetryIds=new Set<string>();
 private lockTimeoutMs:number;private lockStaleMs:number;private lockRetryMs:number;private host:string;private clock:()=>number;private fs:RegistryFsPort;
 readonly root:string;
 constructor(root=process.env.PI_TASK_PLANE_HOME??join(process.env.HOME??process.cwd(),".pi","task-plane"),options:RegistryOptions={}){
  this.root=resolve(root);this.tasksDir=join(this.root,"tasks");this.indexPath=join(this.root,"active-index.json");this.activeIndexDirtyPath=join(this.root,".active-index-dirty");this.archiveTasksDir=join(this.root,"archive","tasks");this.lockDir=join(this.root,".registry.lock");this.recoveryLockDir=join(this.root,".registry-lock-recovery");
  this.lockTimeoutMs=options.lockTimeoutMs??5_000;this.lockStaleMs=options.lockStaleMs??30_000;this.lockRetryMs=options.lockRetryMs??25;this.host=options.hostname??osHostname();this.clock=options.clock??Date.now;this.fs=options.fs??nodeRegistryFs;
  try{this.fs.mkdir(this.tasksDir,{recursive:true,mode:0o700});}catch(e){throw runtime("Cannot initialize task registry",e);}
 }
 taskDir(id:string){assertId(id);return join(this.tasksDir,id);} metadataPath(id:string){return join(this.taskDir(id),"metadata.json");} outputPath(id:string){return join(this.taskDir(id),"output.log");} terminalClaimPath(id:string){return join(this.taskDir(id),"model-wake.claim");}
 get(id:string):TaskRecord|undefined {assertId(id);const path=this.metadataPath(id);try{return this.readRecord(path,id);}catch(error){if(code(error)!=="ENOENT")throw error;}const archived=join(this.archiveTasksDir,id,"metadata.json");let record:TaskRecord;try{record=this.readRecord(archived,id);}catch(error){if(code(error)==="ENOENT")return;throw error;}try{this.fs.symlink(join(this.archiveTasksDir,id),this.taskDir(id));}catch{}return record;}
 list(includeCompleted=false):TaskRecord[]{return this.scan(includeCompleted).filter(r=>includeCompleted||ACTIVE.has(r.status)||r.status==="orphaned").sort(order);}
 listSession(sessionId:string,includeCompleted=false):TaskRecord[]{assertRuntimeId(sessionId,"session id");return this.list(includeCompleted).filter(r=>r.owner_session_id===sessionId);}

 admit(ownerSessionId:string,draft:AdmissionDraft):{record:TaskRecord;idempotent:boolean}{assertRuntimeId(ownerSessionId,"session id");const safe=validateAdmissionDraft(draft);if(safe.owner_session_id!==ownerSessionId)throw new RegistryConflictError("Admission owner session mismatch.");for(let attempt=0;attempt<3;attempt++){const prepared=attempt===0?undefined:{epoch:this.indexEpoch(),records:this.scan()};try{return this.withLock(()=>{
  let ids=this.readActiveIndex();if(!ids){if(!prepared||prepared.epoch!==this.indexEpoch())throw new AdmissionRetry();const current=prepared.records.filter(record=>ACTIVE.has(record.status)).map(record=>this.get(record.task_id)).filter((record):record is TaskRecord=>!!record&&ACTIVE.has(record.status));ids=current.map(record=>record.task_id);this.refreshIndex(current);}
  const records=ids.map(id=>this.get(id)).filter((record):record is TaskRecord=>!!record&&ACTIVE.has(record.status));const canonicalIds=records.map(record=>record.task_id).sort();if(JSON.stringify(canonicalIds)!==JSON.stringify([...ids].sort())){this.refreshIndex(records);throw new AdmissionRetry();}const active=records.filter(record=>record.owner_session_id===ownerSessionId);
  if(safe.idempotency_key){const old=active.find(record=>record.type==="monitor"&&record.idempotency_key===safe.idempotency_key);if(old)return{record:old,idempotent:true};}
  if(active.length>=25)throw new RegistryError("Active task cap (25) reached for this session.");
  const taskId=makeId(),dir=this.taskDir(taskId),now=safe.started_at??new Date().toISOString();assertIso(now,"started_at");
  const attemptId=randomBytes(16).toString("hex");const record:TaskRecord={...safe,schema_version:3,record_version:1,task_id:taskId,status:"running",owner_session_id:ownerSessionId,output_path:this.outputPath(taskId),metadata_path:this.metadataPath(taskId),started_at:now,updated_at:now,output_bytes:0,attempt:1,attempt_id:attemptId,attempt_phase:safe.type==="monitor"&&safe.mode==="interval"?"claimed":"starting"};
  validateRecord(record,this);try{this.fs.mkdir(dir,{mode:0o700});const output=this.fs.open(record.output_path,"wx",0o600);this.fs.close(output);const priorActive=this.markIndexDirty();this.writeMetadata(record);if(priorActive)this.tryUpdateIndex(record,priorActive);return{record,idempotent:false};}catch(e){if(this.getCommitted(taskId))return{record:this.getCommitted(taskId)!,idempotent:false};this.fs.rm(dir,{recursive:true,force:true});throw e instanceof RegistryError?e:runtime("Task admission failed",e);}
 });}catch(error){if(!(error instanceof AdmissionRetry))throw error;}}throw new RegistryRuntimeError("Task admission could not stabilize the active index.");}

 attachProcess(id:string,session:string,expected:number,runtimeId:string,pid:number,pgid?:number):TaskRecord {assertRuntimeId(runtimeId,"runtime id");assertPositiveInteger(pid,"pid");if(pgid!==undefined)assertPositiveInteger(pgid,"pgid");return this.transition(id,session,expected,r=>({...r,owner_runtime_id:runtimeId,pid,pgid}));}
 setBlocked(id:string,session:string,expected:number,blocked:boolean,reason?:string):TaskRecord{return this.transition(id,session,expected,r=>({...r,status:blocked?"blocked":"running",blocked_reason:blocked?required(reason,"blocked reason"):undefined}));}
 updateOutput(id:string,session:string,expected:number,bytes:number):TaskRecord {assertNonnegative(bytes,"output bytes");return this.transition(id,session,expected,r=>({...r,output_bytes:bytes}));}
 commitSchedule(id:string,session:string,expected:number,nextRunAt:string,lastHash:string):TaskRecord {assertIso(nextRunAt,"next_run_at");required(lastHash,"last hash");return this.transition(id,session,expected,r=>({...r,next_run_at:nextRunAt,last_hash:lastHash}));}
 commitScheduleClaimed(id:string,session:string,expected:number,token:string,nextRunAt:string,lastHash:string,now=new Date()):TaskRecord {assertIso(nextRunAt,"next_run_at");required(lastHash,"last hash");assertDate(now);return this.transition(id,session,expected,r=>{this.assertFence(r,token,now);return{...r,next_run_at:nextRunAt,last_hash:lastHash,pid:undefined,pgid:undefined};},true);} 
 requestStop(id:string,session:string,expected:number,reason:StopReason,signal:"SIGTERM"|"SIGKILL"="SIGTERM",at=new Date(),killAfterS=5):TaskRecord {if(!STOPS.has(reason))throw new RegistryError("Invalid stop reason.");assertDate(at);if(!finitePositive(killAfterS)||killAfterS>60)throw new RegistryError("Invalid stop escalation delay.");return this.transition(id,session,expected,r=>r.stop_requested_at?r:{...r,stop_request_id:randomBytes(16).toString("hex"),stop_requested_at:at.toISOString(),stop_requested_reason:reason,stop_requested_signal:signal,stop_requested_kill_after_s:killAfterS,stop_request_deadline_at:new Date(at.getTime()+killAfterS*1000).toISOString()});}
 acknowledgeStop(id:string,session:string,expected:number,runtimeId:string,at=new Date()):TaskRecord{assertRuntimeId(runtimeId,"runtime id");assertDate(at);return this.transition(id,session,expected,r=>{if(!r.stop_requested_at)throw new RegistryConflictError("No stop request to acknowledge.");if(r.owner_runtime_id!==runtimeId)throw new RegistryConflictError("Only the attempt owner may acknowledge stop.");return r.stop_acknowledged_at?r:{...r,stop_acknowledged_at:at.toISOString(),stop_acknowledged_by_runtime_id:runtimeId,attempt_phase:"closing"};});}
 requestSuspension(id:string,session:string,expected:number,at=new Date()):TaskRecord{assertDate(at);return this.transition(id,session,expected,r=>({...r,suspension_pending:true,suspension_requested_at:r.suspension_requested_at??at.toISOString(),attempt_phase:"suspension_requested"}));}
 suspend(id:string,session:string,expected:number,at=new Date()):TaskRecord {assertDate(at);return this.transition(id,session,expected,r=>({...r,suspended_at:at.toISOString(),suspension_completed_at:at.toISOString(),suspension_pending:true,attempt_phase:"suspended",pid:undefined,pgid:undefined,owner_runtime_id:undefined}));}
 suspendClaimed(id:string,session:string,expected:number,token:string,at=new Date()):TaskRecord {assertDate(at);return this.transition(id,session,expected,r=>{this.assertFence(r,token,at);return{...r,suspended_at:at.toISOString(),suspension_completed_at:at.toISOString(),suspension_pending:true,attempt_phase:"suspended",pid:undefined,pgid:undefined,owner_runtime_id:undefined,lease_token:undefined,lease_attempt_id:undefined,lease_owner_runtime_id:undefined,lease_expires_at:undefined};},true);}
 resume(id:string,session:string,expected:number,runtimeId:string):TaskRecord {assertRuntimeId(runtimeId,"runtime id");return this.transition(id,session,expected,r=>({...r,suspended_at:undefined,suspension_pending:false,suspension_requested_at:undefined,suspension_completed_at:undefined,attempt:(r.attempt??1)+1,attempt_id:randomBytes(16).toString("hex"),attempt_phase:"starting",owner_runtime_id:runtimeId}));}
 resumeAndClaim(id:string,session:string,expected:number,runtimeId:string,ttlMs:number,now=new Date()):LeaseClaimResult{validateLeaseArgs(runtimeId,ttlMs,now);return this.withLock(()=>{const r=this.owned(id,session);this.assertVersion(r,expected);if(r.status!=="running"||r.attempt_phase!=="suspended")return{outcome:"contended",record:r};const attemptId=randomBytes(16).toString("hex");return{outcome:"acquired",record:this.commit({...r,suspended_at:undefined,suspension_pending:false,suspension_requested_at:undefined,suspension_completed_at:undefined,attempt:(r.attempt??1)+1,attempt_id:attemptId,attempt_phase:"starting",owner_runtime_id:runtimeId,lease_token:randomBytes(16).toString("hex"),lease_attempt_id:attemptId,lease_owner_runtime_id:runtimeId,lease_expires_at:new Date(now.getTime()+ttlMs).toISOString()})};});}
 claimUnstartedStream(id:string,session:string,expected:number,runtimeId:string,ttlMs:number,now=new Date()):LeaseClaimResult{validateLeaseArgs(runtimeId,ttlMs,now);return this.withLock(()=>{const r=this.owned(id,session);this.assertVersion(r,expected);const eligible=r.status==="running"&&r.type==="monitor"&&r.mode==="stream"&&r.attempt_phase==="starting"&&!r.owner_runtime_id&&!r.pid&&!r.pgid&&!r.lease_token&&!r.suspension_pending&&!r.stop_requested_at;if(!eligible)return{outcome:"contended",record:r};if(r.deadline_at&&Date.parse(r.deadline_at)<=now.getTime()){const expired=this.commit(expiredMonitor(r,now));return{outcome:"unclaimable",record:expired,status:"timed_out"};}return{outcome:"acquired",record:this.commit({...r,owner_runtime_id:runtimeId,lease_token:randomBytes(16).toString("hex"),lease_attempt_id:r.attempt_id,lease_owner_runtime_id:runtimeId,lease_expires_at:new Date(now.getTime()+ttlMs).toISOString()})};});}
 markOrphaned(id:string,session:string,expected:number,reason:string):TaskRecord{return this.transition(id,session,expected,r=>omitExecution({...r,status:"orphaned",blocked_reason:required(reason,"orphan reason")}));}

 claimLease(id:string,session:string,expected:number,runtimeId:string,ttlMs:number,now=new Date()):LeaseClaimResult {validateLeaseArgs(runtimeId,ttlMs,now);return this.withLock(()=>{const r=this.owned(id,session);this.assertVersion(r,expected);if(isTerminal(r.status)||r.status==="orphaned")return{outcome:"unclaimable",record:r,status:r.status};const expires=r.lease_expires_at?Date.parse(r.lease_expires_at):0;if(r.lease_token){if(expires>now.getTime())return{outcome:"contended",record:r};return{outcome:"unclaimable",record:this.commit({...r,status:"orphaned",blocked_reason:"expired_unverified_attempt",pid:undefined,pgid:undefined,lease_token:undefined,lease_attempt_id:undefined,lease_owner_runtime_id:undefined,lease_expires_at:undefined}),status:"orphaned"};}return{outcome:"acquired",record:this.commit({...r,owner_runtime_id:runtimeId,lease_token:randomBytes(16).toString("hex"),lease_attempt_id:r.attempt_id,lease_owner_runtime_id:runtimeId,lease_expires_at:new Date(now.getTime()+ttlMs).toISOString()})};});}
 renewLease(id:string,session:string,expected:number,token:string,ttlMs:number,now=new Date()):TaskRecord {validateLeaseArgs("renew",ttlMs,now);return this.transition(id,session,expected,r=>{this.assertFence(r,token,now);return{...r,lease_expires_at:new Date(now.getTime()+ttlMs).toISOString()};},true);}
 releaseLease(id:string,session:string,expected:number,token:string,now=new Date()):TaskRecord {assertDate(now);return this.transition(id,session,expected,r=>{this.assertFence(r,token,now);return{...r,pid:undefined,pgid:undefined,owner_runtime_id:undefined,attempt_phase:r.type==="monitor"&&r.mode==="interval"?"claimed":r.attempt_phase,lease_token:undefined,lease_attempt_id:undefined,lease_owner_runtime_id:undefined,lease_expires_at:undefined};},true);}
 updateAttemptClaimed(id:string,session:string,expected:number,token:string,patch:AttemptPatch,now=new Date()):TaskRecord {const safe=validateAttemptPatch(patch);return this.transition(id,session,expected,r=>{this.assertFence(r,token,now);return{...r,...safe};},true);}
 finalizeClaimed(id:string,session:string,expected:number,token:string,status:TerminalTaskStatus,patch:TerminalPatch={},now=new Date()):TaskRecord {return this.finalize(id,session,expected,status,patch,now,token);}
 finalizeUnleased(id:string,session:string,expected:number,status:TerminalTaskStatus,patch:TerminalPatch={},now=new Date()):TaskRecord {return this.finalize(id,session,expected,status,patch,now);}

 claimDue(session:string,runtimeId:string,limit:number,ttlMs:number,now=new Date()):TaskRecord[]{assertRuntimeId(session,"session id");validateLeaseArgs(runtimeId,ttlMs,now);if(!Number.isInteger(limit)||limit<0)throw new RegistryError("Invalid claim limit.");return this.withLock(()=>{const due=this.scan().filter(r=>r.owner_session_id===session&&r.type==="monitor"&&r.mode==="interval"&&ACTIVE.has(r.status)&&!r.suspension_pending&&!r.stop_requested_at&&!r.lease_token&&(!r.attempt_phase||["claimed","running"].includes(r.attempt_phase))&&(!r.next_run_at||Date.parse(r.next_run_at)<=now.getTime())).sort(order).slice(0,limit),claimed:TaskRecord[]=[];for(const r of due)try{claimed.push(this.commit({...r,owner_runtime_id:runtimeId,lease_token:randomBytes(16).toString("hex"),lease_attempt_id:r.attempt_id,lease_owner_runtime_id:runtimeId,lease_expires_at:new Date(now.getTime()+ttlMs).toISOString()}));}catch(error){console.warn(`task-plane claim creation failed for ${r.task_id}; retrying on a later scheduler tick: ${error instanceof Error?error.message:String(error)}`);}return claimed;});}
 updateDispatch(id:string,session:string,expected:number,state:DispatchState,at=new Date(),error?:string):TaskRecord {if(!DISPATCH.has(state))throw new RegistryError("Invalid dispatch state.");assertDate(at);return this.withLock(()=>{const r=this.owned(id,session);this.assertVersion(r,expected);if(!isTerminal(r.status))throw new RegistryConflictError("Only terminal tasks have terminal dispatch state.");if(!dispatchForward(r.dispatch_state,state))throw new RegistryConflictError("Dispatch state cannot move backward.");const next=this.commit({...r,dispatch_state:state,dispatch_requested_at:state==="dispatch_requested"?at.toISOString():r.dispatch_requested_at,host_api_invoked_at:state==="host_api_invoked"?at.toISOString():r.host_api_invoked_at,dispatch_error:state==="dispatch_sync_failed"?required(error,"dispatch error"):r.dispatch_error});if(state==="host_api_invoked"||state==="dispatch_sync_failed")this.archiveTerminal(next);return next;});}
 dispatchBackfillCandidates(session:string):TaskRecord[]{assertRuntimeId(session,"session id");return this.scan().filter(r=>r.owner_session_id===session&&isTerminal(r.status)&&r.dispatch_state===undefined&&!r.notification_suppressed_reason);}
 claimTerminal(id:string,session:string):boolean {return this.withLock(()=>{const r=this.owned(id,session);if(!isTerminal(r.status))throw new RegistryConflictError("Only terminal tasks may be claimed.");if(r.dispatch_state!==undefined)return false;const claimPath=this.terminalClaimPath(id);let fd:number|undefined;try{fd=this.fs.open(claimPath,"wx",0o600);this.fs.close(fd);fd=undefined;}catch(e){if(fd!==undefined)try{this.fs.close(fd);}catch{}if(code(e)==="EEXIST")return false;try{this.fs.unlink(claimPath);}catch{}throw runtime(`Cannot create terminal notification claim ${claimPath}`,e);}try{this.commit({...r,dispatch_state:"dispatch_requested",dispatch_requested_at:new Date().toISOString()});return true;}catch(e){const committed=this.get(id);if(committed?.dispatch_state==="dispatch_requested")return true;try{this.fs.unlink(claimPath);}catch{}throw e;}});}
 appendEventTimestamp(id:string,session:string,expected:number,token:string,now=new Date()):{record:TaskRecord;count:number}{assertDate(now);return this.withLock(()=>{const r=this.owned(id,session);this.assertVersion(r,expected);this.assertFence(r,token,now);const cutoff=now.getTime()-60_000,old=eventTimestamps(r).filter(t=>t>=cutoff),timestamps=[...old,now.getTime()].slice(-301);return{record:this.commit({...r,event_timestamps:timestamps},Date.parse(r.lease_expires_at!)),count:timestamps.length};});}

 rebuildIndex():string[]{for(let attempt=0;attempt<3;attempt++){const epoch=this.indexEpoch(),records=this.scan();const rebuilt=this.withLock(()=>epoch===this.indexEpoch()?this.refreshIndex(records):undefined);if(rebuilt)return rebuilt;}throw new RegistryRuntimeError("Active index rebuild could not stabilize the registry snapshot.");}
 reconcile():TaskRecord[]{this.repairArchiveLinks();let records=this.scan();for(const snapshot of records){if(!archiveEligible(snapshot))continue;this.withLock(()=>{const current=this.get(snapshot.task_id);if(current)this.archiveTerminal(current);});}this.repairArchiveLinks();for(let attempt=0;attempt<3;attempt++){const epoch=this.indexEpoch();records=this.scan();const reconciled=this.withLock(()=>epoch===this.indexEpoch()?(this.refreshIndex(records),true):false);if(reconciled)return records;}throw new RegistryRuntimeError("Task reconciliation could not stabilize the registry snapshot.");}
 orphanExpiredAttempts(session:string,now=new Date(),verifiedLive=new Set<string>()):TaskRecord[]{assertRuntimeId(session,"session id");assertDate(now);return this.withLock(()=>this.scan().filter(r=>r.owner_session_id===session&&!verifiedLive.has(r.task_id)&&!isTerminal(r.status)&&r.status!=="orphaned"&&r.lease_expires_at&&Date.parse(r.lease_expires_at)<=now.getTime()).map(r=>this.commit(omitExecution({...r,status:"orphaned",blocked_reason:"expired_unverified_attempt"}))));}
 expireMonitorLifespan(id:string,session:string,expected:number,now=new Date()):TaskRecord{assertDate(now);return this.withLock(()=>{const r=this.owned(id,session);this.assertVersion(r,expected);this.assertExpiredMonitor(r,now);return this.commit(expiredMonitor(r,now));});}
 expireSuspendedMonitorLifespan(id:string,session:string,expected:number,now=new Date()):TaskRecord{assertDate(now);return this.withLock(()=>{const r=this.owned(id,session);this.assertVersion(r,expected);this.assertExpiredMonitor(r,now);if(r.attempt_phase!=="suspended"||!r.suspended_at)throw new RegistryConflictError("Monitor is not durably suspended.");return this.commit(expiredMonitor(r,now));});}

 private finalize(id:string,session:string,expected:number,status:TerminalTaskStatus,patch:TerminalPatch,now:Date,token?:string):TaskRecord {if(!TERMINAL.has(status))throw new RegistryError("Invalid terminal status.");assertDate(now);const safe=validateTerminalPatch(patch);return this.withLock(()=>{const r=this.owned(id,session);this.assertVersion(r,expected);if(isTerminal(r.status)||r.status==="orphaned")throw new RegistryConflictError(`Task ${id} is unmanageable and cannot be terminalized.`);if(token)this.assertFence(r,token,now);else if(r.lease_token)throw new RegistryConflictError(`Task ${id} has an active lease.`);const next=this.commit({...r,...safe,status,attempt_phase:"outcome_pending",ended_at:safe.ended_at??now.toISOString(),pid:undefined,pgid:undefined,owner_runtime_id:undefined,lease_token:undefined,lease_attempt_id:undefined,lease_owner_runtime_id:undefined,lease_expires_at:undefined},token?Date.parse(r.lease_expires_at!):undefined);if(next.notification_suppressed_reason==="shutdown")this.archiveTerminal(next);return next;});}
 private transition(id:string,session:string,expected:number,fn:(r:TaskRecord)=>TaskRecord,hardLeaseFence=false):TaskRecord {return this.withLock(()=>{const r=this.owned(id,session);this.assertVersion(r,expected);if(isTerminal(r.status)||r.status==="orphaned")throw new RegistryConflictError(`Task ${id} is unmanageable; execution state is immutable.`);return this.commit(fn(r),hardLeaseFence?Date.parse(r.lease_expires_at!):undefined);});}
 private commit(record:TaskRecord,leaseDeadline?:number):TaskRecord {const next={...record,record_version:record.record_version+1,updated_at:new Date().toISOString()};validateRecord(next,this);const priorActive=this.markIndexDirty();this.writeMetadata(next,leaseDeadline);if(priorActive)this.tryUpdateIndex(next,priorActive);return next;}
 private owned(id:string,session:string):TaskRecord {assertRuntimeId(session,"session id");const r=this.get(id);if(!r)throw new RegistryError(`Unknown task ${id}.`);if(r.owner_session_id!==session)throw new RegistryConflictError(`Task ${id} belongs to another session.`);return r;}
 private assertVersion(r:TaskRecord,expected:number){if(!Number.isInteger(expected)||expected<1||r.record_version!==expected)throw new RegistryConflictError(`Stale task version for ${r.task_id}: expected ${expected}, canonical ${r.record_version}.`);}
 private assertExpiredMonitor(r:TaskRecord,now:Date){if(r.type!=="monitor"||!r.deadline_at||Date.parse(r.deadline_at)>now.getTime())throw new RegistryConflictError("Monitor lifespan has not expired.");if(isTerminal(r.status)||r.status==="orphaned")throw new RegistryConflictError(`Task ${r.task_id} is unmanageable.`);}
 private assertTokenFence(r:TaskRecord,token:string){required(token,"lease token");if(r.lease_token!==token||r.lease_attempt_id!==r.attempt_id)throw new RegistryConflictError(`Lease fence rejected for ${r.task_id}.`);}
 private assertFence(r:TaskRecord,token:string,now:Date){assertDate(now);this.assertTokenFence(r,token);if(Date.parse(r.lease_expires_at!)<=now.getTime())throw new RegistryConflictError(`Lease expired for ${r.task_id}.`);}
 private scan(includeArchived=false):TaskRecord[]{let entries;try{entries=this.fs.readdir(this.tasksDir);}catch(e){throw runtime("Cannot scan task registry",e);}const out:TaskRecord[]=[],seen=new Set<string>();for(const entry of entries){if(!entry.isDirectory()&&!(includeArchived&&entry.isSymbolicLink()))continue;if(!validId(entry.name))throw new RegistryCorruptionError(`Invalid task directory name ${entry.name}.`);const r=this.get(entry.name);if(!r)throw new RegistryCorruptionError(`Task directory ${entry.name} has no metadata.json.`);out.push(r);seen.add(entry.name);}if(includeArchived){let archived:Dirent[];try{archived=this.fs.readdir(this.archiveTasksDir);}catch(error){if(code(error)==="ENOENT")return out;throw runtime("Cannot scan archived task registry",error);}for(const entry of archived){if(!entry.isDirectory()||seen.has(entry.name))continue;if(!validId(entry.name))throw new RegistryCorruptionError(`Invalid archived task directory name ${entry.name}.`);const path=join(this.archiveTasksDir,entry.name,"metadata.json"),record=this.readRecord(path,entry.name);out.push(record);try{this.fs.symlink(join(this.archiveTasksDir,entry.name),this.taskDir(entry.name));}catch{}}}return out;}
 private readRecord(path:string,id:string):TaskRecord {let text:string;try{text=this.fs.read(path);}catch(error){if(code(error)==="ENOENT")throw error;throw runtime(`Cannot read task metadata ${path}`,error);}try{return parseRecord(JSON.parse(text),this,id);}catch(error){if(error instanceof RegistryError)throw error;throw new RegistryCorruptionError(`Malformed task metadata ${path}`,{cause:error});}}
 private archiveTerminal(record:TaskRecord):void {if(!archiveEligible(record))return;const source=this.taskDir(record.task_id),target=join(this.archiveTasksDir,record.task_id);try{this.fs.mkdir(this.archiveTasksDir,{recursive:true,mode:0o700});this.fs.rename(source,target);try{this.fs.symlink(target,source);}catch(error){this.fs.rename(target,source);throw error;}this.archiveRetryIds.delete(record.task_id);}catch{this.archiveRetryIds.add(record.task_id);try{this.fs.symlink(target,source);this.archiveRetryIds.delete(record.task_id);}catch{}/* Metadata is already committed; retention is best-effort and retries later. */}}
 private retryArchives(limit=8):void {let remaining=limit;for(const id of [...this.archiveRetryIds]){if(remaining--<=0)return;try{const record=this.get(id);if(!record){this.archiveRetryIds.delete(id);continue;}this.archiveTerminal(record);}catch{}}}
 private repairArchiveLinks():void {let archived:Dirent[];try{archived=this.fs.readdir(this.archiveTasksDir);}catch{return;}let visible:Set<string>;try{visible=new Set(this.fs.readdir(this.tasksDir).map(entry=>entry.name));}catch{return;}for(const entry of archived){if(!entry.isDirectory()||!validId(entry.name)||visible.has(entry.name))continue;try{this.fs.symlink(join(this.archiveTasksDir,entry.name),this.taskDir(entry.name));}catch{}}}
 private atomicWrite(path:string,data:string,leaseDeadline?:number){const tmp=`${path}.${process.pid}.${this.heldLockToken}.tmp`;let fd:number|undefined;try{fd=this.fs.open(tmp,"wx",0o600);this.fs.write(fd,data);this.fs.close(fd);fd=undefined;if(leaseDeadline!==undefined&&this.clock()>=leaseDeadline)throw new RegistryConflictError(`Lease expired before commit.`);this.fs.rename(tmp,path);}catch(e){if(fd!==undefined)try{this.fs.close(fd);}catch{}try{this.fs.unlink(tmp);}catch{}throw e;}}
 private writeMetadata(r:TaskRecord,leaseDeadline?:number){const path=this.metadataPath(r.task_id);try{this.atomicWrite(path,JSON.stringify(r,null,2),leaseDeadline);}catch(e){if(e instanceof RegistryError)throw e;throw runtime(`Cannot commit task metadata ${path}`,e);}}
 private readActiveIndex():string[]|undefined {try{this.fs.read(this.activeIndexDirtyPath);return;}catch(error){if(code(error)!=="ENOENT")return;}return this.readIndexPayload()?.active;}
 private indexEpoch():string {try{return `dirty:${this.fs.read(this.activeIndexDirtyPath)}`;}catch(error){if(code(error)!=="ENOENT")return "unreadable";}try{return `clean:${this.fs.read(this.indexPath)}`;}catch{return "missing";}}
 private markIndexDirty():string[]|undefined {const active=this.readActiveIndex();try{this.atomicWrite(this.activeIndexDirtyPath,randomBytes(16).toString("hex"));return active;}catch(error){throw runtime("Cannot mark active index dirty",error);}}
 private clearIndexDirty(){try{this.fs.unlink(this.activeIndexDirtyPath);}catch(error){if(code(error)!=="ENOENT")throw error;}}
 private tryUpdateIndex(record:TaskRecord,active:string[]){try{const ids=new Set(active);if(ACTIVE.has(record.status))ids.add(record.task_id);else ids.delete(record.task_id);this.atomicWrite(this.indexPath,JSON.stringify({schema_version:1,revision:randomBytes(16).toString("hex"),active:[...ids].sort()},null,2));this.clearIndexDirty();}catch{/* metadata rename is the commit point; a retained dirty marker forces safe rebuild */}}
 private readIndexPayload():{revision:string;active:string[]}|undefined {try{const value=JSON.parse(this.fs.read(this.indexPath)),active=value?.schema_version===1?value.active:undefined;if(typeof value?.revision==="string"&&value.revision&&Array.isArray(active)&&active.every((item:unknown)=>typeof item==="string"&&validId(item))&&new Set(active).size===active.length)return{revision:value.revision,active};}catch{}return;}
 private refreshIndex(records=this.scan()):string[]{const active=records.filter(r=>ACTIVE.has(r.status)).map(r=>r.task_id).sort();try{this.atomicWrite(this.indexPath,JSON.stringify({schema_version:1,revision:randomBytes(16).toString("hex"),active},null,2));this.clearIndexDirty();return active;}catch(e){throw runtime("Cannot refresh active task index",e);}}
 private repairIndex(records:TaskRecord[]){const expected=records.filter(r=>ACTIVE.has(r.status)).map(r=>r.task_id).sort(),actual=this.readActiveIndex();if(!actual||JSON.stringify([...actual].sort())!==JSON.stringify(expected))try{this.refreshIndex(records);}catch{}}
 private getCommitted(id:string){try{return this.get(id);}catch{return undefined;}}
 private writeNew(path:string,data:string){const fd=this.fs.open(path,"wx",0o600);try{this.fs.write(fd,data);}finally{this.fs.close(fd);}}
 private withLock<T>(fn:()=>T):T {if(this.heldLockToken)return fn();const token=`${process.pid}-${Date.now()}-${randomBytes(8).toString("hex")}`,deadline=Date.now()+this.lockTimeoutMs;while(true){try{this.fs.mkdir(this.lockDir,{mode:0o700});this.writeNew(this.lockOwnerPath(),JSON.stringify({pid:process.pid,hostname:this.host,token,acquired_at:Date.now()} satisfies LockOwner));break;}catch(e){if(code(e)!=="EEXIST"){try{this.fs.rm(this.lockDir,{recursive:true,force:true});}catch{}throw runtime("Registry lock acquisition failed",e);}this.removeStaleLock();if(Date.now()>=deadline)throw new RegistryRuntimeError(`Task registry lock acquisition failed at ${this.lockDir}.`);sleep(Math.min(this.lockRetryMs,Math.max(1,deadline-Date.now())));}}this.heldLockToken=token;try{this.retryArchives();return fn();}finally{this.heldLockToken=undefined;const owner=this.readOwner(this.lockDir);if(owner?.token===token)this.fs.rm(this.lockDir,{recursive:true,force:true});}}
 private removeStaleLock(){const recoveryToken=randomBytes(8).toString("hex"),recoveryOwner=join(this.recoveryLockDir,"owner.json");try{this.fs.mkdir(this.recoveryLockDir,{mode:0o700});this.writeNew(recoveryOwner,JSON.stringify({pid:process.pid,hostname:this.host,token:recoveryToken,acquired_at:Date.now()} satisfies LockOwner));}catch(e){if(code(e)!=="EEXIST")return;this.recoverMalformedOrDead(this.recoveryLockDir);return;}try{const owner=this.readOwner(this.lockDir);if(owner){if(owner.hostname===this.host&&!alive(owner.pid))this.removeIfToken(this.lockDir,owner.token);}else this.removeMalformedIfOld(this.lockDir);}finally{this.removeIfToken(this.recoveryLockDir,recoveryToken);}}
 private recoverMalformedOrDead(dir:string){const owner=this.readOwner(dir);if(owner){if(owner.hostname===this.host&&!alive(owner.pid))this.removeIfToken(dir,owner.token);}else this.removeMalformedIfOld(dir);}
 private removeMalformedIfOld(dir:string){try{const age=Date.now()-Number(this.fs.stat(dir).mtimeMs??Date.now());if(age>this.lockStaleMs)this.fs.rm(dir,{recursive:true,force:true});}catch{}}
 private removeIfToken(dir:string,token:string){const owner=this.readOwner(dir);if(owner?.token===token)this.fs.rm(dir,{recursive:true,force:true});}
 private readOwner(dir:string):LockOwner|undefined {try{const o=JSON.parse(this.fs.read(join(dir,"owner.json")));if(Number.isInteger(o.pid)&&o.pid>0&&typeof o.hostname==="string"&&o.hostname&&typeof o.token==="string"&&o.token&&Number.isFinite(o.acquired_at))return o;}catch{}return;}
 private lockOwnerPath(){return join(this.lockDir,"owner.json");}
}

function archiveEligible(record:TaskRecord):boolean{return isTerminal(record.status)&&((record.dispatch_state==="host_api_invoked"||record.dispatch_state==="dispatch_sync_failed")||record.notification_suppressed_reason==="shutdown");}
function eventTimestamps(r:TaskRecord):number[]{const value=(r as TaskRecord&{event_timestamps?:number[]}).event_timestamps;return value??[];}
function omitExecution(r:TaskRecord):TaskRecord{const next={...r};for(const k of ["pid","pgid","owner_runtime_id","lease_token","lease_attempt_id","lease_owner_runtime_id","lease_expires_at"] as const)delete next[k];return next;}
function expiredMonitor(r:TaskRecord,now:Date):TaskRecord{const next=omitExecution({...r,status:"timed_out",stop_reason:"timeout",attempt_phase:"outcome_pending",ended_at:now.toISOString()});for(const k of ["suspended_at","suspension_pending","suspension_requested_at","suspension_completed_at"] as const)delete next[k];return next;}
function parseRecord(raw:unknown,registry:TaskRegistry,expectedId:string):TaskRecord {validateRecord(raw,registry);if(raw.task_id!==expectedId)throw new RegistryCorruptionError(`Task metadata id ${raw.task_id} does not match directory ${expectedId}.`);return raw;}
function validateRecord(raw:unknown,registry:TaskRegistry):asserts raw is TaskRecord {
 if(!raw||typeof raw!=="object"||Array.isArray(raw))throw new RegistryCorruptionError("Invalid task metadata object.");const r=raw as Record<string,unknown>;
 const keys=new Set(["schema_version","record_version","task_id","type","mode","name","command","cwd","status","output_path","metadata_path","started_at","updated_at","ended_at","deadline_at","owner_session_id","owner_session_file","owner_runtime_id","pid","pgid","exit_code","signal","stop_reason","blocked_reason","output_bytes","max_output_bytes","max_runtime_s","interval_s","command_timeout_s","until_output_matches","throttle_s","idempotency_key","next_run_at","last_hash","event_timestamps","suspended_at","attempt","attempt_id","attempt_phase","suspension_pending","suspension_requested_at","suspension_completed_at","dispatch_state","dispatch_requested_at","host_api_invoked_at","dispatch_error","notification_suppressed_reason","lease_token","lease_attempt_id","lease_owner_runtime_id","lease_expires_at","stop_requested_at","stop_request_id","stop_requested_signal","stop_requested_reason","stop_requested_kill_after_s","stop_request_deadline_at","stop_acknowledged_at","stop_acknowledged_by_runtime_id","stdio_drain_timed_out","failure_reason"]);for(const k of Object.keys(r))if(!keys.has(k))bad(k);
 if(r.schema_version!==3)bad("schema_version");if(!Number.isInteger(r.record_version)||(r.record_version as number)<1)bad("record_version");if(typeof r.task_id!=="string"||!validId(r.task_id))bad("task_id");if(r.metadata_path!==registry.metadataPath(r.task_id)||r.output_path!==registry.outputPath(r.task_id))bad("paths");
 if(r.type!=="bash"&&r.type!=="monitor")bad("type");if(r.type==="bash"&&(r.mode!==undefined||r.interval_s!==undefined||r.command_timeout_s!==undefined||r.until_output_matches!==undefined||r.throttle_s!==undefined))bad("bash mode fields");if(r.type==="monitor"&&(r.mode!=="stream"&&r.mode!=="interval"))bad("monitor mode");if(r.type==="monitor"&&r.max_runtime_s!==undefined)bad("monitor max_runtime_s");if(r.mode==="stream"&&(r.interval_s!==undefined||r.command_timeout_s!==undefined||r.until_output_matches!==undefined))bad("stream fields");if(r.mode==="interval"&&(!finitePositive(r.interval_s)||(r.interval_s as number)<0.001))bad("interval_s");
 for(const k of ["command","cwd","owner_session_id"]){if(typeof r[k]!=="string"||!(r[k] as string).trim())bad(k);}for(const k of ["name","owner_session_file","owner_runtime_id","signal","blocked_reason","until_output_matches","idempotency_key","last_hash","dispatch_error","lease_token","lease_attempt_id","lease_owner_runtime_id","attempt_id","attempt_phase","stop_request_id","stop_acknowledged_by_runtime_id","notification_suppressed_reason","failure_reason"]){if(r[k]!==undefined&&(typeof r[k]!=="string"||!(r[k] as string).trim()))bad(k);}
 if(typeof r.status!=="string"||!STATUSES.has(r.status))bad("status");for(const k of ["started_at","updated_at","ended_at","deadline_at","next_run_at","suspended_at","suspension_requested_at","suspension_completed_at","dispatch_requested_at","host_api_invoked_at","lease_expires_at","stop_requested_at","stop_request_deadline_at","stop_acknowledged_at"]){if(r[k]!==undefined&&(typeof r[k]!=="string"||!validIso(r[k] as string)))bad(k);}for(const k of ["output_bytes","max_output_bytes","max_runtime_s","interval_s","command_timeout_s","throttle_s","pid","pgid","exit_code","attempt","stop_requested_kill_after_s"]){if(r[k]!==undefined&&(typeof r[k]!=="number"||!Number.isFinite(r[k])||(r[k] as number)<0))bad(k);}if(!Number.isFinite(r.output_bytes)||!Number.isFinite(r.max_output_bytes)||(r.output_bytes as number)<0||(r.max_output_bytes as number)<=0)bad("output counters");if(r.pid!==undefined&&(!Number.isInteger(r.pid)||Number(r.pid)<=0)||r.pgid!==undefined&&(!Number.isInteger(r.pgid)||Number(r.pgid)<=0)||r.attempt!==undefined&&(!Number.isInteger(r.attempt)||Number(r.attempt)<=0)||r.exit_code!==undefined&&!Number.isInteger(r.exit_code))bad("integer field");
 if(r.event_timestamps!==undefined&&(!Array.isArray(r.event_timestamps)||r.event_timestamps.length>301||r.event_timestamps.some((v,i,a)=>!Number.isFinite(v)||v<0||(i>0&&v<a[i-1]))))bad("event_timestamps");
 if(r.suspension_pending!==undefined&&typeof r.suspension_pending!=="boolean"||r.stdio_drain_timed_out!==undefined&&typeof r.stdio_drain_timed_out!=="boolean")bad("boolean field");if(r.attempt_phase!==undefined&&!new Set(["claimed","starting","running","closing","outcome_pending","suspension_requested","suspended"]).has(r.attempt_phase as string))bad("attempt_phase");if(r.notification_suppressed_reason!==undefined&&r.notification_suppressed_reason!=="shutdown")bad("notification_suppressed_reason");if(r.attempt_id===undefined||r.attempt_phase===undefined)bad("attempt identity");if(r.suspended_at!==undefined&&r.attempt_phase!=="suspended")bad("suspension coherence");if(r.attempt_phase==="suspended"&&(!r.suspension_pending||!r.suspended_at||r.pid!==undefined||r.pgid!==undefined||r.status!=="running"))bad("suspension coherence");const terminal=typeof r.status==="string"&&TERMINAL.has(r.status);if(terminal!==Boolean(r.ended_at))bad("status/ended_at");if(r.status==="orphaned"&&(!r.blocked_reason||r.ended_at))bad("orphaned");
 if(r.stop_reason!==undefined&&!STOPS.has(r.stop_reason as string)||r.stop_requested_reason!==undefined&&!STOPS.has(r.stop_requested_reason as string))bad("stop reason");if(r.failure_reason!==undefined&&r.failure_reason!=="command_timeout")bad("failure_reason");if(r.stop_requested_signal!==undefined&&r.stop_requested_signal!=="SIGTERM"&&r.stop_requested_signal!=="SIGKILL")bad("stop_requested_signal");const stop=[r.stop_requested_at,r.stop_requested_signal,r.stop_requested_reason,r.stop_requested_kill_after_s,r.stop_request_deadline_at].filter(x=>x!==undefined).length;if(stop!==0&&stop!==5)bad("stop request coherence");if(stop===5&&(!finitePositive(r.stop_requested_kill_after_s)||Number(r.stop_requested_kill_after_s)>60||Date.parse(r.stop_request_deadline_at as string)!==Date.parse(r.stop_requested_at as string)+Number(r.stop_requested_kill_after_s)*1000))bad("stop request deadline");
 if(r.dispatch_state!==undefined&&!DISPATCH.has(r.dispatch_state as string))bad("dispatch_state");if(!terminal&&(r.dispatch_state!==undefined||r.dispatch_requested_at!==undefined||r.host_api_invoked_at!==undefined||r.dispatch_error!==undefined))bad("nonterminal dispatch");if(r.dispatch_state!==undefined&&!r.dispatch_requested_at)bad("dispatch coherence");if(r.dispatch_state==="host_api_invoked"&&!r.host_api_invoked_at||r.dispatch_state!=="host_api_invoked"&&r.host_api_invoked_at!==undefined||r.dispatch_state==="dispatch_sync_failed"&&!r.dispatch_error||r.dispatch_state!=="dispatch_sync_failed"&&r.dispatch_error!==undefined)bad("dispatch coherence");
 const lease=[r.lease_token,r.lease_attempt_id,r.lease_owner_runtime_id,r.lease_expires_at],present=lease.filter(x=>x!==undefined).length;if(present!==0&&present!==4)bad("lease triple");if(present===4&&r.lease_attempt_id!==r.attempt_id)bad("lease attempt fence");if(present===4&&(terminal||r.status==="orphaned"))bad("lease triple");
}
function bad(field:string):never{throw new RegistryCorruptionError(`Invalid task metadata field: ${field}.`);}
function validateTerminalPatch(p:TerminalPatch):TerminalPatch {if(!p||typeof p!=="object"||Array.isArray(p))throw new RegistryError("Invalid terminal patch.");const raw=p as Record<string,unknown>,allowed=new Set(["exit_code","signal","stop_reason","ended_at","stdio_drain_timed_out","notification_suppressed_reason","failure_reason"]);for(const k of Object.keys(raw))if(!allowed.has(k))throw new RegistryError(`Invalid terminal patch field: ${k}.`);if(p.exit_code!==undefined&&(!Number.isFinite(p.exit_code)||!Number.isInteger(p.exit_code)))throw new RegistryError("Invalid exit code.");if(p.signal!==undefined)required(p.signal,"signal");if(p.ended_at!==undefined)assertIso(p.ended_at,"ended_at");if(p.stop_reason!==undefined&&!STOPS.has(p.stop_reason))throw new RegistryError("Invalid stop reason.");if(p.stdio_drain_timed_out!==undefined&&typeof p.stdio_drain_timed_out!=="boolean")throw new RegistryError("Invalid drain timeout flag.");if(p.notification_suppressed_reason!==undefined&&p.notification_suppressed_reason!=="shutdown")throw new RegistryError("Invalid suppression reason.");if(p.failure_reason!==undefined&&p.failure_reason!=="command_timeout")throw new RegistryError("Invalid failure reason.");const safe:TerminalPatch={};for(const k of allowed)if(Object.prototype.hasOwnProperty.call(raw,k))(safe as Record<string,unknown>)[k]=raw[k];return safe;}
function validateAdmissionDraft(p:AdmissionDraft):AdmissionDraft {if(!p||typeof p!=="object"||Array.isArray(p))throw new RegistryError("Invalid admission draft.");const raw=p as unknown as Record<string,unknown>,allowed=new Set(["type","mode","name","command","cwd","owner_session_id","owner_session_file","max_output_bytes","max_runtime_s","interval_s","command_timeout_s","until_output_matches","idempotency_key","deadline_at","started_at"]);for(const k of Object.keys(raw))if(!allowed.has(k))throw new RegistryError(`Invalid admission draft field: ${k}.`);const safe={} as AdmissionDraft;for(const k of allowed)if(Object.prototype.hasOwnProperty.call(raw,k))(safe as unknown as Record<string,unknown>)[k]=raw[k];if(safe.type!=="bash"&&safe.type!=="monitor")throw new RegistryError("Invalid admission type.");for(const [v,label] of [[safe.command,"command"],[safe.cwd,"cwd"],[safe.owner_session_id,"owner session id"]] as const)required(v,label);if(!finitePositive(safe.max_output_bytes))throw new RegistryError("Invalid max output bytes.");if(safe.started_at!==undefined)assertIso(safe.started_at,"started_at");if(safe.deadline_at!==undefined)assertIso(safe.deadline_at,"deadline_at");return safe;}
function validateAttemptPatch(p:AttemptPatch):AttemptPatch {if(!p||typeof p!=="object"||Array.isArray(p))throw new RegistryError("Invalid attempt patch.");const raw=p as Record<string,unknown>,allowed=new Set(["output_bytes","pid","pgid","blocked_reason","next_run_at","last_hash"]);for(const k of Object.keys(raw))if(!allowed.has(k))throw new RegistryError(`Invalid attempt patch field: ${k}.`);if(p.output_bytes!==undefined)assertNonnegative(p.output_bytes,"output bytes");if(p.pid!==undefined)assertPositiveInteger(p.pid,"pid");if(p.pgid!==undefined)assertPositiveInteger(p.pgid,"pgid");if(p.blocked_reason!==undefined)required(p.blocked_reason,"blocked reason");if(p.next_run_at!==undefined)assertIso(p.next_run_at,"next_run_at");if(p.last_hash!==undefined)required(p.last_hash,"last hash");const safe:AttemptPatch={};for(const k of allowed)if(Object.prototype.hasOwnProperty.call(raw,k))(safe as Record<string,unknown>)[k]=raw[k];return safe;}
function validateLeaseArgs(runtimeId:string,ttlMs:number,now:Date){assertRuntimeId(runtimeId,"runtime id");assertDate(now);if(!Number.isFinite(ttlMs)||ttlMs<=0||ttlMs>MAX_TTL_MS)throw new RegistryError(`Lease TTL must be finite, positive, and at most ${MAX_TTL_MS}ms.`);}
function dispatchForward(from:DispatchState|undefined,to:DispatchState){return from===undefined?to==="dispatch_requested":from==="dispatch_requested"&&(to==="host_api_invoked"||to==="dispatch_sync_failed");}
function assertId(id:string):asserts id is string {if(!validId(id))throw new RegistryError("Invalid task id.");}function validId(id:string){return /^task_[a-z0-9]+_[a-f0-9]{12}$/.test(id);}function assertRuntimeId(v:string,label:string){required(v,label);if(v.length>1024||/[\0\r\n]/.test(v))throw new RegistryError(`Invalid ${label}.`);}function required<T>(v:T,label:string):T{if(typeof v!=="string"||!v.trim())throw new RegistryError(`Missing ${label}.`);return v;}function assertDate(v:Date){if(!(v instanceof Date)||!Number.isFinite(v.getTime()))throw new RegistryError("Invalid timestamp.");}function assertIso(v:string,label:string){if(!validIso(v))throw new RegistryError(`Invalid ${label}.`);}function validIso(v:string){const n=Date.parse(v);return Number.isFinite(n)&&new Date(n).toISOString()===v;}function finitePositive(v:unknown){return typeof v==="number"&&Number.isFinite(v)&&v>0;}function assertNonnegative(v:number,label:string){if(!Number.isFinite(v)||v<0)throw new RegistryError(`Invalid ${label}.`);}function assertPositiveInteger(v:number,label:string){if(!Number.isInteger(v)||v<=0)throw new RegistryError(`Invalid ${label}.`);}function order(a:TaskRecord,b:TaskRecord){return a.started_at.localeCompare(b.started_at)||a.task_id.localeCompare(b.task_id);}function code(e:unknown){return(e as NodeJS.ErrnoException)?.code;}function runtime(message:string,cause:unknown){return new RegistryRuntimeError(`${message}: ${cause instanceof Error?cause.message:String(cause)}`,{cause});}function alive(pid:number){try{process.kill(pid,0);return true;}catch(e){return code(e)==="EPERM";}}function sleep(ms:number){Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,ms);}function makeId(){return`task_${Date.now().toString(36)}_${randomBytes(6).toString("hex")}`;}export function isTerminal(s:TaskRecord["status"]):s is TerminalTaskStatus{return TERMINAL.has(s);}
