import assert from "node:assert/strict";
import { test } from "node:test";
import { QuestionService } from "../extensions/pi/question-service.js";
import { harness } from "./harness.js";
const params = { questions: [{ question: "Choose?", header: "Choice", options: [{ id: "a", label: "A" }, { id: "b", label: "B" }], multiSelect: false }], delivery: "blocking", urgency: "normal" };

test("live blocking waiter persists consumption before resolving and rebuild does not inject", async () => { const h = harness(); const pending = h.execute("ask_user_question", params, "live"); await Promise.resolve(); h.done({ kind: "submitted", answers: [{ question: "Choose?", selected_option_ids: ["a"], selected_labels: ["A"] }] }); const result = await pending; assert.equal(result.details.state, "answered"); assert.equal(h.messages.length, 0); assert.deepEqual(h.entries.slice(-2).map((e) => e.data.type), ["question.answered", "question.answer_delivered"]); await h.hooks.get("session_start")![0]({}, h.ctx); assert.equal(h.messages.length, 0); });
test("rebuild delivers unconsumed terminal once and marker suppresses replay", async () => { const h = harness(); const created = await h.execute("ask_user_question", { ...params, delivery: "non_blocking" }, "async"); const id = created.details.request_id; const requestCreated = h.entries[0].data; const service = new QuestionService(); service.apply(requestCreated); const terminal = service.answer(id, [{ question: "Choose?", selected_option_ids: [requestCreated.payload.questions[0].options[0].id], selected_labels: ["A"] }])!; h.branch.push({ type: "custom", customType: "async-user-question", data: terminal }); const start = h.hooks.get("session_start")![0]; await start({}, h.ctx); assert.equal(h.messages.length, 1); assert.deepEqual(h.messages[0].options, { deliverAs: "followUp", triggerTurn: true }); assert.equal(h.entries.at(-1).data.type, "question.answer_delivered"); await start({}, h.ctx); assert.equal(h.messages.length, 1); assert.equal(requestCreated.type, "question.created"); });
test("delivery failure leaves terminal unmarked for reconciliation retry", async () => { const h = harness(); const created = await h.execute("ask_user_question", { ...params, delivery: "non_blocking" }, "retry"); const request = h.entries[0].data; const service = new QuestionService(); service.apply(request); h.branch.push({ type: "custom", customType: "async-user-question", data: service.decline(created.details.request_id)! }); const original = h.pi.sendMessage; (h.pi as any).sendMessage = () => { throw new Error("offline"); }; await h.hooks.get("session_start")![0]({}, h.ctx); assert.ok(!h.entries.some((e) => e.data.type === "question.answer_delivered")); (h.pi as any).sendMessage = original; await h.hooks.get("session_start")![0]({}, h.ctx); assert.equal(h.entries.at(-1).data.type, "question.answer_delivered"); assert.equal(request.type, "question.created"); });
test("inbox picker draft survives close and reopen without durable draft entries", async () => {
  const h = harness(); const created = await h.execute("ask_user_question", { ...params, delivery: "non_blocking" }, "draft"); const id = created.details.request_id;
  await h.commands.get("questions").handler("", h.ctx); h.done(id); await Promise.resolve();
  h.component().handleInput("\x1b[B"); h.component().handleInput("\r"); h.component().handleInput("\x1b"); await Promise.resolve();
  assert.deepEqual(h.entries.map((entry) => entry.data.type), ["question.created"]);
  h.done(id); await Promise.resolve();
  assert.ok(h.component().render(80).some((line: string) => line.includes("Ready to submit")));
});

test("withdraw is terminal and idempotent", async () => { const h = harness(); const created = await h.execute("ask_user_question", { ...params, delivery: "non_blocking" }, "withdraw"); const id = created.details.request_id; const first = await h.execute("withdraw_user_question", { request_id: id, reason: "obsolete" }); const second = await h.execute("withdraw_user_question", { request_id: id }); assert.equal(first.details.state, "withdrawn"); assert.equal(second.details.state, "withdrawn"); assert.equal(h.entries.filter((e) => e.data.type === "question.withdrawn").length, 1); });
